# Copyright 2016, 2017 Peter Dimov
# Copyright (C) 2017 - 2019 James E. King III
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

#
# Generic Appveyor build script for boostorg repositories
# See: https://github.com/boostorg/boost-ci/
#
# Instructions for customizing this script for your library:
#
# 1. Customize the compilers and language levels you want.
# 2. If you have more than include/, src/, test/, example/, examples/,
#    benchmark/ or tools/ directories, set the environment variable DEPINST.
#    For example if your build uses code in "bench/" and "fog/" directories:
#      - DEPINST: --include bench --include fog
# 3. Enable pull request builds in your boostorg/<library> account.
#
# That's it - the script will do everything else for you.
#

version: 0.15.{build}-{branch}

shallow_clone: true

branches:
  only:
    - main
    - develop
    - /pr-.*/
    - /rc-.*/
    - /appveyor-.*/
#    - /bugfix-.*/
#    - /hotfix-.*/
#    - /feature-.*/
#    - /optimization-.*/
#    - /refactoring-.*/
#    - /redesign-.*/
#    - /task-.*/


build: off

matrix:
  # Adding MAYFAIL to any matrix job allows it to fail but the build stays green:
  allow_failures:
    - MAYFAIL: true

environment:

  matrix:
     - FLAVOR: G++9 Release C++20
       APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 20
       CXX: g++-9
       CC: gcc-9
       BUILD_SCRIPT: ci/appveyor/build.sh
 
     - FLAVOR: G++ 7 Release C++20
       APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 20
       CXX: g++-7
       CC: gcc-7
       BUILD_SCRIPT: ci/appveyor/build.sh
#      
#     - FLAVOR: Codecov
#       APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
#       ARCH: x64
#       CXX_STANDARD: 20
#       BUILD_SCRIPT: ci/appveyor/codecov_build.sh

     - FLAVOR: Ubsan
       APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
       ARCH: x64
       CXX_STANDARD: 20
       BUILD_SCRIPT: ci/appveyor/ubsan_build.sh
 
     - FLAVOR: Visual Studio 2019 C++2a
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
       GENERATOR: Visual Studio 16 2019
       ARCH: x64
       CONFIG: Debug
       CXX_STANDARD: 20

     - FLAVOR: Visual Studio 2019 C++2a
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
       GENERATOR: Visual Studio 16 2019
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 20
 
     - FLAVOR: Visual Studio 2017 C++2a
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       GENERATOR: Visual Studio 15 2017
       ARCH: x64
       CONFIG: Debug
       CXX_STANDARD: 20
 
     - FLAVOR: Visual Studio 2017 C++2a
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       GENERATOR: Visual Studio 15 2017
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 20
 
 #    - FLAVOR: Visual Studio 2017 C++2a
 #      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
 #      GENERATOR: Visual Studio 15 2017
 #      ARCH: Win32
 #      platform: x86
 #      CONFIG: Debug
 #      CXX_STANDARD: 20
 #
 #    - FLAVOR: Visual Studio 2017 C++2a
 #      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
 #      GENERATOR: Visual Studio 15 2017
 #      ARCH: Win32
 #      platform: x86
 #      CONFIG: Release
 #      CXX_STANDARD: 20
 
     - FLAVOR: Visual Studio 2017 C++17
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       GENERATOR: Visual Studio 15 2017
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 17
 
     - FLAVOR: Visual Studio 2017 C++14 (Default)
       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       GENERATOR: Visual Studio 15 2017
       ARCH: x64
       CONFIG: Release
       CXX_STANDARD: 14
 
#     - FLAVOR: Visual Studio 2017 C++11 (Default)
#       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#       GENERATOR: Visual Studio 15 2017
#       ARCH: x64
#       CONFIG: Debug
#       CXX_STANDARD: 11
# 
#     - FLAVOR: Visual Studio 2017 C++11 (Default)
#       APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#       GENERATOR: Visual Studio 15 2017
#       ARCH: x64
#       CONFIG: Release
#       CXX_STANDARD: 11


build_script:
  - cmd: ci\appveyor\build.bat
  - sh: chmod +x $BUILD_SCRIPT
  - sh: ls -l $BUILD_SCRIPT
  - sh: ./$BUILD_SCRIPT

test_script:
  - cmd: ctest -V -C %CONFIG%
