////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

[[main]]
= `<strf/outbuff.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <strf/outbuff.hpp>
:toclevels: 1
:icons: font

:min_size_after_recycle: <<min_size_after_recycle,min_size_after_recycle>>
:basic_outbuff: <<basic_outbuff,basic_outbuff>>

:basic_cstr_writer: <<basic_cstr_writer, basic_cstr_writer>>
:basic_string_maker: <<basic_string_maker, basic_string_maker>>
:basic_string_appender: <<basic_string_appender, basic_string_appender>>
:basic_streambuf_writer: <<basic_streambuf_writer, basic_streambuf_writer>>
:narrow_cfile_writer: <<narrow_cfile_writer, narrow_cfile_writer>>
:wide_cfile_writer: <<wide_cfile_writer, wide_cfile_writer>>
:garbage_buf: <<garbage_buf, garbage_buf>>
:garbage_buf_end: <<garbage_buf, garbage_buf_end>>

////
`<strf/outbuff.hpp>` is a lighweight header can be used in freestanding evironments. All other headers of the strf library include it. It's not affected by the `STRF_SEPARATE_COMPILATION` macro.
////

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
constexpr std::size_t min_size_after_recycle();

template <typename CharT>
class basic_outbuff
{ /{asterisk} \... {asterisk}/ };

template <typename CharT>
class basic_outbuff_noexcept: public basic_outbuff<CharT>
{ /{asterisk} \... {asterisk}/ };

template <typename CharT>
void put(basic_outbuff<CharT>& ob, CharT c);

template <typename CharT>
class basic_cstr_writer final: public basic_outbuff_noexcept<CharT>
{ /{asterisk} \... {asterisk}/};

template <typename CharT>
class discarded_outbuff final: public basic_outbuff_noexcept<CharT>
{ /{asterisk} \... {asterisk}/};

template <typename CharT>
CharT* outbuff_garbage_buf();

template <typename CharT>
CharT* outbuff_garbage_buf_end();

using bin_outbuff     = basic_outbuff<std::byte>;
using u8outbuff       = basic_outbuff<char8_t>;
using outbuff         = basic_outbuff<char>;
using u16outbuff      = basic_outbuff<char16_t>;
using u32outbuff      = basic_outbuff<char32_t>;
using woutbuff        = basic_outbuff<wchar_t>;

using u8cstr_writer  = basic_cstr_writer<char8_t>;
using cstr_writer    = basic_cstr_writer<char>;
using u16cstr_writer = basic_cstr_writer<char16_t>;
using u32cstr_writer = basic_cstr_writer<char32_t>;
using wcstr_writer   = basic_cstr_writer<wchar_t>;

} // namespace strf
----

== Function template `min_size_after_recycle` [[min_size_after_recycle]]
====
[source,cpp]
----
template <typename CharT>
constexpr std::size_t min_size_after_recycle();
----
[horizontal]
Return value:: Implementation-defined value greater than or equal to 64.
====

== Class template `basic_outbuff` [[basic_outbuff]]

=== Synopsis

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class basic_outbuff;
{
public:

    using char_type = CharT;

    basic_outbuff(const basic_outbuff&) = delete;
    basic_outbuff(basic_outbuff&&) = delete;
    basic_outbuff& operator=(const basic_outbuff&) = delete;
    basic_outbuff& operator=(basic_outbuff&&) = delete;

    virtual ~basic_outbuff() = default;

    CharT{asterisk} pointer() const noexcept;
    CharT{asterisk} end() const noexcept;
    std::size_t size() const noexcept;
    bool good() const noexcept;
    void advance_to(CharT{asterisk} p);
    void advance(std::size_t n);
    void require(std::size_t s);

    virtual void recycle() = 0;

protected:

    basic_outbuff(CharT{asterisk} pointer_, CharT{asterisk} end_);

    basic_outbuff(CharT{asterisk} pointer_, std::size_t n);

    void set_pointer(CharT{asterisk} p) noexcept;
    void set_end(CharT{asterisk} e) noexcept;
    void set_good(bool g) noexcept;
};

// global functions

template <typename CharT>
void put( basic_outbuff<CharT>& ob, CharT ch );

} // namespace strf
----

=== Member types

[[basic_outbuff_char_type]]
====
[source,cpp,subs=normal]
----
using char_type = CharT;
----
====

=== Public member functions

[[basic_outbuff_pointer]]
====
[source,cpp]
----
CharT* pointer() const noxcept;
----
[horizontal]
Return:: The memory position where the content shall be written.
====
[[basic_outbuff_end]]
====
[source,cpp]
----
CharT* end() const noxcept;
----
[horizontal]
Return:: The end of memory position where the content shall be written.
         Dereferencing `end()` has undefined behaviour.
====
[[basic_outbuff_size]]
====
[source,cpp]
----
std::size_t size() const noexcept;
----
[horizontal]
Return:: `end() - pointer()`
====
[[basic_outbuff_recycle]]
====
[source,cpp]
----
virtual void recycle() = 0;
----
[horizontal]
Posconditions::
- `size() >= {min_size_after_recycle}<CharT>()`
- The range [ `pointer()`, `end()` ) is valid accessible memory area
- If the return value of `good()` was `false` before this call to `recycle()`, then `good()` remains returning `false`.
====

// Effect::
// Depends on the derivate class, but if `good()` returns `true`,
// then supposedly consumes the content in the range [`p`, `pointer()`),
// where `p` is the value `pointer()` would have returned if called before
// any call to `advance` or `advance_to` in this object since the last
// time `recycle` was called in this object, or, in case `recycle`
// was not called in this object yet, since this object was constructed.


[[basic_outbuff_require]]
====
[source,cpp]
----
void require(std::size_t s)
----
[horizontal]
Effect:: Calls `recycle()` if `size() < s`.
Precondition:: `s \<= {min_size_after_recycle}<CharT>()`
Postcondition:: `size() >= s`
====
[[basic_outbuff_advance_to]]
====
[source,cpp]
----
void advance_to(CharT* p)
----
[horizontal]
Effect:: Advance the buffer's pointer to `p`.
Precondition:: `pointer() \<= p && p \<= end()`
Postcondition:: `pointer() == p`
====
[[basic_outbuff_advance_count]]
====
[source,cpp]
----
void advance(std::size_t n)
----
[horizontal]
Effect:: Same as `advance_to(pointer() + n)`
Precondition:: `n \<= size()`
====
[[basic_outbuff_advance]]
====
[source,cpp]
----
void advance()
----
[horizontal]
Effect:: Same as `advance_to(1)`
Precondition:: `pointer() != end()`
====
[[basic_outbuff_good]]
====
[source,cpp]
----
bool good() const;
----
[horizontal]
Return:: The state of this object.
Semantincs:: `good() == false` means that writting anything on
   `pointer()`, and calling `advance_to` and `recycle()` has no
   relevant side effect besides their postconditions.
Note:: The range [ `pointer()`, `end()` ) shall aways be a valid
accessible memory, even when `good()` returns `false`.
====

=== Protected Member functions

[[basic_outbuff_ctor_range]]
====
[source,cpp]
----
basic_outbuff(CharT* pointer_, CharT* end_)
----
[horizontal]
Preconditions::
- `pointer_ \<= end_`
- The range [ `pointer_`, `end_` ) must be an accessible memory area.
Posconditions::
- `pointer() == pointer_`
- `end() == end_`
- `good() == true`
====
[[basic_outbuff_ctor_count]]
====
[source,cpp]
----
basic_outbuff(CharT* pointer_, std::size_t n)
----
[horizontal]
Preconditions::
- The range [ `pointer_`, `pointer_ + n ` ) must be an accessible memory area.
Posconditions::
- `pointer() == pointer_`
- `end() == pointer_ + n`
- `good() == true`
====
[[basic_outbuff_set_pointer]]
====
[source,cpp]
----
void set_pointer(CharT* p) noexcept
----
[horizontal]
Postconditions:: `pointer() == p`
====
[[basic_outbuff_set_end]]
====
[source,cpp]
----
void set_end(CharT* e) noexcept
----
[horizontal]
Postconditions:: `end() == e`
====
[[basic_outbuff_set_good]]
====
[source,cpp]
----
void set_good(bool g) noexcept
----
[horizontal]
Postconditions:: `good() == g`
====

=== Global functions

[[basic_outbuff_put]]
====
[source,cpp,subs=normal]
----
template <typename CharT>
void put(basic_outbuff<CharT>& ob, CharT ch);
----
[horizontal]
Effect:: Same as:
+
[source,cpp]
----
if (ob.size() == 0) {
    ob.recycle();
}
*ob.pointer() = ch;
ob.advance();
----
====

[[basic_outbuff_noexcept]]
== Class template `basic_outbuff_noexcept`

[source,cpp]
----
namespace strf {

template <typename CharT>
class basic_outbuff_noexcept: public basic_outbuff<CharT>
{
public:

    virtual void recycle() noexcept = 0;

protected:

    using basic_outbuff<CharT>::basic_outbuff;
};

// type aliases

using outbuff_noexcept      = basic_outbuff_noexcept<char>;
using u8outbuff_noexcept    = basic_outbuff_noexcept<char8_t>;
using u16outbuff_noexcept   = basic_outbuff_noexcept<char16_t>;
using u32outbuff_noexcept   = basic_outbuff_noexcept<char32_t>;
using woutbuff_noexcept     = basic_outbuff_noexcept<wchar_t>;
using bin_outbuff_noexcept  = basic_outbuff_noexcept<std::byte>;

} // namespace strf
----

[[basic_cstr_writer]]
== Class template `basic_cstr_writer`

[source,cpp]
----
namespace strf {

template <typename CharT>
class basic_cstr_writer final: public basic_outbuff_noexcept<CharT>
{
public:

    basic_cstr_writer(CharT* dest, CharT* dest_end) noexcept;
    basic_cstr_writer(CharT* dest, std::size_t len) noexcept;
    template <std::size_t N>
    basic_cstr_writer(CharT (&dest)[N]) noexcept;

    void recycle() noexcept override;
    struct result
    {
        CharT* ptr;
        bool truncated;
    };
    result finish() noexcept;
};

} // namespace strf
----

=== Public member function

====
[source,cpp]
----
basic_cstr_writer(CharT* dest, CharT* dest_end) noexcept;
----
[horizontal]
Precondition:: `dest < dest_end`
Postconditions::
- `good() == true`
- `pointer() == dest`
- `end() == dest_end - 1`
====
====
[source,cpp]
----
basic_cstr_writer(CharT* dest, std::size_t dest_size) noexcept;
----
[horizontal]
Precondition:: `dest_size != 0`
Postconditions::
- `good() == true`
- `pointer() == dest`
- `end() == dest + dest_size - 1`
====
====
[source,cpp]
----
template <std::size_t N>
basic_cstr_writer(CharT (&dest)[N]) noexcept;
----
[horizontal]
Postconditions::
- `good() == true`
- `pointer() == dest`
- `end() == dest + N - 1`
====
====
[source,cpp]
----
void recycle() noexcept;
----
[horizontal]
Postconditions::
- `good() == false`
- `pointer() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====
====
[source,cpp]
----
result finish() noexcept;
----
[horizontal]
Effects::
- Assign to `'\0'` the position after the last written character in memory area used to initialize this object and set this object into "bad" state.
Return value::
- `result::truncated` is `true` if `recycle` or `finish` has ever been called in this object.
- `result::ptr` points to the termination character `'\0'`.
Postconditions::
- `good() == false`
- `pointer() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====

[[discarded_outbuff]]
== Class template `discarded_outbuff`

`discarded_outbuff` it's the library's analogous to `/dev/null`.
A `discarded_outbuff` object ignores anything written to it.

[source,cpp]
----
namespace strf {

template <typename CharT>
class discarded_outbuff final: public basic_outbuff_noexcept<CharT>
{
public:
    discarded_outbuff() noexcept;
    void recycle() noexcept override;
};

} // namespace strf
----
====
[source,cpp]
----
discarded_outbuff() noexcept;
----
[horizontal]
Postconditions::
- `good() == false`
- `pointer() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====
====
[source,cpp]
----
void recycle() noexcept;
----
[horizontal]
Postconditions::
- `good() == false`
- `pointer() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====

[[garbage_buf]]
== Garbage buffer
These function templates return the begin and the end of a memory area that is never supposed to be read. It can be used when implementing a class that derives from `basic_outbuff` to set the buffer when the state is "bad".

[source,cpp]
----
template <typename CharT>
CharT* garbage_buf() noexcept;
----

[source,cpp]
----
template <typename CharT>
CharT* garbage_buf_end() noexcept;
----


