////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

== facets_pack

[[facets_pack]]
=== Class template `facets_pack`

====
[source,cpp]
----
template <typename ... FPE>
class facets_pack;
----
::
Compile-time requirements::: All types in `FPE\...` satisfy
 <<FacetsPackElement, _FacetsPackElement_>>.
====

==== Member functions
===== Constructors
====
[source,cpp]
----
constexpr facets_pack(const facets_pack& other);
----
::
Effects::: Initializes each element with the const reference
          of the corresponding element in `other`
Compile-time requirements::: `std::is_copy_constructible_v<FPE> && \...`,
      otherwise this constructor does not participate in overload resolution.
====
====
[source,cpp]
----
constexpr facets_pack(facets_pack&& other);
----
::
Effects::: Initializes each element from the
          rvalue reference of the corresponding element in `other`
Compile-time requirements::: `std::is_move_constructible_v<FPE> && \...`, otherwise this
          constructor does not participate in overload resolution.
====
====
[source,cpp]
----
constexpr explicit facets_pack(const FPE& ... fpe)
----
::
Effects::: Initializes each element with the correspondig value in `fpe\...`
Compile-time requirements::: `std::is_copy_constructible_v<FPE> && \...`, otherwise this
      constructor does not participate in overload resolution.
====
====
[source,cpp]
----
template <typename... U>[br]
constexpr explicit facets_pack(U&&... u)
----
::
Effects::: Initializes each element with the correspondig value in `std::forward<U>(u)\...`.
Compile-time requirements::: This constructor does not participate in overload resolution, unless
- `sizeof\...(U) == sizeof\...(FPE)`, and
- `sizeof\...(U) != 0`, and
- `std::is_constructible_v<FPE, U&&> && \...`
====
===== Assignment operators (deleted)
====
[source,cpp]
----
   facets_pack& operator=(const facets_pack&) = delete
   facets_pack& operator=(facets_pack&&) = delete;
----
::
Assignments are deleted because they seem unecessary and it's unclear
what would be the best
implementation in the case there is any reference type in `FPE\...`.
====

[[pack]]
=== Function template `pack`
====
[source,cpp]
----
template <typename ... Types>
constexpr facets_pack<VTypes...>  pack(const Types& ... args)
----
::
Effects::: Creates a `facets_pack` object from `args\...` 
Return type::: `facets_pack<VTypes\...>`, where for each `Ti` in `Types\...`,
               the corresponding `Vi` in `VTypes\...` is:
- `const F&` , if `Vi` is `std::reference_wrapper<F>`
- `const Vi` , if `Vi` <<facet_stored_by_value, `facet_stored_by_value<Vi>`>> is `false`
- `Ti` , otherwise
====

[[get_facet]]
=== Function template `get_facet`
====
[source,cpp]
----
template <typename FCat, typename Tag, typename ... T>
constexpr decltype(auto) get_facet(const facets_pack<T...>& fp);
----
::
Effects::: If <<has_facet, `has_facet<FCat, Tag>(fp)`>> returns `true` then
          returns <<do_get_facet,`do_get_facet<FCat, Tag>(fp)`, otherwise
          return `FCat::get_default()`.
Compile-time requirements:::  `FCat` satisfies <<FacetCategory,_FacetCategory_>>.
====

[[has_facet]]
=== Hypothetical function template `fas_facet`
NOTE: This function template does not exists in this library.
       It is only documented to help to explain the
       <<get_facet, `get_facet`>> function template.
====
[source,cpp]
----
template <typename FCat, typename Tag, typename FPE>
constexpr bool has_facet(const FPE& fpe)
----
::
Effects:::
- If `FPE` is a <<facets_pack, `facets_pack`>>, then return wheter there
  is any elemente `elm` in `fpe` such that `has_facet<FCat, Tag>(elm)`
  is `true`.
- If `FPE` is <<constrained_fpe, `constrained_fpe<FPE, Filter>`>>,
  then return `Filter<Tag>::value && has_facet<FCat, Tag>(fpe.get())`.
- If `FPE` satisfies <<facet, _Facet_>>, return `std::is_same_v<FCat, FacetCategory<FPE>>`

Compile-time requirements:::
- `FCat` satisfies <<FacetCategory, _FacetCategory_>>.
- `FPE` satisfies <<FacetsPackElement, _FacetsPackElement_>>.
====


[[do_get_facet]]
=== Hypothetical function template `do_get_facet`
NOTE: This function template is not part of the library.
      It only is documented to help to explaine the
      <<get_facet,`get_facet`>> function template
====
[source,cpp]
----
template <typename FCat, typename Tag, typename FPE>
constexpr decltype(auto) do_get_facet(const FPE& fpe);
----
::
Compile-time requirements:::
- `FCat` satisfies <<FacetCategory,_FacetCategory_>>.
- `FPE` satisfies <<FacetsPackElement,_FacetsPackElement_>>.
- `has_facet<FCat, Tag>(fpe)` is `true`.
====

[[constrained_fpe]]
=== Class template `constrained_fpe`

====
[source,cpp]
----
template <template <class> class Filter, typename FPE>
class constrained_fpe;
----
::
The class template `constrained_fpe` is designed to be used in
<<facets_pack,`facets_pack`>>. `constrained_fpe<Filter, FPE>`
holds a value of `FPE` that will only be returned by
<<get_facet, ``get_facet<Category, Tag>``>> if
`Filter<Tag>::value` is `true`.

Compile-time requirements:::
- For any type `T`, `Filter<T>` has a member variable `value` that is a
  static constexpr value whose type is implicitly convertible to `bool`
- `FPE` satisfies <<ConstrainableFacetsPackElement,_ConstrainableFacetsPackElement_>>.
====

==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <template <class> class Filter, typename FPE>
class constrained_fpe
{
public:
    // <<constrained_fpe_constructor, constructors>>
    constexpr constrained_fpe(const constrained_fpe&) = default;
    constexpr constrained_fpe(constrained_fpe&& other) = default;
    constexpr constrained_fpe(const FPE& f);

    // <<constrained_fpe_element_access, element access>>
    constexpr const FPE& get() const;

private:
    FPE element; // exposition only;
};

} // namespace strf
----

==== Member functions
[[constrained_fpe_constructor]]
===== Constructors
====
[source,cpp]
----
constexpr explicit constrained_fpe(const FPE& fpe);
----
::
Effect::: Initializes the element of the `constrained_fpe` with `fpe`.
====
====
[source,cpp]
----
constexpr constrained_fpe(const constrained_fpe& other);
----
::
Effect::: Initializes the element of the `constrained_fpe` from
     the const reference of the element of `other`.
Compile-time requirements::: `std::is_copy_constructible<FPE>::value` is `true`.
====
====
[source,cpp]
----
constexpr constrained_fpe(constrained_fpe&& other);
----
::
Effect::: Initializes the element of the `constrained_fpe` from
     the rvalue reference of element of `other`.
Compile-time requirements::: `std::is_move_constructible<FPE>::value` is `true`.

[[constrained_fpe_element_access]]
====
===== Element access

====
[source,cpp]
----
constexpr const FPE& get() const;
----
::
Effect::: Return the stored element;
====
=== Function template `constrain`
====
[source]
----
template <template <class> class Filter, typename T>
constexpr constrained_fpe<Filter, U> constrain(const T& arg);
----
::
`constrain` is just a syntatic sugar to instantiate <<constrained_fpe, `constrained_fpe`>>

Effect::: Create a <<constrained_fpe, `constrained_fpe`>> object from `args`
Return type::: `constrained_fpe<Filter, U>`, where `U` is
- `const F&`, if `T` is `std::reference_wrapper<F>` is `true`
- `const T&`, if `facet_stored_by_value<T>` is `false`
- `T`, otherwise
Compile-time requirements:::
`T` is a type such that `U` satisfies <<FacetsPackElement, _FacetsPackElement_>>.
====

[[FacetsPackElement]]
=== Type requirement _FacetsPackElement_
A given type `F` satisfies _FacetsPackElement_ if, and only if, the following conditions is true:

- `F` satisfies <<Facet,_Facet_>>
  and <<facet_stored_by_value,`facet_stored_by_value<F>`>> is `true`
- `F` is an instance of <<facets_pack,`facets_pack`>.
- `F` is an instance of <<constrained_fpe,`constrained_fpe`>>.
- `F` is `const `F2&`, where `F2` satisfies one of the previous requirements.
- `F` is `const `F2&`, where `F2` satisfies <<Facet, _Facet_>>,
  and `facet_stored_by_value<F2>` is `false`.

[[ConstrainableFacetsPackElement]]
=== Type requirement _ConstrainableFacetsPackElement_
A given a type `F` is a _ConstrainableFacetsPackElement_, if it satisfies
<<FacetsPackElement,_FacetsPackElement_>> and the following rules:

- If `F` is `const F2&`, then `F2` satifies the _ConstrainableFacetsPackElement_
  requirements.
- If `F` is `facets_pack<F2\...>`, then all types in `F2\...` satisfy the
  _ConstrainableFacetsPackElement_ requirements.
- If `F` is not an instance of <<constrained_fpe,`constrained_fpe`>>,
  then it satifies <<Facet,`Facet`>> and
  `facet_category<FPE>::constrainable` is `true`.

[[Facet]]
=== Type requirement _Facet_
A given a type `F` satisfies `Facet` if all of the following conditions are met:

- If `F` is abstract or not _CopyConstructible_, then
  <<facet_stored_by_value `facet_stored_by_value<F>`>>
  must be `false`.
- <<facet_category,`facet_category<F>`>>
  satisfies the <<FacetCategory,_FacetCategory_>>
  requirements.

[[FacetCategory]]
=== Type requirement _FacetCagory_
A given a type `FCat` satisfies `FacetCategory` if:

- `FCat` has a static member function named `get_default` that takes
  no argument and whose return type is either `F` or `const F&`,
  where `F` is a type that satisfies the requirements associated to
  `FCat`.
- `FCat` has a member named `constrainable` that is a static constexpr
  value convertible to `bool`. ( If this value is `false` then
  the facets associated `FCat` can not be <<constrained_fpe,constrained>> ).

[[facet_traits]]
=== Class template `facet_traits`

This class template provides the <<Facet,Facet>> informations.
If you create a new facet, you can either define such informations as
members of the facet, or specialize `facet_traits`.

[source]
----
template <typename F>
class facet_traits
{
public:
    using category = /* Facet::category or void */;
    constexpr static bool store_by_value = /* Facet::store_by_value or true */;
};
----
==== Public members
====
[source]
----
constexpr static bool store_by_value;
----
Value:: Equal to `F::store_by_value` is such expression is well formed
and implicitly convetible to `bool`, otherwise it is `false`.
====
====
[source]
----
typename /* */ category;
----
Same as `Facet::category` if such member exist and is a type,
otherwise it is an alias to `void`.
====
==== Specialization
====
[source]
----
template <typename F>
class facet_traits<const F>
{
public:
    using category = typename facet_traits<F>::category;
    constexpr static bool store_by_value = facet_stored_by_value<F>::store_by_value;
};
----
====

[[facet_category]]
=== Type alias `facet_category`
`facet_category` is just a syntatic sugar:
====
[source]
----
template <typename Facet>
using facet_category = facet_traits<Facet>::typename category;
----
====
[[facet_stored_by_value]]
=== Variable template `facet_stored_by_value`
====
[source]
----
template <typename T>
constexpr bool facet_stored_by_value;
----
::
Value::: ``facet_traits<T>::store_by_value`` if such expression
       is well formed and implicitly convertible to `bool`,
       otherwise the value is `true`.
====
