////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

== List of printable types


=== Strings
Types::
`const CharT*`, `std::string_view<CharT, Traits>`
and `std::basic_string<CharT, Traits, Alloc>`
::
where:
::
- `CharT` is the character type. If it is not the same as the output character type ( defined by the <<destinations,destination>> ), then it is necessary to use the `conv` or `sani` format function.
- `Traits` can be any type that satisfies https://en.cppreference.com/w/cpp/named_req/CharTraits[CharTraits]
- `Alloc` can be any type that satisfies https://en.cppreference.com/w/cpp/named_req/Allocator[Allocator]

Format functions::
( in addition to <<alignment_format_functions, alignment functions>> )

`p(<<strf_hpp#width_t,width_t>> limit)`:::
   Does not print the whole string if its width is greater than `limit`,
   but the greatest possible amount of its leading Unicode code points
   such that the width is not greater than `limit`.
+
////
   but prints the maxixum leading sub-string such that its width
   is not greater than `limit`.
   Prints the maximum amount of Unicode code points such that
   the width is not greater than `limit`.
   __To-to__
////
+
`template <typename Encoding> sanitize_from_encoding(Encoding enc)`:::
   Translates input string from `enc` to the output encoding.
   If the encodings are the same then sanitizes the input string.
`sanitize_encoding()`::: Translates input string from the encoding associated to `CharT` to
            the output encoding. If these encodings are the same
            then sanitizes the input string.
`template <typename Encoding> convert_from_encoding(Encoding enc)`:::
   Translates input string from `enc` to the
   output encoding, if these encodings are not the same.
   Otherwise, copies input string as it is.
`convert_encoding()` ::: Translates input string from the encoding associated to `CharT` to
          the output encoding, if these encodings are not the same.
          Otherwise, copies the input string as it is.
`template <typename Encoding>  sani(Encoding enc)`::: Equivanlent to `sanitize_encoding(enc)`
`template <typename Encoding>  conv(Encoding enc)`::: Equivanlent to `convert_encoding(enc)`
`sani()`::: Equivalent to `sanitize_encoding()`
`conv()`::: Equivalent to `convert_encoding()`
+
.Example
[source,cpp]
----
auto str = strf::to_string(strf::center(u" Hello! ", 16, '*').conv());
assert(str == "**** Hello! ****");
----
+
See also the section about <<encoding_conversion,encoding conversion>>.

//-
Facet categories::
- `<<width_calculator,width_calculator_c>>`
- `<<character_encoding,char_encoding_c>><__CharType__>`
- `<<surrogate_policy,surrogate_policy_c>>`
- `<<invalid_seq_policy,invalid_seq_policy_c>>`

=== Single characters
Type:: `CharT`, that is the output character type defined by the <<destinations,destination>>.

Format functions::
( in addition to <<alignment_format_functions, alignment functions>> )
[horizontal]
`multi(std::size_t count)`::: Prints the character `count` times. Default value is `1`.

//-
Facet categories::
- `<<width_calculator,width_calculator_c>>`
- `<<character_encoding,char_encoding_c>><__CharType__>`: Used to encode the <<alignment_format_functions,fill character>>.

=== `bool`
Type:: `bool`
Format functions::
<<alignment_format_functions, Alignment functions>> only.
Facet categories::
- `<<lettercase,lettercase_c>>`
- `<<character_encoding,char_encoding_c>><__CharType__>`: Used to encode the <<alignment_format_functions,fill character>>.

=== `const void*`
Types:: `const void*`
Format functions::
The <<alignment_format_functions, alignment functions>> only.

Facet categories::
- `<<lettercase,lettercase_c>>`
- `<<numpunct, numpunct_c>><16>`
- `<<character_encoding,char_encoding_c>><__CharType__>`: Used to encode the <<alignment_format_functions,fill character>> and the <<numpunct,punctuation characters>>.

=== Integers

Types::
`short`,
`int`,
`long int`,
`long long int`,
`unsigned short`,
`unsigned int`,
`unsigned long int` and
`unsigned long long int`

[[int_fmt]]
Format functions::
( in addition to <<alignment_format_functions, alignment functions>> )
[horizontal]
`dec()`::: Use decimal base ( This is already the default, though )
`hex()`::: Use hexadecimal base.
`oct()`::: Use octal base.
`bin()`::: Use binary base.
`p(unsigned precision)`::: Ensures that at least `precision` digits
are printed by adding extra zero leading digits if necessary.
`operator+()`::: When in decimal base, prints the positive sign
`"+"` when value is non negative. No effect for other bases.
`operator*()`::: Prints the base indication
( `"0x"` for hexadecimal, `"0"` for octal and `"0b"` for binary ).
No effect in decimal base.
`operator~()`::: Equivalent to `operator*()`. Deprecated.

//-
Facet categories::
- `<<lettercase,lettercase_c>>`
- `<<numpunct, numpunct_c>><__Base__>`
- `<<character_encoding,char_encoding_c>><__CharType__>`: Used to encode the <<alignment_format_functions,fill character>> and the <<numpunct,punctuation characters>>.


=== Floating Points
Types::
`float`, `double`

Format functions::
( In addition to the <<alignment_format_functions, alignment functions>> )
[horizontal]
`operator+()`::: When in decimal base, prints the positive sign
`"+"` if the value is non negative. No effect for other bases.
`operator*()`:::  Prints the decimal point even when there
are no fractional digits.
`operator~()`::: Equivalent to `operator*()`. Deprecated.
`sci()`::: Prints in scientific notation, like this: `"1.2345e+02"`.
`fixed()`::: Prints in decimal notation, like this: `"123.45"`.
`gen()`::: This is the default notation.
When precision is unspecified ( or equal to `(unsigned)-1` )
prints in the scientfic notation if, and only if, it is shorter
than the fixed notation. Otherwise ( when precision is specified ),
does like in `std::printf`:
uses the scientfic notation if the exponent is less than -4 or greater
than or equal to the precision. Trailing fractional zeros are not printed.
`hex()`::: Prints in hexadecimal notation, like this `"-0x1.abcd123e+5"`
`p(unsigned precision)`::: If `precision == (unsigned)-1`, which is
the default, then prints the minimal amount of digits so that value
can be fully recovered by a parser. Otherwise, if notation is __general__,
`precision` is the number of significant digits. Otherwise, it is
the number of fractional digits. `precision == 0` has the same effect as
`precision == 1`.

//-
Facet categories::
- `<<lettercase,lettercase_c>>`
- `<<numpunct, numpunct_c>><10>`
- `<<character_encoding,char_encoding_c>><__CharType__>`: Used to encode the <<alignment_format_functions,fill character>> and the <<numpunct,punctuation characters>>.

=== Ranges

==== Without formatting

[source,cpp]
----
namespace strf {

template <typename Range>
/*...*/ range(const Range& r);

template <typename T, std::size_t N>
/*...*/ range(T (&array)[N]);

template <typename Iterator>
/*...*/ range(const Iterator& begin, const Iterator& end);

// With operation

template <typename Range, typename UnaryOperation>
/*...*/ range(const Range& r, UnaryOperation unary_op);

template <typename T, std::size_t N, typename UnaryOperation>
/*...*/ range(T (&array)[N], UnaryOperation unary_op);

template <typename Iterator, typename UnaryOperation>
/*...*/ range( const Iterator& begin
             , const Iterator& end
             , UnaryOperation unary_op );

// With separator:

template <typename Range, typename CharT>
/*...*/ separated_range(const Range& r, const CharT* separator);

template <typename T, std::size_t N, typename CharT>
/*...*/ separated_range(T (&array)[N], const CharT* separator);

template <typename Iterator, typename CharT>
/*...*/ separated_range( const Iterator& begin
                       , const Iterator& end
                       , const CharT* separator );

// With separator and operation

template <typename Range, typename CharT, typename UnaryOperation>
/*...*/ separated_range( const Range& r
                       , const CharT* separator
                       , UnaryOperation unary_op );

template <typename T, std::size_t N, typename CharT, typename UnaryOperation>
/*...*/ separated_range( T (&array)[N]
                       , const CharT* separator
                       , UnaryOperation unary_op );

template <typename Iterator, typename CharT, typename UnaryOperation>
/*...*/ separated_range( const Iterator& begin
                       , const Iterator& end
                       , const CharT* separator
                       , UnaryOperation unary_op );
} // namespace strf
----

.Examples
[source,cpp,subs=normal]
----
int arr[3] = { 11, 22, 33 };

auto str = strf::to_string(strf::range(arr));
assert(str == "112233");

str = strf::to_string(strf::separated_range(arr, ", "));
assert(str == "11, 22, 33");

auto op = [](auto x){ return strf::<<join,join>>('(', +strf::fmt(x * 10), ')'); };

str = strf::to_string(strf::separated_range(arr, ", ", op));
assert(str == "(+110), (+220), (+330)");
----

==== With formatting

[source,cpp]
----
namespace strf {

template <typename Range>
/*...*/ fmt_range(const Range& r);

template <typename T, std::size_t N>
/*...*/ fmt_range(T (&array)[N], const Range& r);

template <typename Iterator>
/*...*/ fmt_range(const Iterator& begin, const Iterator& end);

// With separator

template <typename Range, typename CharT>
/*...*/ fmt_separated_range(const Range& r, const CharT* separator);

template <typename T, std::size_t N, typename CharT>
/*...*/ fmt_separated_range(T (&array)[N], const CharT* separator);

template <typename Iterator, typename CharT>
/*...*/ fmt_separated_range( const Iterator& begin
                           , const Iterator& end
                           , const CharT* separator );
} // namespace strf
----
Any format function applicable to the element type of the
range can also be applied to the
expression `strf::fmt_range(/{asterisk}\...{asterisk}/)` or
`strf::fmt_separated_range(/{asterisk}\...{asterisk}/)`.
This way the format functions is applied to all elements:

.Example 1
[source,cpp]
----
std::vector<int> vec = { 11, 22, 33 };
auto str1 = strf::to_string("[", +strf::fmt_separated_range(vec, " ;") > 4, "]");
assert(str1 == "[ +11 ; +22 ; +33]");
----

.Example 2
[source,cpp]
----
std::vector<int> vec = { 11, 22, 33 };
auto str2 = strf::to_string
    ( "["
    , *strf::fmt_separated_range(vec, " / ").fill('.').hex() > 6,
    " ]");

assert(str2 == "[..0xfa / ..0xfb / ..0xfc]");
----

[[join]]
=== Joins

==== Without alignment

[source,cpp]
----
namespace strf {

template <typename ... Args>
/*...*/ join(const Args& ... args);

}
----

==== With alignment

You can apply the <<alignment_format_functions,alignment format functions>>
one the return type of `join(args\...)`

[source,cpp]
----
auto str = strf::to_string
    ("---", strf::join("abc", "def", 123) > 15, "---");

assert(str == "---      abcdef123---");
----

The `split_pos` function specifies how many arguments
go before the fill when the `operator%` is used.
[source,cpp]
----
str = strf::to_string
    ( strf::join('a', 'b', 'c', 'd', 'e', 'f').split_pos(2) % 10 );
assert(str == "ab    cdef");
----

The functions below provide an alternartive syntax to create aligned
join. Their return type has the `operator()(const Args& \... args)` member function
that receives the elements of the join.


[[text_alignment]]
[source,cpp]
----
namespace strf {

enum class text_alignment {left, right, split, center};

/* ... */ join_align( std::int16_t width
                    , text_alignment align
                    , char32_t fillchar = U' '
                    , std::ptrdiff_t split_pos = 0 );
/* ... */ join_center(int width, char32_t fillchar = U' ');
/* ... */ join_left(int width, char32_t fillchar = U' ');
/* ... */ join_right(int width, char32_t fillchar = U' ');
/* ... */ join_split(int width, int split_pos);
/* ... */ join_split( std::int16_t width
                    , char32_t fillchar
                    , std::ptrdiff_t split_pos );
}
----

.Example
[source,cpp]
----
auto str = strf::to_string
    ("---", strf::join_right(15) ("abc", "def", 123), "---");
assert(str == "---      abcdef123---");

str = strf::to_string
    ("---", strf::join_center(15) ("abc", "def", 123), "---");
assert(str == "---   abcdef123   ---");

str = strf::to_string
    ( "---"
    , strf::join_left(15, U'.') ("abc", strf::right("def", 5), 123)
    , "---" );
assert(str == "---abc  def123....---");

str = strf::to_string
    ( "---"
    , strf::join_split(15, '.', 1) (strf::left("abc", 5), "def", 123)
    , "---" );
assert(str == "---abc  ....def123---");
----




=== Facets [[global_function_with]]
It is possible to <<facet_overriding,override facets>>
to only a subset of the input arguments.

[source,cpp]
----
namespace strf {

template < typename FPack >
class inner_pack
{
public:
    template <typename... Args>
    /*...*/  operator()(const Args&... args) const;
    //...
};

template <typename ... Facets>
inner_pack</*...*/> with(const Facets&... facets);
----
.Example 1
[source,cpp]
----
auto str = strf::to_string.with(strf::numpunct<10>(1))
    ( 10000
    , "  "
    , strf::hex(0x10000)
    , strf::with( strf::numpunct<10>(3)
                , strf::numpunct<16>(4).thousands_sep('\'') )
        ( "  { "
        , 10000
        , "  "
        , strf::hex(0x10000)
        , " }" ) );

assert(str == "1,0,0,0,0  10000  { 10,000  1'0000 }");
----

.Example 2
[source,cpp]
----
auto fp = strf::pack
    ( strf::numpunct<10>(3)
    , strf::numpunct<16>(4).thousands_sep('\'') );

auto str = strf::to_string.with(strf::numpunct<10>(1))
    ( 10000
    , "  "
    , strf::hex(0x10000)
    , strf::with(fp)
        ( "  { "
        , 10000
        , "  "
        , strf::hex(0x10000)
        , strf::with
            (strf::numpunct<10>(2).thousands_sep('.'))
            ("  { ", 10000, " }")
        , " }" ) );

assert(str == "1,0,0,0,0  10000  { 10,000  1'0000  { 1.00.00 } }");
----
