////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

== Outbuf

[[min_size_after_recycle]]
=== `min_size_after_recycle`
====
[source,cpp]
----
template <std::size_t CharSize>
constexpr std::size_t min_size_after_recycle();
----
[horizontal]
Return value:: Implementation-defined value greater than or equal to 64.
====

[[underlying_outbuf]]
=== Class template `underlying_outbuf`

==== Synopsis

[source,cpp]
----
namespace strf {

template <std::size_t CharSize>
class underlying_outbuf;
{
public:

    using char_type = /*see below*/;

    underlying_outbuf(const underlying_outbuf&) = delete;
    underlying_outbuf(underlying_outbuf&&) = delete;
    underlying_outbuf& operator=(const underlying_outbuf&) = delete;
    underlying_outbuf& operator=(underlying_outbuf&&) = delete;

    virtual ~underlying_outbuf() = default;

    char_type* pos() const noexcept;
    char_type* end() const noexcept;
    std::size_t size() const noexcept;
    bool good() const noexcept;
    void advance_to(char_type* p);
    void advance(std::size_t n);
    void require(std::size_t s);

    virtual bool recycle() = 0;

protected:

    underlying_outbuf(char_type* pos_, char_type* end_);

    underlying_outbuf(char_type* pos_, std::size_t n);

    void set_pos(char_type* p) noexcept;
    void set_end(char_type* e) noexcept;
    void set_good(true g) noexcept;
};

// global type aliases

template <std::size_t CharSize>
using underlying_char_type = typename underlying_outbuf<CharSize>::char_type

// global functions

template <std::size_t CharSize>
void write( underlying_outbuf<CharSize>& ob
          , const underlying_char_type<CharSize>* data
          , std::size_t data_size );

template <std::size_t CharSize>
void write( underlying_outbuf<CharSize>& ob
          , const underlying_char_type<CharSize>* data
          , const underlying_char_type<CharSize>* data_end );

template <std::size_t CharSize>
void put( underlying_outbuf<CharSize>& ob
        , underlying_char_type<CharSize> ch );

} // namespace strf
----

==== Member types

[[underlying_char_type]]
====
[source,cpp]
----
using char_type = /*see below*/;
----
[horizontal]
Same as::
- `std::uint8_t` if `CharSize == 1`
- `char16_t` if `CharSize == 2`
- `char32_t` if `CharSize == 4`

It is undefined for any other `CharSize` value.
====

==== Public member functions

[[underlying_outbuf_pos]]
====
[source,cpp]
----
char_type* pos() const noxcept;
----
[horizontal]
Return:: The memory position where the content shall be written.
====
[[underlying_outbuf_end]]
====
[source,cpp]
----
char_type* end() const noxcept;
----
[horizontal]
Return:: The end of memory position where the content shall be written.
         Dereferencing `end()` has undefined behaviour.
====
[[underlying_outbuf_size]]
====
[source,cpp]
----
std::size_t size() const noexcept;
----
[horizontal]
Return:: `end() - pos()`
====
[[underlying_outbuf_recycle]]
====
[source,cpp]
----
virtual void recycle() = 0;
----
[horizontal]
Posconditions::
- `size() >= {min_size_after_recycle}<CharSize>()`
- The range [ `pos()`, `end()` ) is valid accessible memory area
- If the return value of `good()` was `false` before this call to `recycle()`, then `good()` remains returning `false`.
====

// Effect::
// Depends on the derivate class, but if `good()` returns `true`,
// then supposedly consumes the content in the range [`p`, `pos()`),
// where `p` is the value `pos()` would have returned if called before
// any call to `advance` or `advance_to` in this object since the last
// time `recycle` was called in this object, or, in case `recycle`
// was not called in this object yet, since this object was constructed.


[[underlying_outbuf_require]]
====
[source,cpp]
----
void require(std::size_t s)
----
[horizontal]
Effect:: Calls `recycle()` if `size() < s`.
Precondition:: `s \<= {min_size_after_recycle}<CharSize>()`
Postcondition:: `size() >= s`
====
[[underlying_outbuf_advance_to]]
====
[source,cpp]
----
void advance_to(char_type* p)
----
[horizontal]
Effect:: Advance the buffer's position to `p`.
Precondition:: `pos() \<= p && p \<= end()`
Postcondition:: `pos() == p`
====
[[underlying_outbuf_advance_count]]
====
[source,cpp]
----
void advance(std::size_t n)
----
[horizontal]
Effect:: Same as `advance_to(pos() + n)`
Precondition:: `n \<= size()`
====
[[underlying_outbuf_advance]]
====
[source,cpp]
----
void advance()
----
[horizontal]
Effect:: Same as `advance_to(1)`
Precondition:: `pos() != end()`
====
[[underlying_outbuf_good]]
====
[source,cpp]
----
bool good() const;
----
[horizontal]
Return:: The state of this object. If the return value is `false`,
then it means that calling `advance` of `advance_to` has no
relevant side effect because the content written in the buffer
will not be read anymore.
Note:: The range [ `pos()`, `end()` ) shall aways be a valid
accessible memory, even when `good()` returns `false`.
====

==== Protected Member functions

[[underlying_outbuf_ctor_range]]
====
[source,cpp]
----
underlying_outbuf(CharT* pos_, CharT* end_)
----
[horizontal]
Preconditions::
- `pos_ \<= end_`
- The range [ `pos_`, `end_` ) must be an accessible memory area.
Posconditions::
- `pos() == pos_`
- `end() == end_`
- `good() == true`
====
[[underlying_outbuf_ctor_count]]
====
[source,cpp]
----
underlying_outbuf(CharT* pos_, std::size_t n)
----
[horizontal]
Preconditions::
- The range [ `pos_`, `pos_ + n ` ) must be an accessible memory area.
Posconditions::
- `pos() == pos_`
- `end() == pos_ + n`
- `good() == true`
====
[[underlying_outbuf_set_pos]]
====
[source,cpp]
----
void set_pos(CharT* p) noexcept
----
[horizontal]
Postconditions:: `pos() == p`
====
[[underlying_outbuf_set_end]]
====
[source,cpp]
----
void set_end(CharT* e) noexcept
----
[horizontal]
Postconditions:: `end() == e`
====
[[underlying_outbuf_set_good]]
====
[source,cpp]
----
void set_good(bool g) noexcept
----
[horizontal]
Postconditions:: `good() == g`
====

==== Global functions

[[underlying_outbuf_put]]
====
[source,cpp]
----
template <std::size_t CharSize>
void put( underlying_outbuf<CharSize>& ob
        , underlying_char_type<CharSize> ch );
----
[horizontal]
Effect:: Same as:
+
[source,cpp]
----
if (ob.size() == 0) {
    ob.recycle();
}
*ob.pos() = ch;
ob.advance();
----
====

[[underlying_outbuf_write]]
[[underlying_outbuf_write_range]]
====
[source,cpp]
----
template <std::size_t CharSize>
void write( underlying_outbuf<CharSize>& ob
          , const underlying_char_type<CharSize>* data
          , const underlying_char_type<CharSize>* data_end );
----
[horizontal]
Effect:: Writes the the range [ `data`, `data_end` ) into `ob`, calling `ob.recycle()`
         how many times are necessary.
====
[[underlying_outbuf_write_count]]
====
[source,cpp]
----
template <std::size_t CharSize>
void write( underlying_outbuf<CharSize>& ob
          , const underlying_char_type<CharSize>* data
          , std::size_t data_size );
----
[horizontal]
Effect:: Same as `write(ob, data, data + data_size)`
====

[[basic_outbuf]]
=== Class template `basic_outbuf`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class basic_outbuf: private {underlying_outbuf}<sizeof(CharT)>
{
public:
    using char_type = CharT;
    basic_outbuf(const basic_outbuf&) = delete;
    basic_outbuf(basic_outbuf&&) = delete;
    basic_outbuf& operator=(const basic_outbuf&) = delete;
    basic_outbuf& operator=(basic_outbuf&&) = delete;

    virtual ~basic_outbuf() = default;

    {underlying_outbuf}<sizeof(CharT)>& as_underlying() noexcept;
    const {underlying_outbuf}<sizeof(CharT)>& as_underlying() const noexcept;

    char_type* pos() const noexcept;
    char_type* end() const noexcept;
    void advance_to(char_type* p);

    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_size,size>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_advance,advance>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_good,good>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_require,require>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_recycle,recycle>>

protected:

    basic_outbuf(char_type* pos_, char_type* end_);
    basic_outbuf(char_type* pos_, std::size_t n);

    void set_pos(char_type* p) noexcept;
    void set_end(char_type* e) noexcept;

    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_set_good,set_good>>;
};

// global type aliases

using outbuf      = basic_outbuf<char>;
using u8outbuf    = basic_outbuf<char8_t>;
using u16outbuf   = basic_outbuf<char16_t>;
using u32outbuf   = basic_outbuf<char32_t>;
using woutbuf     = basic_outbuf<wchar_t>;
using bin_outbuf  = basic_outbuf<std::byte>;

// global functions

template <typename CharT>
void write( basic_outbuf<CharT>& ob
          , const CharT* data
          , std::size_t count );

template <typename CharT>
void write( basic_outbuf<CharT>& ob
          , const CharT* data
          , const CharT* data_end );

void write(basic_outbuf<char>& ob, const char* cstr);

void write(basic_outbuf<wchar_t>& ob, const wchar_t* cstr);

template <typename CharT>
void put(basic_outbuf<CharT>& ob, CharT ch);

} // namespace strf
----

==== Public member functions

[[basic_outbuf_as_underlying]]
====
[source,cpp,subs=normal]
----
underlying_outbuf<sizeof(CharT)>& as_underlying() noexcept;
const underlying_outbuf<sizeof(CharT)>& as_underlying() const noexcept;
----
[horizontal]
Return:: `*this`
====
[[basic_outbuf_pos]]
====
[source,cpp]
----
char_type* pos() const noexcept;
----
[horizontal]
Return:: `(CharT*) as_underlying().pos();`
====
[[basic_outbuf_end]]
====
[source,cpp]
----
char_type* end() const noexcept;
----
[horizontal]
Return:: `(CharT*) as_underlying().end();`
====
[[basic_outbuf_advance_to]]
====
[source,cpp]
----
void advance_to(char_type* p);
----
[horizontal]
Effect:: Same as
+
[source,cpp]
----
as_underlying().advance_to((underlying_char_type<sizeof(CharT)>*)p)
----
Precondition:: `p \<= end()`
====

==== Public member functions inherited from private base `underlying_outbuf<sizeof(CharT)>`

[source,cpp,subs=normal]
----
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_size,size>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_advance,advance>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_good,good>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_require,require>>
    using {underlying_outbuf}<sizeof(CharT)>::<<underlying_outbuf_recycle,recycle>>
----

==== Protected member functions

[[basic_outbuf_ctor_range]]
====
[source,cpp]
----
basic_outbuf(char_type* pos_, char_type* end_);
----
[horizontal]
Effect:: Initializes private base class `underlying_outbuf<sizeof(CharT)>`
with `pos_` and `end_` casted as `underlying_char_type<sizeof(CharT)>*`.
====
[[basic_outbuf_ctor_count]]
====
[source,cpp]
----
basic_outbuf(char_type* pos_, std::size_t n);
----
[horizontal]
Effect:: Same as `basic_outbuf(pos_, pos + n)`
====
[[basic_outbuf_]]
====
[source,cpp]
----
void set_pos(char_type* p) noexcept;
----
[horizontal]
Effect:: Same as
+
[source, cpp]
----
as_underlying().set_pos((underlying_char_type<sizeof(CharT)>*)p)
----
====
[[basic_outbuf_]]
====
[source,cpp]
----
void set_end(char_type* e) noexcept;
----
[horizontal]
Effect:: Same as
+
[source, cpp]
----
as_underlying().set_end((underlying_char_type<sizeof(CharT)>*)e)
----
====
[[basic_outbuf_set_good]]
====
[source,cpp]
----
void set_good(bool g) noexcept;
----
[horizontal]
Effect:: Same as `as_underlying().set_good(g)`
====

==== Global functions

[[basic_outbuf_put]]
====
[source,cpp]
----
template <typename CharT>
void put(basic_outbuf<CharT>& ob, CharT ch);
----
[horizontal]
Effect:: Same as:
+
[source,cpp]
----
if (ob.size() == 0) {
    ob.recycle();
}
*ob.pos() = ch;
ob.advance();
----
====
[[basic_outbuf_write]]
[[basic_outbuf_write_range]]
====
[source,cpp]
----
template <typename CharT>
void write( basic_outbuf<CharT>& ob
          , const CharT* data
          , const CharT* data_end );
----
[horizontal]
Effect:: Writes the the range [ `data`, `data_end` ) into `ob`, calling `ob.recycle()`
         how many times are necessary.
====
[[basic_outbuf_write_count]]
====
[source,cpp]
----
template <typename CharT>
void write( basic_outbuf<CharT>& ob
          , const CharT* data
          , std::size_t data_size );
----
[horizontal]
Effect:: Same as `write(ob, data, data + data_size)`
====
[[basic_outbuf_write_cstr]]
====
[source,cpp]
----
void write( basic_outbuf<char>& ob
          , const char* cstr );
----
[horizontal]
Effect:: Same as `write(ob, cstr, std::strlen(cstr))`
====
[[basic_outbuf_write_wcstr]]
====
[source,cpp]
----
void write( basic_outbuf<wchar_t>& ob
          , const wchar_t* wcstr );
----
[horizontal]
[horizontal]
Effect:: Same as `write(ob, wcstr, std::wstrlen(wcstr))`
====
[[basic_outbuf_noexcept]]
=== Class template `basic_outbuf_noexcept`

[source,cpp]
----
namespace strf {

template <typename CharT>
class basic_outbuf_noexcept: public basic_outbuf<CharT>
{
public:

    virtual void recycle() noexcept = 0;

protected:

    using basic_outbuf<CharT>::basic_outbuf;
};

// type aliases

using outbuf_noexcept      = basic_outbuf_noexcept<char>;
using u8outbuf_noexcept    = basic_outbuf_noexcept<char8_t>;
using u16outbuf_noexcept   = basic_outbuf_noexcept<char16_t>;
using u32outbuf_noexcept   = basic_outbuf_noexcept<char32_t>;
using woutbuf_noexcept     = basic_outbuf_noexcept<wchar_t>;
using bin_outbuf_noexcept  = basic_outbuf_noexcept<std::byte>;

} // namespace strf
----

[[basic_cstr_writer]]
=== Class template `basic_cstr_writer`

[source,cpp]
----
namespace strf {

template <typename CharT>
class basic_cstr_writer final: public basic_outbuf_noexcept<CharT>
{
public:

    basic_cstr_writer(CharT* dest, CharT* dest_end);
    basic_cstr_writer(CharT* dest, std::size_t len);
    template <std::size_t N>
    basic_cstr_writer(CharT (&dest)[N]);

    void recycle() noexcept override;
    struct result
    {
        CharT* ptr;
        bool truncated;
    };
    result finish();
};

} // namespace strf
----

==== Public member function

====
[source,cpp]
----
basic_cstr_writer(CharT* dest, CharT* dest_end);
----
[horizontal]
Precondition:: `dest < dest_end`
Postconditions::
- `good() == true`
- `pos() == dest`
- `end() == dest_end - 1`
====
====
[source,cpp]
----
basic_cstr_writer(CharT* dest, std::size_t dest_size);
----
[horizontal]
Precondition:: `dest_size != 0`
Postconditions::
- `good() == true`
- `pos() == dest`
- `end() == dest + dest_size - 1`
====
====
[source,cpp]
----
template <std::size_t N>
basic_cstr_writer(CharT (&dest)[N]);
----
[horizontal]
Postconditions::
- `good() == true`
- `pos() == dest`
- `end() == dest + N - 1`
====
====
[source,cpp]
----
void recycle() noexcept;
----
[horizontal]
Postconditions::
- `good() == false`
- `pos() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Assign to `'\0'` the position after the last written character in memory area used to initialize this object and set this object into "bad" state.
Return value::
- `result::truncated` is `true` if `recycle` or `finish` has ever been called in this object.
- `retulr::ptr` is the position after the last written character in memory area used to initialize this object
Postconditions::
- `good() == false`
- `pos() == {garbage_buf}<CharT>()`
- `end() == {garbage_buf_end}<CharT>()`
====

[[basic_string_maker]]
=== Class template `basic_string_maker`
==== Synopsis
[source,cpp]
----
namespace strf {

template < typename CharT
         , typename Traits = std::char_traits<CharT>
         , typename Allocator = std::allocator<CharT> >
class basic_string_maker final: public basic_outbuf<CharT>
{
public:
    basic_string_maker();
    void reserve(std::size_t size);
    void recycle() override;
    basic_string<CharT, Traits, Allocator> finish();
};

// Global type aliases

using string_maker    = basic_string_maker<char>;
using u16string_maker = basic_string_maker<char16_t>;
using u32string_maker = basic_string_maker<char32_t>;
using wstring_maker   = basic_string_maker<wchar_t>;
using u8string_maker  = basic_string_maker<char8_t>;

} // namespace strf
----
==== Public member functions

====
[source,cpp]
----
void reserve(std::size_t size);
----
[horizontal]
Effect:: Calls `str.reserve(size)`, where `str` is the private string object that is returned by `finish()`.
====
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good()` is `true` then calls `str.append(p0, pos())`, where `str` is the private string object that is returned by `finish()`, and `p0` is the return value of `pos()` before any call to `advance` and `advance_to` since the last call to `recycle()` ( all in this object ), or since this object's contruction, whatever happened last.
- Calls `set_pos` and/or `set_end`.
Postconditions:: `size() >= min_size_after_recycle<sizeof(CharT)>()`
====
====
[source,cpp]
----
basic_string<CharT, Traits, Allocator> finish()
----
[horizontal]
Effects:: Calls `recycle()` and `set_good(false)` and return the internal string.
Postconditions:: `good() == false`
====

[[basic_string_appender]]
=== Class template `basic_string_appender`
==== Synopsis
[source,cpp]
----
namespace strf {

template < typename CharT
         , typename Traits = std::char_traits<CharT>
         , typename Allocator = std::allocator<CharT> >
class basic_string_appender final: public basic_outbuf<CharT>
{
public:
    explicit basic_string_appender(basic_string<CharT, Traits, Allocator>& dest);
    void reserve(std::size_t size);
    void recycle() override;
    void finish();
};

// Global type aliases

using string_appender    = basic_string_appender<char>;
using u16string_appender = basic_string_appender<char16_t>;
using u32string_appender = basic_string_appender<char32_t>;
using wstring_appender   = basic_string_appender<wchar_t>;

} // namespace strf
----
==== Public member functions

====
[source,cpp]
----
void reserve(std::size_t size);
----
[horizontal]
Effect:: Calls `str.reserve(str.size() + size)`, where `str` is the reference that this object was initialized with.
====
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good()` is `true` then calls `str.append(p0, pos())`, where `str` is the reference that this object was initialized with, and `p0` is the return value of `pos()` before any call to `advance` and `advance_to` since the last call to `recycle()` ( all in this object ), or since this object's contruction, whatever happened last.
- Calls `set_pos` and/or `set_end`.
Postconditions:: `size() >= min_size_after_recycle<sizeof(CharT)>()`
====
====
[source,cpp]
----
void finish()
----
[horizontal]
Effects:: Calls `recycle()` and `set_good(false)`.
Postcondition:: `good() == false`
====

[[basic_streambuf_writer]]
=== Class template `basic_streambuf_writer`
==== Synopsis
[source,cpp]
----
namespace strf {

template <typename CharT, typename Traits = std::char_traits<CharT> >
class basic_streambuf_writer final: public basic_outbuf<CharT>
{
public:
    explicit basic_streambuf_writer(std::basic_streambuf<CharT, Traits>& dest);
    void recycle() override;
    struct result
    {
        std::streamsize count;
        bool success;
    };
    result finish();
};

// Global type aliases

using streambuf_writer
    = basic_streambuf_writer<char, std::char_traits<char> >;

using wstreambuf_writer
    = basic_streambuf_writer<wchar_t, std::char_traits<wchar_t> >;

} // namespace strf
----
==== Public member functions

====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good()` is `true` then calls `dest.sputn(p0, pos() - p0)`, where `dest` is the reference this object was initialized with, and `p0` is the return value of `pos()` before any call to `advance` and `advance_to` since the last call to `recycle()`, or since this object's contruction, whatever happened last.
- If the returned value of `dest.sputn` is less then `pos() - p0`, calls `set_good(false)`.
- Calls `set_pos` and/or `set_end`.
Postconditions:: `size() >= min_size_after_recycle<sizeof(CharT)>()`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the sum of the values returned by `dest.sputn`.
- `result::success` is the value `good()` would return before this call to `finish()`.
====

[[narrow_cfile_writer]]
=== Class template `narrow_cfile_writer`
==== Synopsis
[source,cpp]
----
namespace strf {

template <typename CharT>
class narrow_cfile_writer final: public basic_outbuf_noexcept<CharT>
{
public:
    explicit narrow_cfile_writer(std::FILE* dest);
    void recycle() noexcept;
    struct result
    {
        std::size_t count;
        bool success;
    };
    result finish();
};

} // namespace strf
----
==== Public member functions
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good() == true`, calls `std::fwrite(p0, pos() - p0, sizeof(CharT), dest)`,
    where `dest` is the `FILE*` used to initialize this object, and
    `p0` is return value of `pos()` before any call to `advance` and `advance_to`
    since the last call to `recycle()`, or since this object's contruction,
    whatever happened last.
-  If the returned value of std::fwrite is less then pos() - p0, calls set_good(false).
-  Calls set_pos and/or set_end.
Postconditions:: `size() >= min_size_after_recycle<sizeof(CharT)>()`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the sum of values returned by all calls `std::fwrite` done by this object.
- `result::success` is the value `good()` would return before this call to `finish()`
====


[[wide_cfile_writer]]
=== Class template `wide_cfile_writer`
==== Synopsis
[source,cpp]
----
namespace strf {

template <typename CharT>
class wide_cfile_writer final: public basic_outbuf_noexcept<CharT>
{
public:
    explicit wide_cfile_writer(std::FILE* dest);
    void recycle() noexcept;
    struct result
    {
        std::size_t count;
        bool success;
    };
    result finish();
};

} // namespace strf
----
==== Public member functions
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good() == true`, for each character `ch` in the range [ `p0`, `pos()` ) calls `std::fputwc(ch, dest)`, until WEOF is returned or the whole range is read, where `dest` is the `FILE*` used to initialize this object, and `p0` is the return value of `pos()` before any call to `advance` and `advance_to` since the last call to `recycle()`, or since this object's contruction, whatever happened last.
- If `std::fputwc` returns WEOF, calls `set_good(false)`.
- Calls `set_pos` and/or `set_end`.
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the number of calls to `std::fputwc` by this object that did not return WEOF .
- `result::success` is the value `good()` would return before this call to `finish()`
====

[[garbage_buf]]
=== Garbage buffer
These function templates return the begin and the end of a memory area that is never supposed to be read. It can be used when implementing a class that derives from `basic_outbuf` to set the buffer when the state is "bad".

[source,cpp]
----
template <typename CharT>
CharT* garbage_buf();
----

[source,cpp]
----
template <typename CharT>
CharT* garbage_buf_end();
----


