////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

:WidthCalculator: <<WidthCalculator,WidthCalculator>>
:width_calculator_c: <<width_calculator_c,width_calculator_c>>
:width_and_pos: <<width_and_pos,width_and_pos>>
:fast_width: <<fast_width,fast_width>>
:width_as_u32len: <<width_as_u32len,width_as_u32len>>
:width_as_fast_u32len: <<width_as_fast_u32len,width_as_fast_u32len>>
:width_by_func: <<width_by_func,width_by_func>>
:make_width_calculator: <<make_width_calculator,make_width_calculator>>
:width_t: <<width_t,width_t>>

== Width Calculation

=== Facet category `width_calculator_c` [[width_calculator_c]]

[source,cpp,subs=normal]
----
namespace strf {

struct width_calculator_c
{
    static constexpr bool constrainable = true;

    static constexpr {fast_width} get_default() noexcept;
};

} // namespace strf
----

For a type to be a facet of the `width_calculator_c` category, it has to
satisfy the __{WidthCalculator}__ requirements.

==== Type requirement _WidthCalculator_ [[WidthCalculator]]

Given

* `CharSize`, an constexpr integer value equal to `1`, `2` or `4`
* `Charset`, an __{UnderlyingCharset}__ type for value `CharSize`
* `charset`, an lvalue reference of type `Charset`
* `ch` a value of type `{underlying_char_type}<CharSize>`
* `limit`, a value of type `{width_t}`
* `str`, a value of type `const {underlying_char_type}<CharSize>*`
        pointing to string encoded according to `charset`.
* `str_len`, a value of type `std::size_t` equal to the length of string `str`.
* `surr_poli`, a value of type `{surrogate_policy}`

For a type `X` to be _WidthCalculator_, given an object `x` of type `X`,
the following syntax and requirements have to be satisfied:
====
[source,cpp]
----
X::category
----
A type alias to `{width_calculator_c}`.
====
====
[source,cpp]
----
x.char_width(charset, ch)
----
[horizontal]
Return type:: `{width_t}`
Return value:: The width of `ch` when encoded according to `charset`.
====
====
[source,cpp,subs=normal]
----
x.str_width(charset, limit, str, str_len, surr_poli)
----
[horizontal]
Return type::: `{width_t}`
Return value::: The width of the string `str` if it is less than `limit`.
               Otherwise, it can be any value that is greater than or
               equal to `limit`.
====
====
[source,cpp]
----
x.str_width_and_pos(charset, limit, str, str_len, surr_poli)
----
[horizontal]
Effect::: Calculates the width of `str`. If such value is less than
         `limit`, then calculates the size of the substring of `str`
         whose width is equal to `limit`.
Return type::: `{width_and_pos}`
Return value::: A value `ret` of type `{width_and_pos}`, such that
* `ret.pos` is the greatest value that is less than or equal to `str_len`
  such that `x.width(charset, width_max, str, ret.pos, surr_poli).width`
  is less than or equal to `limit`.
* `ret.width` is the width of the substring of `str` with size `ret.pos`
  that starts at the same position of `str`.
====

NOTE: The library provides three classes and one class template that
      satisfy _WidthCalculator: `{fast_width}`, `{width_as_fast_u32len}`,
      `{width_as_u32len}` and `{width_by_func}.

////
What "width" of a string means is up to each _WidthCalculator_ type.
It doesn't have to be accurate, after all that would require to
      consider the font in which the string is displayed, which is
      usually impractical.
      However it is expected the width to be a
      https://en.wikipedia.org/wiki/Monotonic_function[monotonically
      increasing function] in relation to be size
////
==== Struct `width_and_pos` [[width_and_pos]]

[source,cpp,subs=normal]
----
struct width_and_pos {
    {width_t} width;
    std::size_t pos;
};
----

=== Class `fast_width` [[fast_width]]

Class `fast_width` is a facet of the category `{width_calculator_c}`
that evaluates the width of a string as its size.

[source,cpp,subs=normal]
----
class fast_width final
{
public:
    using category = {width_calculator_c};

    template <typename Charset>
    {width_t} <<fast_width_char_width,char_width>>
        ( const Charset&
        , {underlying_char_type}<Charset::char_size> ) const noexcept;

    template <typename Charset>
    {width_t} <<fast_width_str_width,str_width>>
        ( const Charset&
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>*
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;

    template <typename Charset>
    constexpr {width_and_pos} <<fast_width_str_width_and_pos,str_width_and_pos>>
        ( const Charset&
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>*
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;
};
----
[[fast_width_char_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
{width_t} char_width
    ( const Charset&
    , {underlying_char_type}<Charset::char_size> ) const noexcept;
----
[horizontal]
Return value:: `1`
====
[[fast_width_str_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_t} str_width
    ( const Charset&
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>*
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value:::
* `str_len`, if `str_len` is less than or equal to `limit.floor()`
*  otherwise, `limit`
====
[[fast_width_str_width_and_pos]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_and_pos} str_width_and_pos
    ( const Charset&
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>*
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value::: The return value `ret` is such that

* if `limit \<= 0` is `true`, then `ret.width` and `ret.pos` are `0`;
* otherwise, if `limit.floor()` is less than `str_len`, then
`ret.width` and `ret.pos` are equal to `limit.floor()`;
* otherwise, `ret.width` and `ret.pos` are equal to `str_len`.
====


=== Class `width_as_fast_u32len` [[width_as_fast_u32len]]

Class `width_as_fast_u32len` is a facet of the category `{width_calculator_c}`.
It evaluates the width of a string as the number of Unicode code points.
However, to gain performance and differently from `{width_as_u32len}`,
it assumes that the measured string is totally conformant to its charset.

[source,cpp,subs=normal]
----
class width_as_fast_u32len final
{
public:
    using category = {width_calculator_c};

    template <typename Charset>
    {width_t} <<width_as_fast_u32len_char_width,char_width>>
        ( const Charset& charset
        , {underlying_char_type}<Charset::char_size> ) const noexcept;

    template <typename Charset>
    {width_t} <<width_as_fast_u32len_str_width,str_width>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;

    template <typename Charset>
    constexpr {width_and_pos} <<width_as_fast_u32len_str_width_and_pos,str_width_and_pos>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;
};
----
[[width_as_fast_u32len_char_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
{width_t} char_width
    ( const Charset&
    , {underlying_char_type}<Charset::char_size> ) const noexcept;
----
[horizontal]
Return value::: `1`
====
[[width_as_fast_u32len_str_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_t} str_width
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value:::
* `0`, if `limit \<= 0` is `true`
* otherwise, `charset.<<UnderlyingCharset_codepoints_fast_count,codepoints_fast_count>>(str, str_len, limit.floor()).count`.
====
[[width_as_fast_u32len_str_width_and_pos]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_and_pos} str_width_and_pos
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value::: The return value `ret` is such that

* If `limit \<= 0` is `true`, then then `ret.width` and `ret.pos` are `0`;
* otherwise, `ret.width` is equal to `ret2.count` and `ret.pos` is equal
  to `charset.<<UnderlyingCharset_codepoints_fast_count,codepoints_fast_count>>(str, str_len, lim).pos`
====

=== Class `width_as_u32len` [[width_as_u32len]]

Class `width_as_fast_u32len` is a facet of the category `{width_calculator_c}`.
It evaluates the width of a string as the number of Unicode code points,
assuming that any non-conformity to the corresponding charset is replaced
by one codepoint ( following the semantics of `{invalid_seq_policy}::replace` ).

[source,cpp,subs=normal]
----
class width_as_u32len final
{
public:
    using category = {width_calculator_c};

    template <typename Charset>
    {width_t} <<width_as_u32len_char_width,char_width>>
        ( const Charset& charset
        , {underlying_char_type}<Charset::char_size> ) const noexcept;

    template <typename Charset>
    {width_t} <<width_as_u32len_str_width,str_width>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;

    template <typename Charset>
    constexpr {width_and_pos} <<width_as_u32len_str_width_and_pos,str_width_and_pos>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const noexcept;
};
----
[[width_as_u32len_char_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
{width_t} char_width
    ( const Charset&
    , {underlying_char_type}<Charset::char_size> ) const noexcept;
----
[horizontal]
Return value:: `1`
====
[[width_as_u32len_str_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_t} str_width
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value:::
* `0`, if `limit \<= 0` is `true`
* otherwise, `charset.<<UnderlyingCharset_codepoints_robust_count,codepoints_robust_count>>(str, str_len, limit.floor()).count`.
====
[[width_as_u32len_str_width_and_pos]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_and_pos} str_width_and_pos
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy} ) const noexcept;
----
[horizontal]
Return value::: The return value `ret` is such that

* If `limit \<= 0` is `true`, then then `ret.width` and `ret.pos` are `0`;
* otherwise, `ret.width` is equal to `ret2.count` and `ret.pos` is equal to
  `charset.<<UnderlyingCharset_codepoints_robust_count,codepoints_robust_count>>(str, str_len, lim).pos`
====

=== Class template `width_by_func` [[width_by_func]]

The instances of the `width_by_func` class template are facets
of the category `{width_calculator_c}`.
It calculates the width of a string by converting it to UTF-32,
following the policy associated to `{invalid_seq_policy}::replace`,
and then calling the provided function to evaluate the width
of each UTF-32 character.

[source,cpp,subs=normal]
----
template <typename CharWidthFunc>
class width_by_func{
public:
    using category = {width_calculator_c};

    template <typename Charset>
    {width_t} <<width_by_func_char_width,char_width>>
        ( const Charset& charste
        , {underlying_char_type}<Charset::char_size> ) const;

    template <typename Charset>
    {width_t} <<width_by_func_str_width,str_width>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const;

    template <typename Charset>
    constexpr {width_and_pos} <<width_by_func_str_width_and_pos,str_width_and_pos>>
        ( const Charset& charset
        , {width_t} limit
        , const {underlying_char_type}<Charset::char_size>* str
        , std::size_t str_len
        , {surrogate_policy} ) const;

private:

    const CharWidthFunc func_; // exposition only
};
----

==== Compile-time requirements
====
Given

* `ch`, a value of type `char32_t`
* `func`, a object of type `CharWidthFunc` or `const CharWidthFunc`

The expression `func(ch)` must be well formed and the return type
must be {width_t}.
====

==== Member functions
[[width_by_func_char_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
{width_t} char_width
    ( const Charset& charset
    , {underlying_char_type}<Charset::char_size> ch) const;
----
[horizontal]
Return value:: `func_(charset.<<Charset_decode_char,decode_char>>(ch))`
====
[[width_by_func_str_width]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_t} str_width
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy}  surr_poli) const;
----
[horizontal]
Return value::: The sum of the values of `func_(ch32)`, where `ch32` is
   each of the `char32_t` values that are written into `ob` --
   an object whose type derives from `{underlying_outbuf}<4>` -- by the call
+
[source,cpp,subs=normal]
----
charset.<<UnderlyingCharset_to_u32,to_u32>>().<<UnderlyingTranscoder_transcode,transcode>>
    ( ob, str, str_len, {invalid_seq_policy}::replace, surr_poli )
----
, if such value is less than or equal to `limit`. Otherwise, the return value
  can be anyone that is greater than or equal to `limit`.
====
[[width_by_func_str_width_and_pos]]
====
[source,cpp,subs=normal]
----
template <typename Charset>
constexpr {width_and_pos} str_width_and_pos
    ( const Charset& charset
    , {width_t} limit
    , const {underlying_char_type}<Charset::char_size>* str
    , std::size_t str_len
    , {surrogate_policy} surr_poli) const;
----
[horizontal]
Return value::: The return value `ret` is such that:
* `ret.width` is the sum of the values of `func_(ch32)`, where `ch32` is
   each of the `char32_t` values that are written into `ob` by the call
+
[source,cpp,subs=normal]
----
charset.<<UnderlyingCharset_to_u32,to_u32>>().<<UnderlyingTranscoder_transcode,transcode>>
    ( ob, str, ret.pos, {invalid_seq_policy}::replace, surr_poli )
----
, where `ob` is any object whose type derives from `{underlying_outbuf}<4>`.
* `ret.pos` is the greatest value that is less than or equal to `str_len`
  such that `str_width_and_pos(charset, limit, str, ret.pos, surr_poli).width`
  is less than or equal to `limit`.
====

=== Function template `make_width_calculator` [[make_width_calculator]]
[source,cpp,subs=normal]
----
template <typename CharWidthFunc>
{width_by_func}<CharWidthFunc> make_width_calculator(CharWidthFunc f);
----
[horizontal]
Return value::: `{width_by_func}<CharWidthFunc>{f}`

=== Class `width_t` [[width_t]]

The `width_t` class implements signed
https://en.wikipedia.org/wiki/Q_(number_format)[Q16.16] arithmetics and
is used to represent width of textual content when
<<alignment_format,text alignment formatting>> is used.
The value of `width_t(1)` corresponds to an https://en.wikipedia.org/wiki/En_(typography)[en].

[source,cpp,subs=normal]
----
namespace strf {

class width_t {
public:
    struct from_underlying_tag{};
    constexpr width_t() noexcept;
    constexpr width_t(std::int16_t) noexcept;
    constexpr width_t(const width_t&) noexcept;
    constexpr width_t(from_underlying_tag, std::int32_t) noexcept;

    constexpr width_t& operator=(const width_t& other) noexcept;
    constexpr width_t& operator=(std::int16_t& x) noexcept;

    constexpr bool operator==(const width_t& other) const noexcept;
    constexpr bool operator!=(const width_t& other) const noexcept;
    constexpr bool operator<(const width_t& other) const noexcept;
    constexpr bool operator>(const width_t& other) const noexcept;
    constexpr bool operator\<=(const width_t& other) const noexcept;
    constexpr bool operator>=(const width_t& other) const noexcept;

    constexpr bool is_integral() const noexcept;
    constexpr std::int16_t floor() const noexcept;
    constexpr std::int16_t ceil() const noexcept;
    constexpr std::int16_t round() const noexcept;

    constexpr width_t operator-() const noexcept;
    constexpr width_t operator+() const noexcept;
    constexpr width_t& operator+=(width_t other) noexcept;
    constexpr width_t& operator-=(width_t other) noexcept;
    constexpr width_t& operator{asterisk}=(std::int16_t m) noexcept;
    constexpr width_t& operator/=(std::int16_t d) noexcept;
    constexpr width_t& operator{asterisk}=(width_t other) noexcept;
    constexpr width_t& operator/=(width_t other) noexcept;

    constexpr std::int32_t underlying_value() const noexcept;
    constexpr static width_t from_underlying(std::int32_t) noexcept;

private:
    std::int32_t _underlying_value; // exposition only
};

constexpr width_t width_max = width_t::from_underlying(INT32_MAX);
constexpr width_t width_min = width_t::from_underlying(INT32_MIN);

constexpr bool operator==(width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator==(std::int16_t lhs, width_t rhs) noexcept;
constexpr bool operator!=(width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator!=(std::int16_t lhs, width_t rhs) noexcept;
constexpr bool operator< (width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator< (std::int16_t lhs, width_t rhs) noexcept;
constexpr bool operator\<=(width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator\<=(std::int16_t lhs, width_t rhs) noexcept;
constexpr bool operator> (width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator> (std::int16_t lhs, width_t rhs) noexcept;
constexpr bool operator>=(width_t lhs, std::int16_t rhs) noexcept;
constexpr bool operator>=(std::int16_t lhs, width_t rhs) noexcept;

constexpr width_t operator+(width_t lhs, width_t rhs) noexcept;
constexpr width_t operator+(std::int16_t lhs, width_t rhs) noexcept;
constexpr width_t operator+(width_t lhs, std::int16_t rhs) noexcept;
constexpr width_t operator-(width_t lhs, width_t rhs) noexcept;
constexpr width_t operator-(std::int16_t lhs, width_t rhs) noexcept;
constexpr width_t operator-(width_t lhs, std::int16_t rhs) noexcept;
constexpr width_t operator*(width_t lhs, width_t rhs) noexcept;
constexpr width_t operator*(std::int16_t lhs, width_t rhs) noexcept;
constexpr width_t operator*(width_t lhs, std::int16_t rhs) noexcept;
constexpr width_t operator/(width_t lhs, width_t rhs) noexcept;
constexpr width_t operator/(std::int16_t lhs, width_t rhs) noexcept;
constexpr width_t operator/(width_t lhs, std::int16_t rhs) noexcept;

constexpr width_t checked_add(width_t lhs, width_t rhs) noexcept;
constexpr width_t checked_subtract(width_t lhs, std::int64_t rhs) noexcept;
constexpr width_t checked_subtract(width_t lhs, width_t rhs) noexcept;
constexpr width_t checked_mul(width_t lhs, std::uint32_t rhs) noexcept;

} // namespace strf
----

__to-do__

=== `width_t` literal `_w` [[width_literal]]

[source,cpp,subs=normal]
----
namespace strf {
namespace width_literal {

template <char\...C>
constexpr {width_t} operator "" _w()

} // namespace width_literal
} // namespace strf
----
The suffix `_w` can be aplied in floating-points literals in fixed notations as well
as integer literals.

.Example
[source,cpp,subs=normal]
----
using namespace strf::width_literal;

strf::width_t x = 1.5_w;
x += 0.25_w;
x += 1_w;
assert(x == 2.75_w);
----

