////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

:rank: <<rank,rank>>
:tag: <<tag,tag>>
:destination_no_reserve: <<destination,destination_no_reserve>>
:OutbuffCreator: <<OutbuffCreator,OutbuffCreator>

:basic_cstr_writer: <<outbuff_hpp#basic_cstr_writer,basic_cstr_writer>>
:destination_no_reserve: <<destination,destination_no_reserve>>
:OutbuffCreator: <<OutbuffCreator,OutbuffCreator>>
:SizedOutbuffCreator: <<SizedOutbuffCreator,SizedOutbuffCreator>>


== Miscellaneous

=== The `lettercase` facet

[source,cpp]
----
namespace strf {

enum class lettercase { lower = /*...*/, mixed = /*...*/, upper = /*...*/ };

constexpr lettercase lowercase = lettercase::lower;
constexpr lettercase mixedcase = lettercase::mixed;
constexpr lettercase uppercase = lettercase::upper;

struct lettercase_c {
    static constexpr bool constrainable = true;
    constexpr static lettercase get_default() noexcept
    {
        return lettercase::lower;
    }
};

template <>
struct {facet_traits}<lettercase> {
    using category = lettercase_c;
};

} // namespace strf
----
=== Type traits
The table below list class templates that satisfy
https://en.cppreference.com/w/cpp/named_req/UnaryTypeTrait[UnaryTypeTrait].
They are created to be used in the `constrain` function template to filter
printable types.

[cols="1,4"]
|===
|`is_int_number`
| matches `short`, `int`, `long`, `long long` and the corresponding unsigned types

|`is_char`
| matches `char`, `char8_t`, `wchar_t`, `char16_t`, and `char32_t`

|`is_string`
| matches strings.
|===

__to-do__

=== Class template `tag` [[tag]]

[source,cpp,subs=normal]
----
namespace strf {

template <typename\... >
struct tag
{
    explicit tag() = default;
};

template <typename T>
struct tag<T>
{
    explicit constexpr STRF_HD tag() noexcept { }
    using type = T;
};

} // namespace strf
----

////
=== Class template `rank` [[rank]]

[source,cpp,subs=normal]
----
namespace strf {

template <std::size_t N>
struct rank: rank<N - 1>
{
    explicit rank() = default;
};

template <>
struct rank<0>
{
    explicit rank() = default;
};

} // namespace strf
----
////

=== `Outbuff` writing functions

[source,cpp,subs=normal]
----
namespace strf {

template <std::size_t CharSize>
void write( {underlying_outbuff}<CharSize>& ob
          , const {underlying_char_type}<CharSize>{asterisk} data
          , std::size_t data_size );

template <std::size_t CharSize>
void write( {underlying_outbuff}<CharSize>& ob
          , const {underlying_char_type}<CharSize>{asterisk} data
          , const {underlying_char_type}<CharSize>{asterisk} data_end );

template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , std::size_t count );

template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , const CharT{asterisk} data_end );

void write({basic_outbuff}<char>& ob, const char{asterisk} cstr);

void write({basic_outbuff}<wchar_t>& ob, const wchar_t{asterisk} cstr);

} // namespace strf
----

[[underlying_outbuff_write]]
[[underlying_outbuff_write_range]]
====
[source,cpp,subs=normal]
----
template <std::size_t CharSize>
void write( {underlying_outbuff}<CharSize>& ob
          , const {underlying_char_type}<CharSize>{asterisk} data
          , const {underlying_char_type}<CharSize>{asterisk} data_end );
----
[horizontal]
Effect:: Writes the the range [ `data`, `data_end` ) into `ob`, calling `ob.recycle()`
         how many times are necessary.
====

[[underlying_outbuff_write_count]]
====
[source,cpp,subs=normal]
----
template <std::size_t CharSize>
void write( {underlying_outbuff}<CharSize>& ob
          , const {underlying_char_type}<CharSize>{asterisk} data
          , std::size_t data_size );
----
[horizontal]
Effect:: Same as `write(ob, data, data + data_size)`
====

[[basic_outbuff_write]]
[[basic_outbuff_write_range]]
====
[source,cpp]
----
template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT* data
          , const CharT* data_end );
----
[horizontal]
Effect:: Writes the the range [ `data`, `data_end` ) into `ob`, calling `ob.recycle()`
         how many times are necessary.
====
[[basic_outbuff_write_count]]
====
[source,cpp]
----
template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT* data
          , std::size_t data_size );
----
[horizontal]
Effect:: Same as `write(ob, data, data + data_size)`
====
[[basic_outbuff_write_cstr]]
====
[source,cpp]
----
void write( {basic_outbuff}<char>& ob
          , const char* cstr );
----
[horizontal]
Effect:: Same as `write(ob, cstr, std::strlen(cstr))`
====

[[basic_outbuff_write_wcstr]]
====
[source,cpp,subs=normal]
----
void write( {basic_outbuff}<wchar_t>& ob
          , const wchar_t{asterisk} wcstr );
----
[horizontal]
Effect:: Same as `write(ob, wcstr, std::wstrlen(wcstr))`
====

=== Destination markers

[[to_char_ptr_count]]
====
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  dest, std::size_t count);

} // namespace strf
----

[horizontal]
Return type:: `{destination_no_reserve}<OBC>`, where `OBC` is an implementation-defined
              type that satifies __{OutbuffCreator}__.
Return value:: A destination object whose internal __{OutbuffCreator}__ object `obc`
is such that `obc.create()` returns a `{basic_cstr_writer}<CharT>` object initialized
with `dest` and `count`, where, `CharT` is `std::remove_reference_t<decltype(*dest)>`.
====
====
[[to_char_array]]
[source,cpp,subs=normal]
----
namespace strf {

template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char8_t  (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char     (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char16_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char32_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(wchar_t  (&dest)[N]);

} // namespace strf
----
[horizontal]
Return type and value:: Same as `to(dest, N)`;
====
====
[[to_char_range]]
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  dest,  char8_t{asterisk}  end);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     dest,  char{asterisk}     end);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} dest,  char16_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} dest,  char32_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  dest,  wchar_t{asterisk}  end);

} // namespace strf
----
[horizontal]
Return type and value:: Same as `to(dest, (std::size_t)(end - dest))`;
====
[[alignment_format_functions]]
=== Alignment format functions

[horizontal]
.Text aligment format function
`operator>(std::int16_t width)`::: Align to the right ( Or to the left right-to-left (RTL) script )
`operator<(std::int16_t width)`::: Align to the left ( Or to the right right-to-left (RTL) script )
`operator^(std::int16_t width)`::: Center alignment
`operator%(std::int16_t width)`::: Split the content, as in `std::internal`.
`fill(char32_t ch)`::: Set the fill character.

=== Format function aliases

include::ref_global_format_functions.adoc[]

