////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

:numpunct_c: <<numpunct_c,numpunct_c>>
:numpunct: <<numpunct,numpunct>>
:default_numpunct: <<default_numpunct,default_numpunct>>
:no_grouping: <<no_grouping,no_grouping>>
:digits_grouping_iterator: <<digits_grouping_iterator,digits_grouping_iterator>>
:digits_grouping: <<digits_grouping,digits_grouping>>
:reverse_digits_groups: <<reverse_digits_groups,reverse_digits_groups>>
:digits_distribution: <<digits_distribution,digits_distribution>>
:NumericPunctuation: <<NumericPunctuation,NumericPunctuation>>

== Numeric punctuation

=== Facet category template `numpunct_c` [[numpunct_c]]

[source,cpp,subs=normal]
----
namespace strf {
template <int Base> struct numpunct_c {
    constexpr static bool constrainable = true;
    static constexpr {default_numpunct}<base> get_default() noexcept;
};
} // namespace strf
----
For a type to be a facet of the `numpunct_c<Base>`,
it must satisfy __NumericPuntuation__ type requirements

=== Type requirement __NumericPunctuation__ [[NumericPunctuation]]

Given

* `Base`, an integer `constexpr` equal to `2`, `8`, `10` or `16`
* `X`, a __NumericPunctuation__ type for `Base`
* `x`, a const value of type `X`

The following must hold:

* X is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[__CopyConstructible__]
* `<<facet_category,facet_category>><X>` is a type alias to `numpunct_c<Base>`

And following expressions are well-formed and satisfy the following corresponding conditions:

====
[source,cpp,subs=normal]
----
static_cast<{numpunct}<Base>>(x)
----
( `X` is explicitly convertible to `{numpunct}<Base>` )
====
====
[source,cpp,subs=normal]
----
x.grouping()
----
[horizontal]
Return type:: `{digits_grouping}`
====
====
[source,cpp,subs=normal]
----
x.distribute(digcount)
----
[horizontal]
Return type:: `{digits_distribution}`
Return value::  `x.grouping().<<digits_grouping_distribute,distribute>>(digcount)`
====
====
[source,cpp,subs=normal]
----
x.any_group_separation(digcount)
----
[horizontal]
Return type:: `bool`
Return value:: `x.grouping().<<digits_grouping_any_separator,any_separator>>(digcount)`
====
====
[source,cpp,subs=normal]
----
x.thousands_sep_count(digcount)
----
[horizontal]
Return type:: `unsigned`
Return value:: `x.grouping().<<digits_grouping_separators_count,separators_count>>(digcount)`
====
====
[source,cpp,subs=normal]
----
x.thousands_sep()
----
[horizontal]
Return type:: `char32_t`
====
====
[source,cpp,subs=normal]
----
x.decimal_point()
----
[horizontal]
Return type:: `char32_t` 
====




=== Class template `numpunct` [[numpunct]]
////
This class adopts the same nomenclature used in
https://en.cppreference.com/w/cpp/locale/numpunct[`std::numpunct`]:

* The __decimal point__ is the character used to separate the integral part
  from the fractional part.
* The __thousands separator__ is the character used in the integral part
  to facilitate the visualization of large numbers.
* A `group` refers to the number of digits in a contiguous sequence of
  digits in the integral part not containing a __thousands separator__.

For example, if the number `123456.555` is represented as `12,3456.555` then:

* The __decimal point__ is `'.'`
* The __thousands separator__ is `','` ( even though it does separate group of thousands )
* The groups are `4` and `2` ( correspoding to the digit sequences `3456` and `12`,
respectively )
////


[source,cpp,subs=normal]
----
`numpunct<__Base__>` is a facet of the `{numpunct_c}<_Base_>` category,
and it satisfies the requirements of __{NumericPunctuation}__.

template <int Base>
class numpunct {
public:
    using category = {numpunct_c}<Base>;

    // constructors
    constexpr <<numpunct_ctor_default,numpunct>>() noexcept;
    constexpr numpunct(const numpunct& ) noexcept;

    constexpr explicit <<numpunct_ctor_grouping,numpunct>>({digits_grouping}) noexcept;

    template <typename\... IntArgs>
    constexpr explicit numpunct(int grp0, IntArgs\... grps) noexcept;

    // assignment    
    constexpr numpunct& operator=(const numpunct&) noexcept;

    // comparison
    constexpr bool operator==(const numpunct& other) const noexcept;
    constexpr bool operator!=(const numpunct& other) const noexcept;

    // observers
    constexpr char32_t   decimal_point() const noexcept;
    constexpr char32_t   thousands_sep() const noexcept;
    constexpr {digits_grouping} grouping() const noexcept;

    // modifiers
    constexpr numpunct&  decimal_point(char32_t ch) & noexcept;
    constexpr numpunct&& decimal_point(char32_t ch) && noexcept;

    constexpr numpunct&  thousands_sep(char32_t ch) & noexcept;
    constexpr numpunct&& thousands_sep(char32_t ch) && noexcept;

    // utilities
    constexpr {digits_distribution} <<numpunct_thousands_distribute,distribute>>(unsiged digcount) const noexcept;
    constexpr bool <<numpunct_any_group_separation,any_group_separation>>(unsigned digcount) const noexcept;
    constexpr STRF_HD unsigned <<numpunct_thousands_sep_count,thousands_sep_count>>(unsigned digcount) const noexcept;

private:
    char32_t decimal_point_ = U'.';  // exposition only
    char32_t thousands_sep_ = U',';  // exposition only
    {digits_grouping} grouping_;     // exposition only
};
----

==== Public members

[[numpunct_ctor_default]]
====
[source,cpp,subs=normal]
----
constexpr numpunct() noexcept;
----
[horizontal]
Postconditions::
* `decimal_point() == U'.'`
* `thousands_separator() == U','`
* `grouping().empty()` 
====

[[numpunct_ctor_grouping]]
====
[source,cpp,subs=normal]
----
constexpr numpunct({digits_grouping} grpng) noexcept;
----
[horizontal]
Postconditions::
* `decimal_point() == U'.'`
* `thousands_separator() == U','`
* `grouping() == grpng` 
====

[[numpunct_ctor_intgroups]]
====
[source,cpp,subs=normal]
----
template <typename\... IntArgs>
constexpr numpunct(int grp0, IntArgs\... grps) noexcept;
----
[horizontal]
Preconditions:: Same as in the constructor of `digits_grouping` ( see <<digits_grouping_ctor_groups,here>> ).
Postconditions::
* `decimal_point() == U'.'`
* `thousands_sep() == U','`
* `grouping() == {digits_grouping}{grp0, grps\...}`;
====

[[numpunct_thousands_sep_count]]
====
[source,cpp,subs=normal]
----
unsigned thousands_sep_count(unsigned digcount) const;
----
[horizontal]
Return value:: `grouping().<<digits_grouping_separators_count,separators_count>>(digcount))`
====

[[numpunct_thousands_distribute]]
====
[source,cpp,subs=normal]
----
constexpr {digits_distribution} distribute(unsiged digcount) const noexcept;
----
[horizontal]
Return value:: `grouping().<<digits_grouping_distribute,distribute>>(digcount))`
====

[[numpunct_any_group_separation]]
====
[source,cpp,subs=normal]
----
bool any_group_separation(unsigned digcount) const;
----
[horizontal]
Return value:: `grouping().<<digits_grouping_any_separator,any_separator>>(digcount)`
====

[[numpunct_get_decimal_point]]
====
[source,cpp,subs=normal]
----
char32_t decimal_point() const noexcept;
----
Returns the decimal point.
====

[[numpunct_get_thousands_sep]]
====
[source,cpp,subs=normal]
----
char32_t thousands_sep() const noexcept;
----
Returns the thousands separator.
====

[[numpunct_set_decimal_point]]
====
[source,cpp,subs=normal]
----
numpunct &  decimal_point(char32_t ch) &  noexcept;
numpunct && decimal_point(char32_t ch) && noexcept;
----
[horizontal]
Effect:: Changes the decimal point to `ch`.
Postcondition:: `decimal_point() == ch`
Return value:: `*this` or `std::move(*this)`
====

[[numpunct_set_thousands_sep]]
====
[source,cpp,subs=normal]
----
numpunct &  thousands_sep(char32_t ch) &  noexcept;
numpunct && thousands_sep(char32_t ch) && noexcept;
----
[horizontal]
Effect:: Changes the thousands separtor to `ch`.
Postcondition:: `thousands_sep() == ch`
Return value:: `*this` or `std::move(*this)`
====

=== Class template `default_numpunct` [[default_numpunct]]

`default_numpunct<Base>` is the default facet of the
`<<numpunct_c,numpunct_c>><Base>` category.
It is an empty class, optimized to represent the default
state of `numpunct<Base>`

[source,cpp,subs=normal]
----
namespace strf {
template <int Base>
class default_numpunct: {
public:
    using category = {numpunct_c}<Base>;

    constexpr default_numpunct() noexcept= default; // no-op
    constexpr default_numpunct(const default_numpunct& ) noexcept = default; // no-op
    constexpr default_numpunct& operator=(const default_numpunct&) noexcept; // no-op
    constexpr bool operator==(const default_numpunct& other) const noexcept;
    constexpr bool operator!=(const default_numpunct& other) const noexcept;

    constexpr {digits_grouping} grouping() const
    constexpr {digits_distribution} distribute(unsiged digcount) const

    constexpr bool any_group_separation(unsigned digcount) const noexcept;
    constexpr STRF_HD unsigned thousands_sep_count(unsigned digcount) const noexcept;

    constexpr char32_t decimal_point() const noexcept;
    constexpr char32_t thousands_sep() const noexcept;
};
} // namespace strf
----
==== Public members

====
[source,cpp,subs=normal]
----
constexpr bool operator==(const default_numpunct& other) const noexcept;
----
[horizontal]
Return value:: `true`
====
====
[source,cpp,subs=normal]
----
constexpr bool operator!=(const default_numpunct& other) const noexcept;
----
[horizontal]
Return value:: `false`
====

====
[source,cpp,subs=normal]
----
constexpr {digits_grouping} grouping() const
----
[horizontal]
Return value:: `{digits_grouping}{}`
====

====
[source,cpp,subs=normal]
----
constexpr {digits_distribution} distribute(unsiged digcount) const
----
[horizontal]
Return value::  `{digits_distribution}{digcount, 0, {}}`
====

====
[source,cpp,subs=normal]
----
constexpr bool any_group_separation(unsigned digcount) const noexcept;
----
[horizontal]
Return value:: `false`
====

====
[source,cpp,subs=normal]
----
unsigned thousands_sep_count(unsigned digcount) const override;
----
[horizontal]
Return value:: 0
====

====
[source,cpp,subs=normal]
----
char32_t thousands_sep() const noexcept;
----
[horizontal]
Return value:: `U','`
====

====
[source,cpp,subs=normal]
----
char32_t decimal_point() const noexcept;
----
[horizontal]
Return value::  `U'.'`
====


=== Class template `no_grouping` [[no_grouping]]

`no_grouping<_Base_>` is a facet of the `<<numpunct_c,numpunct_c>><_Base_`
category. The only reason for one to use `no_grouping`
rather than `{numpunct}` is optimization. It is not possible to
change the thousaunds separator nor the grouping in a `no_grouping<_Base_>`
object. It is only possible to change its decimal point.

[source,cpp,subs=normal]
----
namespace strf {
template <int Base>
class no_grouping {
public:
    using category = {numpunct_c}<Base>;

    constexpr no_grouping() = default;
    constexpr no_grouping(const no_grouping& ) = default;
    constexpr no_grouping& operator=(const no_grouping&) noexcept;
    constexpr bool operator==(const no_grouping& other) const noexcept;
    constexpr bool operator!=(const no_grouping& other) const noexcept;

    constexpr {digits_grouping} grouping() const
    constexpr {digits_distribution} distribute(unsiged digcount) const

    constexpr bool any_group_separation(unsigned digcount) const noexcept;
    constexpr STRF_HD unsigned thousands_sep_count(unsigned digcount) const noexcept;

    constexpr char32_t   decimal_point() const noexcept;
    constexpr no_grouping&  decimal_point(char32_t ch) & noexcept;
    constexpr no_grouping&& decimal_point(char32_t ch) && noexcept;

    constexpr char32_t   thousands_sep() const noexcept;

private:
    char32_t decimal_point_ = U'.';  // exposition only
};

} // namespace strf
----
==== Public members


====
[source,cpp,subs=normal]
----
constexpr bool operator==(const no_grouping& other) const noexcept;
----
[horizontal]
Return value:: `decimal_point() == other.decimal_point()`
====
====
[source,cpp,subs=normal]
----
constexpr bool operator!=(const no_grouping& other) const noexcept;
----
[horizontal]
Return value:: `decimal_point() != other.decimal_point()`
====

====
[source,cpp,subs=normal]
----
constexpr {digits_grouping} grouping() const
----
[horizontal]
Return value:: `{digits_grouping}{}`
====

====
[source,cpp,subs=normal]
----
constexpr {digits_distribution} distribute(unsiged digcount) const
----
[horizontal]
Return value::  `{digits_distribution}{digcount, 0, {}}`
====

====
[source,cpp,subs=normal]
----
constexpr bool any_group_separation(unsigned digcount) const noexcept;
----
[horizontal]
Return value:: `false`
====

====
[source,cpp,subs=normal]
----
unsigned thousands_sep_count(unsigned digcount) const override;
----
[horizontal]
Return value:: 0
====


====
[source,cpp,subs=normal]
----
unsigned thousands_sep_count(unsigned digcount) const override;
----
[horizontal]
Return value:: 0
====
====
[source,cpp,subs=normal]
----
char32_t thousands_sep() const noexcept;
----
[horizontal]
Return value:: `U','`
====

====
[source,cpp,subs=normal]
----
char32_t decimal_point() const noexcept;
----
[horizontal]
Return value::
====
====
[source,cpp,subs=normal]
----
no_grouping &  decimal_point(char32_t ch) &  noexcept;
no_grouping && decimal_point(char32_t ch) && noexcept;
----
[horizontal]
Effect:: Changes the decimal point to `ch`.
Postcondition:: `decimal_point() == ch`
Return value::  `*this` or `std::move(*this)`
====

=== Class `digits_grouping` [[digits_grouping]]
[source,cpp,subs=normal]
----
namespace strf {
class digits_grouping {
public:
    constexpr static int grp_max = 30;
    constexpr static unsigned grps_count_max = 6;

    // constructors
    constexpr <<digits_grouping_default_ctor,digits_grouping>>() noexcept;
    constexpr digits_grouping(const digits_grouping&) noexcept;

    digits_grouping(const char* str) noexcept;

    constexpr explicit <<digits_grouping_ctor_groups,digits_grouping>>(int grp) noexcept;

    template <typename\... IntArgs>
    constexpr <<digits_grouping_ctor_groups,digits_grouping>>(int grp0, int grp1, IntArgs\... grps) noexcept;

    // assignment 
    constexpr digits_grouping& operator=(const digits_grouping&) noexcept;

    // comparison
    constexpr bool operator==(const digits_grouping&) const noexcept;
    constexpr bool operator!=(const digits_grouping&) const noexcept;

    // observers and utilities
    constexpr bool <<digits_grouping_empty,empty>>() const noexcept;
    constexpr bool <<digits_grouping_any_separator,any_separator>>(int digcount) const noexcept;
    constexpr unsigned <<digits_grouping_separators_count,separators_count>>(int digcount) const noexcept;
    constexpr {digits_grouping_iterator} get_iterator() const noexcept;
    constexpr {digits_distribution} distribute(unsigned digcount) const noexcept;
};
} // namespace strf
----

[[digits_grouping_default_ctor]]
====
[source,cpp,subs=normal]
----
constexpr explicit digits_grouping() noexcept;
----
Equivalent to `digits_grouping(-1)`
[horizontal]
Poscondition:: `<<digits_grouping_empty,empty()>>` returns `true`
====

[[digits_grouping_ctor_groups]]
====
[source,cpp,subs=normal]
----
constexpr explicit digits_grouping(int grp) noexcept;

template <typename\... IntArgs>
constexpr digits_grouping(int grp0, int grp1, IntArgs\... grps) noexcept;
----
Specifies the groups from the least significant ( first argument ) to the most significant.
If the last argument is `-1`, then the last group ( second-to-last argument ) is not to be repeated.

Compile-time requirements::

* All arguments are convertible to `int`
* Total number of arguments is not greater than `grps_count_max`

Preconditions:: 

* The value `g` of last argument is such that `g == -1 || (0 < g && g \<= grp_max)` is `true`.
* The value `g` of any argument but the last is such that `(0 < g && g \<= grp_max)` is `true`.
====

[[digits_grouping_ctor_str]]
====
[source,cpp,subs=normal]
----
digits_grouping(const char* str) noexcept;
----
The characters in `str` specify the groups, starting from the least significant one.
If the last character is `'\xFF'`, then the last group is not repeated.
Passing the empty string (`""`) has the same effect as passing as `"\xFF"`, which has the same effect of the default constructor.

Preconditions::
* `str != nullptr`
* `str` is a null terminated string
* `strlen(str) \<= grps_count_max`
* For each character `ch` in `str` that is not the last character, `0 < ch && ch \<= grp_max` is `true`
* If `ch` is the last character `str`, then `ch == '\xFF' || (0 < ch && ch \<= grp_max)` is `true`
====

[[digits_grouping_empty]]
====
[source,cpp,subs=normal]
----
constexpr bool empty() const noexcept;
----
If `empty()` return `true`, then there is no group. This means that
the thousands separator is absent regardless of the number of
digits.
====

[[digits_grouping_any_separator]]
====
[source,cpp,subs=normal]
----
constexpr bool any_separator(int digcount) const noexcept;
----
[horizontal]
Return value:: `separators_count(digcount) != 0`
====

[[digits_grouping_separators_count]]
====
[source,cpp,subs=normal]
----
constexpr unsigned separators_count(int digcount) const noexcept;
----
[horizontal]
Return value:: The quantity of thousands separators that would appear
               in `digcount` digits.
====

[[digits_grouping_get_iterator]]
====
[source,cpp,subs=normal]
----
constexpr {digits_grouping_iterator} get_iterator() const noexcept;
----
Constructs a `{digits_grouping_iterator}` from this object.
It is supposed to be used when the digits
are to be written backwards, __i.e.__ from the the least to the
most significant.
====

[[digits_grouping_distribute]]
====
[source,cpp,subs=normal]
----
constexpr {digits_distribution} distribute(unsigned digcount) const noexcept;
----
Constructs a `{digits_distribution}` from this object.
It is supposed to be used when the digits
are to be written forwards, __i.e.__ from the the most to the
least significant.

`digcount` is the quantity of digits.

Precondition:: `digcount > 0`
Postconditions:: The return value `dist` is such that
* `dist.highest_group > 0`
* if `x.grouping().empty()` is `true`, then `dist == {digits_distribution}{digcount, 0, {}}`
* if `x.grouping().empty()` is `false` and `dist.<<digits_distribution,middle_groups_count>>` is not `0`, then `dist.low_groups.empty()` is `false`.
====

=== Class `digits_grouping_creator` [[digits_grouping_creator]]

[source,cpp,subs=normal]
----
namespace strf {
class digits_grouping_creator {
public:
    constexpr digits_grouping_creator() noexcept = default;
    constexpr digits_grouping_creator(const digits_grouping_creator&) noexcept = delete;
    constexpr void push_high(int grp) noexcept;
    constexpr bool failed() const noexcept;
    constexpr {digits_grouping} finish_no_more_sep() noexcept;
    constexpr {digits_grouping} finish() noexcept;
};
} // namespace strf
----

Sometimes it is not easy instantiate `{digits_grouping}` through
one of its constructors, since they require you to pass all groups at once.
So `digits_grouping_creator` provides an alternative way to create a `digits_grouping`
object by iteratively informing each of the groups one by one
( passing it to `push_high` function ),
starting from the least significant group.
A tipical use is when one needs to parse a string that describe
grouping, like those provided by localization functions and
whose format varies according to the operating system.
After all groups are passed, `finish()` or `finish_no_more_sep()`
shall be called to create the resulting `digits_grouping` object.
`finish()` is used when the last group is supposed to be repeated
for the more significant digits, while
`finish_no_more_sep()` is for the opposite case.

There is a limit of how may times `push_high` can be called,
which is `digits_grouping::grp_count_max` when `finish()` is used,
and `digits_grouping::grp_count_max - 1` when `finish_no_more_sep()` is used.


=== Class `digits_grouping_iterator` [[digits_grouping_iterator]]

This class provides a way to iterate through the groups of a `{digits_grouping}`
object, from the least to the most significant.

[source,cpp,subs=normal]
----
namespace strf {
class digits_grouping_iterator {
public:
    // constructors
    digits_grouping_iterator() = delete;
    constexpr digits_grouping_iterator(const digits_grouping_iterator&) noexcept = default;
    constexpr explicit digits_grouping_iterator({digits_grouping}) noexcept;

    // assignment
    constexpr digits_grouping_iterator& operator=(const digits_grouping_iterator&) noexcept;

    // comparison
    constexpr bool operator==(const digits_grouping_iterator&) const noexcept;
    constexpr bool operator!=(const digits_grouping_iterator&) const noexcept;

    // iteration
    constexpr unsigned lowest_group() const noexcept; // current
    constexpr void pop_low() noexcept;                // move to next
    constexpr bool is_final() const noexcept;
    constexpr bool no_more_sep() const noexcept;
};
} // namespace strf
----

====
[source,cpp,subs=normal]
----
constexpr unsigned lowest_group() noexcept;
----
[horizontal]
Return:: The current group.
====
====
[source,cpp,subs=normal]
----
constexpr void pop_low() noexcept;
----
[horizontal]
Effect:: Moves to the next (more significant) group.
Precondition:: `is_final()` returns `false`.
====

////
====
[source,cpp,subs=normal]
----
constexpr bool no_more_sep() const noexcept;
----
====
====
[source,cpp,subs=normal]
----
constexpr bool final() const noexcept;
----
====
////


.Example
[source,cpp,subs=normal]
----
strf::digits_grouping grouping{1, 2, 3};  
strf::digits_grouping_iterator it = grouping.get_iterator();

assert(it.lowest_group() == 1 && ! it.is_final());
it.pop_low();
assert(it.lowest_group() == 2 && ! it.is_final());
it.pop_low();
assert(it.lowest_group() == 3 && it.is_final() && ! it.no_more_sep());
----

.Example
[source,cpp,subs=normal]
----
strf::digits_grouping grouping{1, 2, 3, -1};
strf::digits_grouping_iterator it = grouping.get_iterator();

assert(it.lowest_group() == 1 && ! it.is_final());
it.pop_low();
assert(it.lowest_group() == 2 && ! it.is_final());
it.pop_low();
assert(it.lowest_group() == 3 && ! it.is_final());
it.pop_low();            
assert(it.is_final() && it.no_more_sep());
----

////
digits_grouping_iterator it = ...;
unsigned digcount = ...; // number of digits to print
...
while(1) {
   if (it.no_more_sep() || digcount < it.lowest_group()) {
      // write digcount digits and quit
      ...
      break;
   }
   if (it.is_final()) {
      while (digcount > it.lowest_group()) {
          ... // write it.lowest_group() digits and a separator
          digcount -= it.lowest_group();
      }
      ... // print digcount digits and quit
      break;
   }
   assert (digcount >= it.lowest_group());
   ... // write it.lowest_group() digits and a separator
   digcount -= it.lowest_group();
   it.pop_low();
}
////

=== Class `digits_distribution` [[digits_distribution]]

This struct is designed to be used in algoritms that
print groups of digits separated by the __thousands separator__
from the most to the least significant.

[source,cpp,subs=normal]
----
namespace strf {
struct digits_distribution {
    {reverse_digits_groups} low_groups;
    unsigned middle_groups_count;
    unsigned highest_group;
};
} // namespace strf
----

* `highest_group` is the most significant group.
* `low_groups` contains the least signficant groups.
* `middle_groups_count` how many groups equal to `low_groups.highest_groups()` follow the highest group.

////
is repeated (
if it's zero, it means that there is one group equal to `low_groups.highest_groups()` ).
////

.Example
[source,cpp,subs=normal]
----
strf::numpunct<__Base__> punct = ...;
strf::digits_distribution dist = punct.distribute(__digits_count__);
assert(dist.highest_groups != 0);

// step 1
... // print the most significant dist.highest_group digits

// step 2 - print middle groups
auto mg = dist.low_groups.highest_group();
dist.low_groups.pop_high();
for (unsigned i=0; i < dist.middle_groups_count; ++i) {
    ... // print the separator, then mg digits
}

// step 3 - least significant groups
while( ! dist.low_groups.empty()) {
    auto g = dist.low_groups.highest_group();
    dist.low_groups.pop_high();

    ... // prints the separator, then g digits
}
----

=== Class `reverse_digits_groups` [[reverse_digits_groups]]

The class `reverse_digits_groups` aims to be used in loops that
print groups of digits separated by the thousand separator from
the most to the least significant.

[source,cpp,subs=normal]
----
namespace strf {
class reverse_digits_groups {
public:
    constexpr static unsigned grp_max = {digits_grouping}::grp_max;
    constexpr static unsigned grps_count_max = {digits_grouping}::grps_count_max;

    constexpr reverse_digits_groups() noexcept;
    constexpr reverse_digits_groups(const reverse_digits_groups&) noexcept;
    constexpr bool operator==(const reverse_digits_groups& other) const noexcept;
    constexpr bool operator!=(const reverse_digits_groups& other) const noexcept;
    constexpr reverse_digits_groups& operator=(const reverse_digits_groups& other) noexcept;
    constexpr void push_low(unsigned group) noexcept;
    constexpr void pop_high() noexcept;
    constexpr unsigned highest_group() const noexcept;
    constexpr bool empty() const noexcept;
};
} // namespace strf
----

[NOTE]
====
The meaning of "group" used in `{reverse_digits_groups}`
is different than in previous classes.

The value returned by `{reverse_digits_groups}::highest_group()`
is expected to always be the actual number of digits in the group.
This why you prior need to pass the total number of digits to
`digits_distribution::<<digits_grouping_distribute,distribute>>`
function: so that it can calculate how many digits actually
go in each group.

On the other hand, there is no similar need when you create a
`{digits_grouping_iterator}` object (
`digits_distribution::<<digits_grouping_iterator,iterator>>` has
no parameter ). So the value returned by
`{digits_grouping_iterator}::lowers_group()` may actually
be larger than the amount of remaining digits to print.
====


====
[source,cpp,subs=normal]
----
constexpr unsigned highest_group() const noexcept;
----
Return the actual number of digits in the current group.

Postconditions:: The return value is zero when `empty()` returns `true`. Otherwise, it is non-zero
and not greater than `grp_max`;
====

====
[source,cpp,subs=normal]
----
constexpr void pop_high() noexcept;
----
Effects:: None when `empty()` returns `true`. Otherwise, moves the return value of `highest_group()` to the next (less significant) group.
====


