////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

== Destination types

[[destination_no_reserve]]
=== Class template `destination_no_reserve`
====
[source,cpp,subs=normal]
----
template <typename OutbufCreator, typename FPack>
class destination_no_reserve
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `OutbufCreator` satisfies <<OutbufCreator,_OutbufCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename OutbufCreator, typename FPack>
class destination_no_reserve
{
public:
    using char_type = typename OutbufCreator::char_type;

    // <<destination_no_reserve_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_no_reserve(Args&&\...);
    constexpr destination_no_reserve(const destination_no_reserve&);
    constexpr destination_no_reserve(destination_no_reserve&&);

    // <<destination_no_reserve_with,facets>>
    template <typename\... FPE>
    destination_no_reserve<OutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_no_reserve<OutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_no_reserve_reserve,size reserve>>
    constexpr destination_calc_size<OutbufCreator, FPack>
    reserve_calc() const &;

    constexpr destination_calc_size<OutbufCreator, FPack>
    reserve_calc() &&; 

    constexpr destination_with_given_size<OutbufCreator, FPack>
    reserve(std::size_t) const &;

    constexpr destination_with_given_size<OutbufCreator, FPack>
    reserve(std::size_t) &&;

    constexpr destination_no_reserve&  no_reserve() &;
    constexpr destination_no_reserve&& no_reserve() &&;
    constexpr const destination_no_reserve&  no_reserve() const &;
    constexpr const destination_no_reserve&& no_reserve() const &&;

    // <<destination_no_reserve_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>&
              , const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type>
              , const Args&\...) const;

private:
    OutbufCreator _outbuf_creator; // exposition only
    FPack _fpack;                  // exposition only
};

} // namespace strf
----

==== Public member functions

[[destination_no_reserve_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_no_reserve(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<OutbufCreator, Args\...>` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `_outbuf_creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr destination_no_reserve(const destination_no_reserve&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `OutbufCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_no_reserve(destination_no_reserve&&) = default;
----
Move constructor.
====
[[destination_no_reserve_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_no_reserve< OutbufCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates a `destination_no_reserve` object whose `_outbuf_creator`
is initialized with this `_outbuf_creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_no_reserve< OutbufCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_no_reserve` object whose `_outbuf_creator`
is initialized with `std::move(_outbuf_creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_no_reserve_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `_outbuf_creator`
is initialized with this `_outbuf_creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `_outbuf_creator`
is initialized with `std::move(_outbuf_creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<OutbufCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` whose `_size` is initialized with `size`,
whose `_outbuf_creator` is initialized with this `_outbuf_creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<OutbufCreator, FPack>
reserve(std::size_t size) &&;
----
Compile-time requirements::
`OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` object whose `_size` is initialized with `size`,
whose `_outbuf_creator` is initialized with `std::move(_outbuf_creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve&  no_reserve() &;
constexpr destination_no_reserve&& no_reserve() &&;
constexpr const destination_no_reserve&  no_reserve() const &;
constexpr const destination_no_reserve&& no_reserve() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====

[[destination_no_reserve_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
// Return type::
// - `decltype(std::declval<decltype(_outbuf_creator.create())&>().finish())` if such type is valid, otherwise `void`
Effect::
. Creates/get the <<basic_outbuf,outbuf>> object doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create()
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = <<make_printer, make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg)
----
, where `preview` is an instance of `preview<false, false>`.
. For each `p` object does `p.print_to(ob)`
. Returns `ob.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates/get the <<basic_outbuf,outbuf>> object doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create()
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = <<make_printer,make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg)
----
, where `preview` is an instance of `preview<false, false>`.
. Prints into `ob` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `ob.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
[[destination_calc_size]]
=== Class template `destination_calc_size`
====
[source,cpp,subs=normal]
----
template <typename SizedOutbufCreator, typename FPack>
class destination_calc_size;
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedOutbufCreator` satisfies <<SizedOutbufCreator,_SizedOutbufCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedOutbufCreator, typename FPack>
class destination_reserve_calc
{
public:
    using char_type = typename SizedOutbufCreator::char_type;

    // <<destination_reserve_calc_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_reserve_calc(Args&&\...);

    constexpr destination_reserve_calc(const destination_reserve_calc&) = default;
    constexpr destination_reserve_calc(destination_reserve_calc&&) = default;

    // <<destination_reserve_calc_with,facets>>
    template <typename\... FPE>
    destination_reserve_calc<SizedOutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_reserve_calc<SizedOutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_reserve_calc_reserve,size reserve>>
    constexpr destination_no_reserve<SizedOutbufCreator, FPack>
    no_reserve() const &;

    constexpr destination_no_reserve<SizedOutbufCreator, FPack>
    no_reserve() &&; 

    constexpr destination_with_given_size<SizedOutbufCreator, FPack>
    reserve(std::size_t) const &;

    constexpr destination_with_given_size<SizedOutbufCreator, FPack>
    reserve(std::size_t) &&;

    constexpr destination_reserve_calc&  reserve_calc() &;
    constexpr destination_reserve_calc&& reserve_calc() &&;
    constexpr const destination_reserve_calc&  reserve_calc() const &;
    constexpr const destination_reserve_calc&& reserve_calc() const &&;

    // <<destination_reserve_calc_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    OutbufCreator _outbuf_creator; // exposition only
    FPack _fpack;                  // exposition only
};

} // namespace strf
----

[[destination_reserve_calc_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_reserve_calc(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<OutbufCreator, Args\...>::value` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `_outbuf_creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr destination_reserve_calc(const destination_reserve_calc&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `OutbufCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_reserve_calc(destination_reserve_calc&&) = default;
----
Move constructor.
====
[[destination_reserve_calc_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_reserve_calc< OutbufCreator
                        , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                       , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_reserve_calc` object whose `_outbuf_creator`
is initialized with this `_outbuf_creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_reserve_calc< OutbufCreator
                        , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                       , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_reserve_calc` object whose `_outbuf_creator`
is initialized with `std::move(this\->_outbuf_creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_reserve_calc_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve<OutbufCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `_outbuf_creator`
is initialized with this `_outbuf_creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `_outbuf_creator`
is initialized with `std::move(_outbuf_creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<OutbufCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` whose `_size` is initialized with `size`,
whose `_outbuf_creator` is initialized with this `_outbuf_creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<OutbufCreator, FPack>
reserve(std::size_t) &&;
----
Compile-time requirements::
`OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` object whose `_size` is initialized with `size`,
whose `_outbuf_creator` is initialized with `std::move(_outbuf_creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_reserve_calc&  reserve_calc() &;
constexpr destination_reserve_calc&& reserve_calc() &&;
constexpr const destination_reserve_calc&  reserve_calc() const &;
constexpr const destination_reserve_calc&& reserve_calc() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====
[[destination_reserve_calc_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<PrintableWithSizePreview,_PrintableWithSizePreview_>>.
Effect::
. Creates a `print_preview<true, false>` object.
+
[source,cpp,subs=normal]
----
print_preview<true, false> preview;
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = <<make_printer, make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg)
----
. Creates/get the <<basic_outbuf,outbuf>> object doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create(preview.get_size())
----
. For each `p` object does `p.print_to(ob)`
. Returns `ob.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<PrintableWithSizePreview,_PrintableWithSizePreview_>>.
Effect::
. For each `arg` in `args\...`, do
+
[source,cpp,subs=normal]
----
print_preview<true, false> preview;
auto p = <<make_printer,make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg);
----
. Calculates the size of the content to be printed according to the
  <<tr_string,tr-string syntax>> and using the `preview` objects
  of the previous step.
. Creates/get the <<basic_outbuf,outbuf>> object by doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create(size)
----
, where `size` is the value calculated in the previous step.
. Prints into `ob` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `ob.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
====

[[destination_with_given_size]]
=== Class template `destination_with_given_size`
====
[source,cpp,subs=normal]
----
template <typename SizedOutbufCreator, typename FPack>
class destination_with_given_size
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedOutbufCreator` satisfies <<SizedOutbufCreator,_SizedOutbufCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedOutbufCreator, typename FPack>
class destination_with_given_size
{
public:
    using char_type = typename SizedOutbufCreator::char_type;

    // <<destination_with_given_size_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_with_given_size(std::size_t, Args&&\...);
    constexpr destination_with_given_size(const destination_with_given_size&) = default;
    constexpr destination_with_given_size(destination_with_given_size&&) = default;

    // <<destination_with_given_size_with,facets>>
    template <typename\... FPE>
    destination_with_given_size<SizedOutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_with_given_size<SizedOutbufCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_with_given_size_reserve,size reserve>>
    constexpr destination_calc_size<SizedOutbufCreator, FPack>
    reserve_calc() const &;

    constexpr destination_calc_size<SizedOutbufCreator, FPack>
    reserve_calc() &&; 

    constexpr destination_no_reserve<SizedOutbufCreator, FPack>
    no_reserve() const &;

    constexpr destination_no_reserve<SizedOutbufCreator, FPack>
    no_reserve() &&;

    constexpr destination_with_given_size&  reserve(std::size_t) &;
    constexpr destination_with_given_size&& reserve(std::size_t) &&;
    constexpr destination_with_given_size   reserve(std::size_t) const &;
    constexpr destination_with_given_size   reserve(std::size_t) const &&;

    // <<destination_with_given_size_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename ... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    std::size_t _size              // exposition only
    OutbufCreator _outbuf_creator; // exposition only
    FPack _fpack;                  // exposition only
};

} // namespace strf
----
[[destination_with_given_size_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_with_given_size(std::size_t size, Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<OutbufCreator, Args\...>`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `_outbuf_creator` with `std::forward<Args>(args)\...`.
- Initializes `_size` with `size`
====
====
[source,cpp]
----
constexpr destination_with_given_size(const destination_with_given_size&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `OutbufCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_with_given_size(destination_with_given_size&&) = default;
----
Move constructor.
====
[[destination_with_given_size_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_with_given_size< OutbufCreator
                           , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                          , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `_outbuf_creator` is initialized with this `_outbuf_creator`
, and whose `_fpack` is initialized with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`

====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_with_given_size< OutbufCreator
                           , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                          , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `_outbuf_creator` is initialized with `std::move(_outbuf_creator)` from this object
, and whose `_fpack` is initialized with
`pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_with_given_size_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve<OutbufCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object
whose `_outbuf_creator` is initialized with this `_outbuf_creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> no_reserve() &&;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `_outbuf_creator`
is initialized with `std::move(_outbuf_creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object
whose `_outbuf_creator` is initialized with this `_outbuf_creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<OutbufCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `OutbufCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedOutbufCreator,_SizedOutbufCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `_outbuf_creator`
is initialized with `std::move(_outbuf_creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size&  reserve(std::size_t size) &;
constexpr destination_with_given_size&& reserve(std::size_t size) &&;
----
[horizontal]
Effect:: assign `size` to `_size`.
Return:: This object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size reserve(std::size_t size) const &;
constexpr destination_with_given_size reserve(std::size_t size) const &&;
----
[horizontal]
Effect:: Creates an `destination_with_give_size` object
whose `_size` is initialized with `size`,
whose `_outbuf_creator` is initialized with this `_outbuf_creator`,
and whose `facets_pack` object with this `_fpack`.
====
[[destination_with_given_size_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates/get the <<basic_outbuf,outbuf>> object doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create(_size)
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = <<make_printer, make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg)
----
, where `preview` is an instance of `preview<false, false>`.
. For each `p` object does `p.print_to(ob)`
. Returns `ob.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates/get the <<basic_outbuf,outbuf>> object doing
+
[source,cpp,subs=normal]
----
decltype(auto) ob = _outbuf_creator.create(_size)
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = <<make_printer,make_printer>><char_type, FPack>(strf::rank<5>(), _fpack, preview, arg)
----
, where `preview` is an instance of `preview<false, false>`.
. Prints into `ob` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `ob.finish()` if such expression is valid ( which is optional ).
====
[[OutbufCreator]]
=== Type requirement _OutbufCreator_
- `T` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[MoveConstructible]
- `T` has a member type `char_type`.
- Given `x`, an expression of type `const T`, the expression `x.create()`
  is valid and the type `std::remove_reference_t<decltype(x.create())>`
  must be the same as, or derive from, `basic_outbuf<char_type>`.

[[SizedOutbufCreator]]
=== Type requirement _SizedOutbufCreator_
- `T` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[MoveConstructible]
- `T` has a member type `char_type`.
- Given `s` and `x`, expressions of type `std::size_t` and `const T` respectively,
  the expression `x.create(s)` is valid and the type
  `std::remove_reference_t<decltype(x.create())>`
  must be the same as, or derive from, `basic_outbuf<char_type>`

[[tr_string]]
=== Tr-string syntax
To-do