////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////
[[main]]
= `<strf/to_cfile.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <strf/to_cfile.hpp>
:toclevels: 1
:icons: font

:min_space_after_recycle: <<outbuff_hpp#min_space_after_recycle,min_space_after_recycle>>
:underlying_outbuff: <<outbuff_hpp#underlying_outbuff,underlying_outbuff>>
:underlying_char_type: <<outbuff_hpp#underlying_char_type,underlying_char_type>>
:basic_outbuff: <<outbuff_hpp#basic_outbuff,basic_outbuff>>
:basic_outbuff_noexcept: <<outbuff_hpp#basic_outbuff_noexcept,basic_outbuff_noexcept>>
:narrow_cfile_writer: <<narrow_cfile_writer,narrow_cfile_writer>>
:wide_cfile_writer: <<wide_cfile_writer,wide_cfile_writer>>

:destination_no_reserve: <<strf_hpp#destination,destination_no_reserve>>
:OutbuffCreator: <<strf_hpp#OutbuffCreator,OutbuffCreator>>


NOTE: This document is still a work in progress.

NOTE: This header files includes `<strf.hpp>`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class narrow_cfile_writer final: public basic_outbuff_noexcept<CharT>
{ /{asterisk}\...{asterisk}/ };

class wide_cfile_writer final: public basic_outbuff_noexcept<wchar_t>
{ /{asterisk}\...{asterisk}/ };

// Destination makers:

template <typename CharT = char>
/{asterisk} \... {asterisk}/  to(std::FILE{asterisk});

/{asterisk} \... {asterisk}/ wto(std::FILE{asterisk});

} // namespace strf
----

[[narrow_cfile_writer]]
== Class template `narrow_cfile_writer`
=== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class narrow_cfile_writer final: public {basic_outbuff_noexcept}<CharT> {
public:
    explicit narrow_cfile_writer(std::FILE{asterisk} dest);

    narrow_cfile_writer(const narrow_cfile_writer&) = delete;
    narrow_cfile_writer(narrow_cfile_writer&&) = delete;

    void recycle() noexcept;
    struct result  {
        std::size_t count;
        bool success;
    };
    result finish();
};

} // namespace strf
----
=== Public member functions
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good() == true`, calls `std::fwrite(p0, pointer() - p0, sizeof(CharT), dest)`,
    where `dest` is the `FILE{asterisk}` used to initialize this object, and
    `p0` is value `pointer()` would return before any call to `advance` and `advance_to`
    since the last call to `recycle()`, or since this object's contruction,
    whatever happened last.
-  If the returned value of std::fwrite is less then pointer() - p0, calls set_good(false).
-  Calls set_pointer and/or set_end.
Postconditions:: `size() >= min_space_after_recycle<CharT>()`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the sum of values returned by all calls `std::fwrite` done by this object.
- `result::success` is the value `good()` would return before this call to `finish()`
====


[[wide_cfile_writer]]
== Class template `wide_cfile_writer`
=== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

class wide_cfile_writer final: public {basic_outbuff_noexcept}<wchar_t> {
public:
    explicit wide_cfile_writer(std::FILE{asterisk} dest);

    wide_cfile_writer(const narrow_cfile_writer&) = delete;
    wide_cfile_writer(narrow_cfile_writer&&) = delete;

    void recycle() noexcept;
    struct result {
        std::size_t count;
        bool success;
    };
    result finish();
};

} // namespace strf
----
=== Public member functions
====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good() == true`, for each character `ch` in the range [ `p0`, `pointer()` ) calls `std::fputwc(ch, dest)`, until WEOF is returned or the whole range is read, where `dest` is the `FILE{asterisk}` used to initialize this object, and `p0` is the value `pointer()` would return before any call to `advance` and `advance_to` since the last call to `recycle()`, or since this object's contruction, whatever happened last.
- If `std::fputwc` returns WEOF, calls `set_good(false)`.
- Calls `set_pointer` and/or `set_end`.
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the number of calls to `std::fputwc` by this object that did not return WEOF .
- `result::success` is the value `good()` would return before this call to `finish()`
====

[[to]]
== Function template `to`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT = char>
__/{asterisk} see below {asterisk}/__ to(std::FILE{asterisk} dest);

} // namespace strf
----
[horizontal]
Return type:: `{destination_no_reserve}<OBC>`, where `OBC` is an implementation-defined
              type that satifies __{OutbuffCreator}__.
Return value:: A destination object whose internal __{OutbuffCreator}__ object `obc`
is such that `obc.create()` returns a `{narrow_cfile_writer}<CharT>` object initialized
with `dest`.

[[wto]]
== Function `wto`

[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ wto(std::FILE{asterisk} dest);

} // namespace strf
----
[horizontal]
Return type:: `{destination_no_reserve}<OBC>`, where `OBC` is an implementation-defined
              type that satifies __{OutbuffCreator}__.
Return value:: A destination object whose internal __{OutbuffCreator}__ object `obc`
is such that `obc.create()` returns a `{wide_cfile_writer}` object initialized
with `dest`.