////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////
[[main]]
= `<to_streambuf.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <to_cfile.hpp>
:toclevels: 1
:icons: font

:min_size_after_recycle: <<outbuf_hpp#min_size_after_recycle,min_size_after_recycle>>
:underlying_outbuf: <<outbuf_hpp#underlying_outbuf,underlying_outbuf>>
:underlying_char_type: <<outbuf_hpp#underlying_char_type,underlying_char_type>>
:basic_outbuf: <<outbuf_hpp#basic_outbuf,basic_outbuf>>
:basic_streambuf_writer: <<basic_streambuf_writer,basic_streambuf_writer>>

:destination_no_reserve: <<strf_hpp#destination,destination_no_reserve>>
:OutbufCreator: <<strf_hpp#OutbufCreator,OutbufCreator>>


NOTE: This document is still a work in progress.

NOTE: This header files includes `<strf.hpp>`

[[basic_streambuf_writer]]
== Class template `basic_streambuf_writer`
=== Synopsis
[source,cpp]
----
namespace strf {

template <typename CharT, typename Traits = std::char_traits<CharT> >
class basic_streambuf_writer final: public basic_outbuf<CharT> {
public:
    explicit basic_streambuf_writer(std::basic_streambuf<CharT, Traits>& dest);
    explicit basic_streambuf_writer(std::basic_streambuf<CharT, Traits>* dest);

    basic_streambuf_writer(const basic_streambuf_writer&) = delete;
    basic_streambuf_writer(basic_streambuf_writer&&) = delete;

    void recycle() override;
    struct result {
        std::streamsize count;
        bool success;
    };
    result finish();
};

// Global type aliases

using streambuf_writer
    = basic_streambuf_writer<char, std::char_traits<char> >;

using wstreambuf_writer
    = basic_streambuf_writer<wchar_t, std::char_traits<wchar_t> >;

} // namespace strf
----
=== Public member functions

====
[source,cpp]
----
void recycle() override;
----
[horizontal]
Effects::
- If `good()` is `true` then calls `dest.sputn(p0, pointer() - p0)`, where `dest` is the reference this object was initialized with, and `p0` is the return value of `pointer()` before any call to `advance` and `advance_to` since the last call to `recycle()`, or since this object's contruction, whatever happened last.
- If the returned value of `dest.sputn` is less then `pointer() - p0`, calls `set_good(false)`.
- Calls `set_pointer` and/or `set_end`.
Postconditions:: `size() >= min_size_after_recycle<sizeof(CharT)>()`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle()` and `set_good(false)`.
Return value::
- `result::count` is the sum of the values returned by `dest.sputn`.
- `result::success` is the value `good()` would return before this call to `finish()`.
====

== Function templates `to`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, typename Traits>
__/{asterisk} see below {asterisk}/__ to(std::basic_streambuf<CharT, Traits>& dest);

template <typename CharT, typename Traits>
__/{asterisk} see below {asterisk}/__ to(std::basic_streambuf<CharT, Traits>* dest);


} // namespace strf
----
[horizontal]
Return type:: `{destination_no_reserve}<OBC>`, where `OBC` is an implementation-defined
              type that satifies __{OutbufCreator}__.
Return value:: A destination object whose internal __{OutbufCreator}__ object `obc`
is such that `obc.create()` returns a `{basic_streambuf_writer}<CharT, Traits>` object initialized
with `dest`.