////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

[[main]]
= `<strf/destination.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <strf/destination.hpp>
:toclevels: 1
:icons: font

:destination: <<destination,destination>>
:put: <<destination_put,put>>

:print_dest: <<print_dest,print_dest>>
:print_dest_space_after_flush: <<print_dest,print_dest_space_after_flush>>

:basic_cstr_writer: <<basic_cstr_writer, basic_cstr_writer>>
:basic_char_array_writer: <<basic_char_array_writer, basic_char_array_writer>>
:discarded_destination: <<discarded_destination,discarded_destination>>

:garbage_buff: <<garbage_buff, garbage_buff>>
:garbage_buff_end: <<garbage_buff, garbage_buff_end>>
:log2_garbage_buff_size: <<garbage_buff, log2_garbage_buff_size>>
:garbage_buff_size: <<garbage_buff, garbage_buff_size>>

:value_type: <<destination_value_type,value_type>>
:buffer_ptr: <<destination_buffer_ptr,buffer_ptr>>
:buffer_end: <<destination_buffer_end,buffer_end>>
:buffer_space: <<destination_buffer_space,buffer_space>>
:flush: <<destination_flush,flush>>
:recycle_buffer: <<destination_recycle_buffer,recycle_buffer>>
:ensure: <<destination_ensure,ensure>>
:advance_to: <<destination_advance_to,advance_to>>
:advance_count: <<destination_advance_count,advance_count>>
:advance: <<destination_advance,advance>>
:good: <<destination_good,good>>
:write: <<destination_write,write>>
:set_buffer_ptr: <<destination_set_buffer_ptr,set_buffer_ptr>>
:set_buffer_end: <<destination_set_buffer_end,set_buffer_end>>
:set_good: <<destination_set_good,set_good>>
:do_write: <<destination_do_write,do_write>>

////
`<strf/destination.hpp>` is a lighweight header can be used in freestanding evironments. All other headers of the strf library include it. It's not affected by the `STRF_SEPARATE_COMPILATION` macro.
////

== Synopsis

[source,cpp,subs=normal]
----
namespace strf {

template <typename T, unsigned Log2BufferSpace>
class {destination};

constexpr std::size_t {print_dest_space_after_flush} = ...; // >= 64

template <typename CharT>
using {print_dest} = destination<CharT, ...>;

template <typename CharT>
class {basic_cstr_writer};

template <typename CharT>
class {basic_char_array_writer};

template <typename CharT>
class {discarded_destination};

template <typename CharT>
CharT* {garbage_buff}();

template <typename CharT>
CharT* {garbage_buff_end}();

using u8cstr_writer  = basic_cstr_writer<char8_t>;
using cstr_writer    = basic_cstr_writer<char>;
using u16cstr_writer = basic_cstr_writer<char16_t>;
using u32cstr_writer = basic_cstr_writer<char32_t>;
using wcstr_writer   = basic_cstr_writer<wchar_t>;

} // namespace strf
----

== Class template `destination` [[destination]]

=== Synopsis

[source,cpp,subs=normal]
----
namespace strf {

template <typename T, unsigned Log2BufferSpace>
class destination: destination<T, Log2BufferSpace - 1>
{
public:
    static constexpr std::size_t buffer_space_after_recycle = 1ull << Log2BufferSpace;

protected:
    using destination<T, Log2BufferSpace - 1>::destination;
};

template <typename T>
class destination<T, 0>
{
public:
    static constexpr std::size_t buffer_space_after_recycle = 1;
    using value_type = T;

    destination(const destination&) = delete;
    destination(destination&&) = delete;
    destination& operator=(const destination&) = delete;
    destination& operator=(destination&&) = delete;

    virtual ~destination() = default;

    T{asterisk} {buffer_ptr}() const noexcept;
    T{asterisk} {buffer_end}() const noexcept;
    std::size_t {buffer_space}() const noexcept;
    bool {good}() const noexcept;
    void {advance_to}(T{asterisk} p);
    void {advance}(std::size_t n);
    void {ensure}(std::size_t s);
    void {flush}();

    void {write}(const T{asterisk} data, std::size_t count);

    virtual void {recycle_buffer}() = 0;

protected:

    <<destination_ctor_range,destination>>(T{asterisk} buff, T{asterisk} buff_end);

    <<destination_ctor_count,destination>>(T{asterisk} buff, std::size_t buff_size);

    void {set_buffer_ptr}(T{asterisk} p) noexcept;
    void {set_buffer_end}(T{asterisk} e) noexcept;
    void {set_good}(bool g) noexcept;

    virtual void {do_write}(const T{asterisk} data, std::size_t count);
};

// global functions

template <typename T>
void {put}(destination<T, 0>& dest, T value);

} // namespace strf
----

=== Member types

[[destination_value_type]]
====
[source,cpp,subs=normal]
----
using value_type = T;
----
====

=== Public member functions

[[destination_buffer_ptr]]
====
[source,cpp]
----
T* buffer_ptr() const noxcept;
----
[horizontal]
Return:: The memory position where the content shall be written.
====
[[destination_buffer_end]]
====
[source,cpp]
----
T* buffer_end() const noxcept;
----
[horizontal]
Return:: The end of memory position where the content shall be written.
         Dereferencing `{buffer_end}()` has undefined behaviour.
====
[[destination_buffer_space]]
====
[source,cpp]
----
std::size_t buffer_space() const noexcept;
----
[horizontal]
Return:: `{buffer_end}() - {buffer_ptr}()`
====

[[destination_flush]]
====
[source,cpp]
----
void flush();
----
[horizontal]
Effect:: Calls `recycle_buffer()`
====

[[destination_recycle_buffer]]
====
[source,cpp]
----
virtual void recycle_buffer() = 0;
----
[horizontal]
Posconditions::
- `{buffer_space}() >= buffer_space_after_recycle`
- The range [ `{buffer_ptr}()`, `{buffer_end}()` ) is valid accessible memory area
- If the return value of `{good}()` was `false` before this call to `{recycle_buffer}()`, then `{good}()` remains returning `false`.
====

// Effect::
// Depends on the derivate class, but if `{good}()` returns `true`,
// then supposedly consumes the content in the range [`p`, `{buffer_ptr}()`),
// where `p` is the value `{buffer_ptr}()` would have returned if called before
// any call to `{advance}` or `{advance_to}` in this object since the last
// time `{recycle_buffer}` was called in this object, or, in case `{recycle_buffer}`
// was not called in this object yet, since this object was constructed.

[[destination_ensure]]
====
[source,cpp]
----
void ensure(std::size_t s)
----
[horizontal]
Effect:: Calls `{recycle_buffer}()` if `{buffer_space}() < s`.
Precondition:: `s \<= buffer_space_after_recycle`
Postcondition:: `{buffer_space}() >= s`
====
[[destination_advance_to]]
====
[source,cpp]
----
void advance_to(T* p)
----
[horizontal]
Effect:: Advance the buffer's pointer to `p`.
Precondition:: `{buffer_ptr}() \<= p && p \<= buffer_end()`
Postcondition:: `{buffer_ptr}() == p`
====
[[destination_advance_count]]
====
[source,cpp]
----
void advance(std::size_t n)
----
[horizontal]
Effect:: Equivalent to `{advance_to}({buffer_ptr}() + n)`
Precondition:: `n \<= {buffer_space}()`
====
[[destination_advance]]
====
[source,cpp]
----
void advance()
----
[horizontal]
Effect:: Equivalent to `{advance_to}(1)`
Precondition:: `{buffer_ptr}() != {buffer_end}()`
====
[[destination_good]]
====
[source,cpp]
----
bool good() const;
----
[horizontal]
Return:: The state of this object.
Semantincs:: `{good}() == false` means that writting anything on
   `{buffer_ptr}()`, and calling `{advance_to}` and `{recycle_buffer}()` has no
   relevant side effect besides their postconditions.
Note:: The range [ `{buffer_ptr}()`, `{buffer_end}()` ) shall aways be a valid
accessible memory, even when `{good}()` returns `false`.
====

[[destination_write]]
====
[source,cpp]
----
void write(const T* data, std::size_t count);
----
[horizontal]
Effect:: If `count \<= {buffer_space}()` is `true`, copy `count` elements of
         of the array pointer by `data` into `{buffer_ptr}()` and calls
         `{advance}(count)`.
         Otherwise, calls `{do_write}(data, count)`.
====

=== Protected Member functions

[[destination_ctor_range]]
====
[source,cpp]
----
destination(T* buff_, T* buff_end_)
----
[horizontal]
Preconditions::
- `buff_ \<= buff_end_`
- The range [ `buff_`, `buff_end_` ) must be an accessible memory area.
Posconditions::
- `{buffer_ptr}() == buff_`
- `{buffer_end}() == end_`
- `{good}() == true`
====
[[destination_ctor_count]]
====
[source,cpp]
----
destination(T* buff_, std::size_t buff_size_)
----
[horizontal]
Preconditions::
- The range [ `buff_`, `buff_ + n ` ) must be an accessible memory area.
Posconditions::
- `{buffer_ptr}() == buff_`
- `{buffer_end}() == buff_ + n`
- `{good}() == true`
====
[[destination_set_buffer_ptr]]
====
[source,cpp]
----
void set_buffer_ptr(T* p) noexcept
----
[horizontal]
Postconditions:: `{buffer_ptr}() == p`
====
[[destination_set_buffer_end]]
====
[source,cpp]
----
void set_buffer_end(T* e) noexcept
----
[horizontal]
Postconditions:: `{buffer_end}() == e`
====
[[destination_set_good]]
====
[source,cpp]
----
void set_good(bool g) noexcept
----
[horizontal]
Postconditions:: `{good}() == g`
====

[[destination_do_write]]
====
[source,cpp]
----
virtual void do_write(const T* data, std::size_t count);
----
[horizontal]
Effect:: Writes the first `count` elements of the array pointed
        by `data` into this object, calling `{recycle_buffer}()` how many time
        it is necessary.
Note:: This function is made virtual so that any derived classes
       can override it with an optimized version.
====

=== Global functions

[[destination_put]]
====
[source,cpp,subs=normal]
----
template <typename T>
void put(destination<T, 0>& dest, T value);
----
[horizontal]
Effect::
+
[source,cpp]
----
if (dest.buffer_space() == 0) {
    dest.recycle_buffer();
}
*dest.buffer_ptr() = value;
dest.advance();
----
====

[[print_dest]]
== Type alias template `print_dest`

[source,cpp,subs=normal]
----
namespace strf {

constexpr unsigned    log2_print_dest_space_after_flush = ...; // >= 6
constexpr std::size_t      print_dest_space_after_flush = ...; // >= 64

template <typename CharT>
using print_dest = {destination}<CharT, log2_print_dest_space_after_flush>;

} // namespace strf
----

* `log2_print_dest_space_after_flush` is an implementation-defined value
that is greater than or equal to `6`.

* `print_dest_space_after_flush` is equal to `(std::size_t)1 << log2_print_dest_space_after_flush`

[[basic_cstr_writer]]
== Class template `basic_cstr_writer`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class basic_cstr_writer final: public {destination}<CharT, {log2_garbage_buff_size}> {
public:
    basic_cstr_writer(CharT{asterisk} dest, CharT{asterisk} dest_end) noexcept;

    basic_cstr_writer(CharT{asterisk} dest, std::size_t len) noexcept;

    template <std::size_t N>
    basic_cstr_writer(CharT (&dest)[N]) noexcept;

    basic_cstr_writer(const basic_cstr_writer&) = delete;

    void recycle_buffer() noexcept override;

    struct result {
        CharT{asterisk} ptr;
        bool truncated;
    };

    result finish() noexcept;
};

} // namespace strf
----

=== Public member functions

====
[source,cpp]
----
basic_cstr_writer(CharT* dest, CharT* dest_end) noexcept;
----
[horizontal]
Precondition:: `dest < dest_end`
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest_end - 1`
====
====
[source,cpp]
----
basic_cstr_writer(CharT* dest, std::size_t dest_size) noexcept;
----
[horizontal]
Precondition:: `dest_size != 0`
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest + dest_size - 1`
====
====
[source,cpp]
----
template <std::size_t N>
basic_cstr_writer(CharT (&dest)[N]) noexcept;
----
[horizontal]
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest + N - 1`
====
====
[source,cpp]
----
void recycle_buffer() noexcept;
----
[horizontal]
Postconditions::
- `{good}() == false`
- `{buffer_ptr}() == {garbage_buff}<CharT>()`
- `{buffer_end}() == {garbage_buff_end}<CharT>()`
====
====
[source,cpp]
----
result finish() noexcept;
----
[horizontal]
Effects::
- Assign to `'\0'` the position after the last written character in memory area used to initialize this object and set this object into "bad" state.
Return value::
- `result::truncated` is `true` if `recycle_buffer` or `finish` has ever been called in this object.
- `result::ptr` points to the termination character `'\0'`.
Postconditions::
- `{good}() == false`
- `{buffer_ptr}() == {garbage_buff}<CharT>()`
- `{buffer_end}() == {garbage_buff_end}<CharT>()`
====

[[basic_char_array_writer]]
== Class template `basic_char_array_writer`

[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT>
class basic_char_array_writer final : public {destination}<CharT, {log2_garbage_buff_size}> {
public:
    template <std::size_t N>
    basic_char_array_writer(CharT (&dest)[N]) noexcept;
    basic_char_array_writer(CharT{asterisk} dest, CharT{asterisk} dest_end) noexcept;
    basic_char_array_writer(CharT{asterisk} dest, std::size_t dest_size) noexcept;
    basic_char_array_writer(const basic_char_array_writer&) noexcept;

    basic_char_array_writer& operator=(const basic_char_array_writer&) noexcept;
    bool operator==(const basic_char_array_writer&) noexcept;

    void recycle_buffer() noexcept override;

    struct result {
        CharT{asterisk} ptr;
        bool truncated;
    };

    result finish() noexcept;
};
} // namespace strf
----

=== Public member functions

====
[source,cpp]
----
template <std::size_t N>
basic_char_array_writer(CharT (&dest)[N]) noexcept;
----
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest + N`
====
====
[source,cpp]
----
basic_char_array_writer(CharT* dest, CharT* dest_end) noexcept;
----
[horizontal]
Precondition:: `dest < dest_end`
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest_end`
====
====
[source,cpp]
----
basic_char_array_writer(CharT* dest, std::size_t dest_size) noexcept;
----
[horizontal]
Precondition:: `dest_size != 0`
Postconditions::
- `{good}() == true`
- `{buffer_ptr}() == dest`
- `{buffer_end}() == dest + dest_size`
====
====
[source,cpp]
----
void recycle_buffer() noexcept;
----
[horizontal]
Postconditions::
- `{good}() == false`
- `{buffer_ptr}() == {garbage_buff}<CharT>()`
- `{buffer_end}() == {garbage_buff_end}<CharT>()`
====
====
[source,cpp]
----
result finish() noexcept;
----
Return value::
- `result.truncated` is `true` when `{recycle_buffer}()` or `{do_write}(...)`
   has been previously called in this object, which means that the
   the range which with it was initialized is too small.
- `result::ptr` is the one-past-the-end pointer of the characters written.
   However, when `result.truncated` is `true`, the number of characters written
   is unspecified.
====


[[discarded_destination]]
== Class template `discarded_destination`

`discarded_destination` it's the library's analogous to `/dev/null`.
A `discarded_destination` object ignores anything written to it.

[source,cpp]
----
namespace strf {

template <typename CharT>
class discarded_destination final: public destination<CharT, {log2_garbage_buff_size}>
{
public:
    discarded_destination() noexcept;
    void recycle_buffer() noexcept override;
};

} // namespace strf
----
====
[source,cpp]
----
discarded_destination() noexcept;
----
[horizontal]
Postconditions::
- `{good}() == false`
- `{buffer_ptr}() == {garbage_buff}<CharT>()`
- `{buffer_end}() == {garbage_buff_end}<CharT>()`
====
====
[source,cpp]
----
void recycle_buffer() noexcept;
----
[horizontal]
Postconditions::
- `{good}() == false`
- `{buffer_ptr}() == {garbage_buff}<CharT>()`
- `{buffer_end}() == {garbage_buff_end}<CharT>()`
====

[[garbage_buff]]
== Garbage buffer

These function templates return the begin and the end of a memory area that is never supposed to be read. It can be used when implementing a class that derives from `destination` to set the buffer when the state is "bad".

====
[source,cpp,subs=normal]
----
constexpr unsigned log2_garbage_buff_size = ...;
----
Implementation-defined type that is greater than or equal to
`<<print_dest,log2_print_dest_space_after_flush>>`;
====

====
[source,cpp]
----
constexpr std::size_t garbage_buff_size = (std::size_t)1 << log2_garbage_buff_size;
----
====

====
[source,cpp]
----
template <typename CharT>
CharT* garbage_buff() noexcept;
----
Returns the begin a memory area of `garbage_buff_size` elements that are never supposed to be read.
====

====
[source,cpp]
----
template <typename CharT>
CharT* garbage_buff_end() noexcept;
----
Returns `garbage_buff() + garbage_buff_size`
====

