////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:strf-revision: develop
:strf-src-root: https://github.com/robhz786/strf/blob/{strf-revision}

= How to add a new destination
:source-highlighter: prettify
:icons: font

:output_buffer: <<destination_hpp#output_buffer,output_buffer>>
:destination: <<destination_hpp#destination,destination>>
:recycle: <<destination_hpp#output_buffer_recycle,recycle>>
:flush: <<destination_hpp#output_buffer_flush,flush>>
:good: <<destination_hpp#output_buffer_good,good>>
:buffer_ptr: <<destination_hpp#output_buffer_buffer_ptr,buffer_ptr>>
:buffer_space: <<destination_hpp#output_buffer_buffer_space,buffer_space>>
:set_good: <<destination_hpp#output_buffer_set_good,set_good>>
:set_buffer_ptr: <<destination_hpp#output_buffer_set_buffer_ptr,set_buffer_ptr>>
:to: <<quick_reference#to_destination_ref,to>>

:printing_syntax: <<strf_hpp#printing_syntax,printing_syntax>>
:DestinationCreator: <<strf_hpp#DestinationCreator,DestinationCreator>>
:SizedDestinationCreator: <<strf_hpp#SizedDestinationCreator,SizedDestinationCreator>>
:destination_space_after_flush: <<destination_hpp#destination,destination_space_after_flush>>

== The `destination` class template

Creating a new output type involves defining a concrete class
that derives from `{destination}`.
Having done that, one can write things to objects
of such type with the `{to}` function template,
using the basic usage `<<tutorial#,syntax>>` of the library:

[source,cpp,subs=normal]
----
strf::destination</{asterisk}char type{asterisk}/>& dst = /{asterisk}\...{asterisk}/;
strf::<<quick_reference#to_destination_ref,to>>(dst) (/{asterisk} arguments to be printed {asterisk}/);
----

But before learning how to implement such class,
it makes sense to first undestand how one uses the
`{destination}` interface, __i.e.__, how to write things
to it.
`destination` is a simple class template: it
contains a boolean &#x2014; which indicates whether
the state is "good" or "bad" &#x2014; and two pointers; one of them points
to the end of buffer, and the other to the position where the
next character shall be written. They are returned by the
`<<destination_hpp#output_buffer_buffer_end,buffer_end>>` and
`<<destination_hpp#output_buffer_buffer_ptr,buffer_ptr>>` functions respectively.
Contrary to what is common in output streams abstractions,
where you need to use high-level functions to insert content ( like
https://en.cppreference.com/w/cpp/io/basic_streambuf/sputc[`sputc`]
in `std::basic_streambuf`, or
https://en.cppreference.com/w/cpp/io/basic_ostream/write[`write`]
in `std::basic_ostream` ), in `{destination}`, one can write things directly to
its buffer.

[source,cpp,subs=normal]
----
if (dst.{buffer_space}() < 5) {
    dst.recycle();
}
memcpy(dst.buffer_ptr(), "hello", 5);
dst.advance(5);
----

As demonstrated above, before writting anything to `buffer_ptr()`, one
must check whether there is enough space,
and if not, one must call the `{recycle}` function
( or `{flush}`, which calls `recycle` ).
This is the only pure virtual function in `{destination}`;
its job is to flush the content written so far and reset the position of
`buffer_ptr()` and `buffer_end()`. After `{recycle}` is called,
the buffer's space ( `buffer_end() - buffer_ptr()` ) is
guaranteed to be at least `{destination_space_after_flush}`
( which is currently `64` but may be greater in future versions ).
This is a postcondition even when the state is "bad".
The state may change from "good" to "bad" in `{recycle}`,
but never from "bad" to "good".
The "bad" state implies that writting
anything in the range [`buffer_ptr(), buffer_end()`) has no relevent
side effect, though the behaviour is still defined, __i.e.__
the range must be a valid accessible memory area.
Sometimes, `<<destination_hpp#garbage_buff,garbage_buff>>`
is used to handle the bad state.

// This means it's not necessary to always check the state before
// writting anything to `buffer_ptr()`. At worse, it is waste
// of CPU resource.


After writing to `buffer_ptr()`, it is necessary to advance
the buffer pointer, otherwise the content will be overwritten
next time something is written in `buffer_ptr()`.
This is can be done with the
`<<destination_hpp#output_buffer_advance,advance>>`
or the `<<destination_hpp#output_buffer_advance_to,advance_to>>`
member function, as shown above.

Now, we can see how a typical implementation would look like:

[source,cpp,subs=normal]
----
class my_destination: public strf::destination<char> {
public:
    my_destination(/{asterisk}\...{asterisk}/)
        : strf::destination<char>{buff, sizeof(buff)}
        // \...
    {
        /{asterisk}\...{asterisk}/
    }

    my_destination(const my_destination&) = delete;
    ~my_destination();

    void recycle() override;
    void finish();

private:
    bool print(const char* str_begin, const char* str_end)
    { /{asterisk}\...{asterisk}/ }

    char buff[strf::{destination_space_after_flush}];
};
----

The `print` member function above represents the code
that would send the content to the actual destination,
whatever it is. If `print` never throws, then
`recycle` could be implemented like below:

[source,cpp,subs=normal]
----
void my_destination::recycle()
{
    if ({good}()) {
        bool success = print(buff, {buffer_ptr}());
        {set_good}(success);
    }
    {set_buffer_ptr}(buff);
}
----

Otherwise, it makes more sense to do:

[source,cpp,subs=normal]
----
void my_destination::recycle()
{
    auto ptr = {buffer_ptr}();
    {set_buffer_ptr}(buff);
    if ({good}()) {
        {set_good}(false);
        bool success = print(buff, ptr);
        {set_good}(success);
    }
}
----

You may want to define a destructor that prints
what is left in the buffer. The issue here is that if `print` throws
we must not propagate the exception ( since
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-dtor-fail[destructors must not throw] ).

[source,cpp,subs=normal]
----
my_destination::~my_destination()
{
    if({good}()) {
        try {
            print(buff, {buffer_ptr}());
        } catch(...)
        {
        } // Need to silence the exception. Not good
    }
}
----

That's why it might be a good idea to create a member function
to do this final flush:

[source,cpp,subs=normal]
----
void my_destination::finish()
{
    bool is_good = {good}();
    {set_good}(false);
    if (is_good) {
        print(buff, ({buffer_ptr}() - buff));
    }
}
----

`finish()` is supposed to be called after all content is written:

[source,cpp,subs=normal]
----
my_destination dst{ /{asterisk}\...{asterisk}/ };

strf::{to}(dst) (/{asterisk}\...{asterisk}/);
strf::{to}(dst) (/{asterisk}\...{asterisk}/);
some_function(dst);
strf::{to}(dst) (/{asterisk}\...{asterisk}/);

dst.finish();
----
Almost
<<quick_reference#destination_types,all destination classes of this library>>
have a `finish` function ( the only exception is
<<destination_hpp#discarder,discarder>>.
So you may want to follow the convention.
Another reason for creating `finish` is that may return a value,
which is something that destructors can't do.


////
`{set_good}` and `{set_buffer_ptr}` are protected member functions.
////

== How to create a __target__ expression [[create_target]]

There are <<quick_reference#targets,several expressions>> that can be used as
the prefix in the `<<tutorial#,basic usage syntax>>`.
Each of them causes the content to be printed into a different destination.
Perhaps you want to create your own. For example, if you use Qt,
you may want to create a `toQString` "destination",
intended to create a `QString` object ( in the same way as
`<<quick_reference#targets,to_string>>` creates
`std::string` objects ).
This section explains how you can do that.

The first step, which involves most of the work, is
to create a class that derives from `{destination}`,
which is covered in previous section.
Sometimes it makes sense to actually create two of them;
one having a constructor that receives the size
while the other does not, as explained soon.

The second step is to create a class that satisfies the requirements of
__{DestinationCreator}__ or __{SizedDestinationCreator}__ or both.
It acts as a factory ( or something analogous to that ) of the class(es)
you defined in step 1.
_SizedDestinationCreator_ is for the case when the constructor
of your destination class requires the number of characters to be printed
( because it needs to allocate memory or something ).
_DestinationCreator_ is for when it does not need that information.

The third and final step is to define the "target expression".
It must be an expression ( a function call or a constexpr value )
whose type is an instance of one the `{printing_syntax}` class template.

The sample below illustrates the above steps:

[source,cpp,subs=normal]
----
// some type that is able to receive text
class foo { /{asterisk} \... {asterisk}/ };

// step 1: define your {destination} class
class foo_writer: strf::destination<char> {
public:
    explicit foo_writer(foo&);
    foo_writer(const foo_writer&) = delete;

    void recycle() override;

    auto finish() \-> /{asterisk} \... {asterisk}/;
    //\...
};

// step 2: define the destination creator
class foo_writer_creator {
public:
    using destination_type = foo_writer;
    using char_type = char;

    foo_writer_creator(foo& f): f_(f) {}
    foo_writer_creator(const foo_writer_creator&) = default;

    foo& create() const { return f_; }

private:
    foo& f_;
}

// step3: define the expression that creates a printing_syntax object
auto to(foo& dst) {
    strf::{printing_syntax}<foo_writer_creator> x{dst};
    // x contains a member object of type foo_writer_creator
    // initialized with dst
    return x;
}
----

== Examples

* {strf-src-root}/examples/toQString.cpp[examples/toQString.cpp] defines a
  constexpr value named `toQSting`
  that is analogous to `<<quick_reference#targets,strf::to_string>>`, except that
  it creates a `QString` ( from Qt framework ) instead of a `std::string`.
* {strf-src-root}/examples/appendQString.cpp[examples/appendQString.cpp] defines
  a function `append` used to append content into a `QString` object

