////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

= The Strf formatting library - Quit Reference
:source-highlighter: prettify
:sectnums:
:sectnumlevels: 0
:toc: left
:toclevels: 2
:icons: font


:destination:     <<destination_hpp#destination,destination>>
:numpunct_c:     <<strf_hpp#numpunct_c,numpunct_c>>
:numpunct:       <<strf_hpp#numpunct,numpunct>>
:width_t:        <<strf_hpp#width_t,width_t>>
:float_notation: <<float_notation,float_notation>>


[[format_functions]]
== Format Functions

The expression `fmt(_arg_)` returns a printable object that contains a copy or reference of
`arg` as well as format information that can be edited with the
member functions like `sci` and `fill`:

.Example
[source,cpp]
----
auto str = strf::to_string( +*strf::fmt(1.0).sci().fill(U'~') ^ 15 );
assert(str == "~~~~+1.e+01~~~~")
----

These member functions are called in this library as __format functions__.

There are also some global function templates
that work as alias to format functions:

[%header,cols="22,25",grid=rows]
|===
| Expression | Equivalent Expression
|`left(_arg_, _width_)`        |`fmt(_arg_) < _width_`
|`right(_arg_, _width_)`       |`fmt(_arg_) > _width_`
|`center(_arg_, _width_)`      |`fmt(_arg_) ^ _width_`
|`left(_arg_, _width_, _ch_)`  |`fmt(_arg_).fill(_ch_) < _width_`
|`right(_arg_, _width_, _ch_)` |`fmt(_arg_).fill(_ch_) > _width_`
|`center(_arg_, _width_, _ch_)`|`fmt(_arg_).fill(_ch_) ^ _width_`
|`pad0(_arg_, _width_)`        |`fmt(_arg_).pad0(_width_)`
|`punct(_arg_)`                |`fmt(_arg_).punct()`
|`bin(_arg_)`                  |`fmt(_arg_).bin()`
|`dec(_arg_)`                  |`fmt(_arg_).oct()`
|`oct(_arg_)`                  |`fmt(_arg_).dec()`
|`hex(_arg_)`                  |`fmt(_arg_).hex()`
|`sci(_arg_)`                  |`fmt(_arg_).sic()`
|`fixed(_arg_)`                |`fmt(_arg_).fixed()`
|`gen(_arg_)`                  |`fmt(_arg_).gen()`
|`sci(_arg_, _precision_)`     |`fmt(_arg_).sic().p(_precision_)`
|`fixed(_arg_, _precision_)`   |`fmt(_arg_).fixed().p(_precision_)`
|`gen(_arg_, _precision_)`     |`fmt(_arg_).gen().p(_precision_)`
|`multi(_arg_, _count_)`       |`fmt(_arg_).multi(_count_)`
|`sani(_arg_, _charset_)`      |`fmt(_arg_).sani(_charset_)`
|`conv(_arg_, _charset_)`      |`fmt(_arg_).conv(_charset_)`
|`sani(_arg_)`                 |`fmt(_arg_).sani()`
|`conv(_arg_)`                 |`fmt(_arg_).cont()`
|===

.Example
[source,cpp]
----
auto str = strf::to_string( +*strf::center(1.0, 9, U'~') );
assert(str == "~~~+1.~~~")
----

[[alignment_format_functions]]
=== Alignment formatting

include::ref_format_functions.adoc[tag=alignment_format_functions]

=== Floating-point formatting

include::ref_format_functions.adoc[tag=float_format_functions]

[[float_notation]]
include::ref_format_functions.adoc[tag=float_notation]


====
NOTE: `pad0` is independent of alignment formatting:
[source,cpp]
----
auto s = strf::to_string(strf::center(-1.25, 12, '_').pad0(8));
assert(s == "__-0001.25__");

auto nan = std::numeric_limits<double>::quiet_NaN();

s = strf::to_string(strf::center(-nan, 12, '_').pad0(8));
assert(s == "____-nan____");

s = strf::to_string(strf::center(-nan, 8, '_').pad0(12));
assert(s == "____-nan____");
----
====

=== Integer formatting

include::ref_format_functions.adoc[tag=int_format_functions]

=== Char formatting
[[multi]]
[%header,cols="382,618",grid=rows]
|===
| Member function | Effect
|`multi(std::size_t count)`
| Prints the argument `count` times.
|===

[[string_formatting]]
=== String formatting
[%header,cols="382,618",grid=rows]
|===
| Member function | Effect
|`p(<<strf_hpp#width_t,width_t>> precision)`
| Sets string precision

| `template <typename Charset> sani(Charset cs)`
| Equivalent to `sanitize_from_charset(cs)`

| `template <typename Charset> conv(Charset cs)`
| Equivalent to `convert_from_charset(cs)`

| `conv()`
| Equivalent to `convert_from_charset()`

| `sani()`
| Equivalent to `sanitize_from_charset()`

| `template <typename Charset> convert_from_charset(Charset cs)`
| Transcodes the input string from the charset represented by `cs`,
  if it is not already destination charset.

| `template <typename Charset> sanitize_from_charset(Charset cs)`
| Transcodes the input string from the charset represented by `cs`,
  or just sanitizes it, if `cs` is also the destination charset.

| `convert_charset()`
| Transcodes the input string from the charset that correspods
  to its character type, if it is not already the same
  as the destination charset.

| `sanitize_charset()`
| Transcodes the input string from the charset that corresponds
  to its character type, or just sanitizes it, if it same
  as the destination charset.

|===


== Destinations [[destinations]]

[%header,cols="10,4"]
|===
| Expression |Header

|`<<to_destination_ref,to>> (__destination_ref__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_raw_string,to>> (__char_ptr__, __end__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_raw_string,to>> (__char_ptr__, __count__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_raw_string,to>> (__char_array__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_char_range,to_range>> (__char_ptr__, __end__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_char_range,to_range>> (__char_ptr__, __count__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_char_range,to_range>> (__char_array__)`
| `<<strf_hpp#,<strf.hpp> >>`

|`<<dest_to_basic_string,to_basic_string>> <__CharT__, _Traits_~_opt_~, _A_~_opt_~>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_to_string,to_string>>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_to_u8string,to_u8string>>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_to_u16string,to_u16string>>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_to_u32string,to_u16string>>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_to_wstring,to_wstring>>`
| `<<to_string_hpp#,<strf/to_string.hpp> >>`

|`<<dest_streambuf,to>> (__streambuf_ptr__)`
| `<<to_streambuf_hpp#,<strf/to_streambuf.hpp> >>`

|`<<dest_streambuf,to>> (__streambuf_ref__)`
| `<<to_streambuf_hpp#,<strf/to_streambuf.hpp> >>`

|`<<dest_cfile,to>> <__CharT__~_opt_~> (__cfile__)`
| `<<to_cfile_hpp#,<strf/to_cfile.hpp> >>`

|`<<dest_wcfile,wto>> (__cfile__)`
| `<<to_cfile_hpp#,<strf/to_cfile.hpp> >>`
|===
where:

* `__CharT__` is a charater type.
* `_Traits_` is a https://en.cppreference.com/w/cpp/named_req/CharTraits[_CharTraits_] type.
* `_A_` is an https://en.cppreference.com/w/cpp/named_req/Allocator[_Allocator_] type
* `__char_ptr__` is a `__CharT__*` value, where `__CharT__` is a character type.
* `__end__` is a `__CharT__*` value, where `__CharT__` is a character type.
* `__count__` is a `std::size_t` value
* `__streambuf_ptr__` is a `std::streambuf<__CharT__, _Traits_>*`
* `__streambuf_ref__` is a `std::streambuf<__CharT__, _Traits_>&`
* `__cfile__` is a `FILE*`
* `__destination_ref__` is a `{destination}<__CharT__>&`,  where `__CharT__` is a character type.
* `__args\...__` is an argument list of printable values.

[[to_destination_ref]]
====
[subs=normal]
----
strf::to(__destination_ref__) (__args\...__)
----
[horizontal]
Return type:: `void`
Supports reserve:: No

See the <<destination_types,list of types>> that derive from `{destination}<__CharT__>&`.
====

[[dest_raw_string]]
====
[subs=normal]
----
strf::<<strf_hpp#to_char_ptr_range,to>>(__char_ptr__, __end__)   (__args\...__);
strf::<<strf_hpp#to_char_array,to>>(__char_array__)      (__args\...__);
strf::<<strf_hpp#to_char_ptr_count,to>>(__char_ptr__, __count__) (__args\...__);
----
[horizontal]
Header file:: `<<strf_hpp#,<strf.hpp> >>`
Preconditions::
* `__count__ > 0`
* `__end__ > __char_ptr__`
//-
Return type:: `<<destination_hpp#basic_cstr_destination,basic_cstr_destination<__CharT__>::result`>>
Return value:: a value `r`, such that:
* `r.ptr` points to last written character which is always `'\0'`.
* `r.truncated` is `true` when the destination string is too small. In this case, the number of
   characters written is unspecified, but it is always greater than zero ( because `'\0'` is always written )
Note:: The termination character `'\0'` is always written.
Supports reserve:: No

////
[source,cpp,subs=normal]
----
namespace strf {

/{asterisk}\...{asterisk}/ to(char*     dest, std::size_t count);
/{asterisk}\...{asterisk}/ to(char8_t*  dest, std::size_t count);
/{asterisk}\...{asterisk}/ to(char16_t* dest, std::size_t count);
/{asterisk}\...{asterisk}/ to(char32_t* dest, std::size_t count);
/{asterisk}\...{asterisk}/ to(wchar_t*  dest, std::size_t count);

/{asterisk}\...{asterisk}/ to(char*     dest, char*     dest_end);
/{asterisk}\...{asterisk}/ to(char8_t*  dest, char8_t*  dest_end);
/{asterisk}\...{asterisk}/ to(char16_t* dest, char16_t* dest_end);
/{asterisk}\...{asterisk}/ to(char32_t* dest, char32_t* dest_end);
/{asterisk}\...{asterisk}/ to(wchar_t*  dest, wchar_t*  dest_end);

template<std::size_t N> /{asterisk}\...{asterisk}/ to(char     (&dest)[N]);
template<std::size_t N> /{asterisk}\...{asterisk}/ to(char8_t  (&dest)[N]);
template<std::size_t N> /{asterisk}\...{asterisk}/ to(char16_t (&dest)[N]);
template<std::size_t N> /{asterisk}\...{asterisk}/ to(char32_t (&dest)[N]);
template<std::size_t N> /{asterisk}\...{asterisk}/ to(wchar_t  (&dest)[N]);
}
----
////

====

[[dest_char_range]]
====
[subs=normal]
----
strf::<<strf_hpp#to_range,to_range>>(__char_ptr__, __end__)   (__args\...__);
strf::<<strf_hpp#to_range_array,to_range>>(__char_array__)      (__args\...__);
strf::<<strf_hpp#to_range_count,to_range>>(__char_ptr__, __count__) (__args\...__);
----
Header file:: `<<strf_hpp#,<strf.hpp> >>`
Preconditions::
* `__end__ >= __char_ptr__`
//-
Return type:: `<<destination_hpp#array_destination,array_destination<__CharT__>::result`>>
Return value:: a value `r`, such that:
* `r.ptr` is the one-past-the-end pointer of the characters written.
* `r.truncated` is `true` when the destination is too small. In this case, the number of
   characters written is unspecified.
Note:: The termination character `'\0'` is **not** appended to the content.
Supports reserve:: No
====


[[dest_to_basic_string]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_basic_string>> <__CharT__, _Traits_~_opt_~, _A_~_opt_~> ( __args\...__ )
----
[horizontal]
Return type:: `std::basic_string<__CharT__, _Traits_, _A_>`
Supports reserve:: Yes
====

[[dest_to_string]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_string>> ( __args\...__ )
----
[horizontal]
Return type:: `std::string`
Supports reserve:: Yes
====

[[dest_to_u8string]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_u8string>> ( __args\...__ )
----
[horizontal]
Return type:: `std::u8string`
Supports reserve:: Yes
====

[[dest_to_u16string]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_u16string>> ( __args\...__ )
----
[horizontal]
Return type:: `std::u16string`
Supports reserve:: Yes
====

[[dest_to_u32string]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_u32string>> ( __args\...__ )
----
[horizontal]
Return type:: `std::u32string`
Supports reserve:: Yes
====

[[dest_to_wstring]]
====
[subs=normal]
----
strf::<<to_string_hpp#to_basic_string,to_wstring>> ( __args\...__ )
----
[horizontal]
Return type:: `std::wstring`
Supports reserve:: Yes
====

[[dest_streambuf]]
====
[subs=normal]
----
<<to_streambuf_hpp#to,to>>(__streambuf_ptr__)  (__args\...__);
<<to_streambuf_hpp#to,to>>(__streambuf_ref__)  (__args\...__);
----
[horizontal]
Return type:: `<<to_streambuf_hpp#basic_streambuf_writer,basic_streambuf_writer<__CharT__, _Traits_>::result>>`
Return value:: A value `r`, such that:
* `r.count` is equal to the number of successfully written characters.
* `r.success` is `false` if an error occurred
Supports reserve:: No

====

[[dest_cfile]]
====
[subs=normal]
----
<<to_cfile_hpp#to,to>><__CharT__~_opt_~>(__cfile__) (__args\...__)
----
Effect:: Successively call `std::fwrite(buffer, sizeof(__CharT__),/{asterisk}\...{asterisk}/, __cfile__)` until the whole content is written or until an error happens, where `buffer` is an internal array of `__CharT__`.
[horizontal]
Return type:: `<<to_cfile_hpp#narrow_cfile_writer,narrow_cfile_writer<__CharT__>::result>>`
Return value::
- `count` is sum of the returned values returned by the several calls to `std::fwrite`.
- `success` is `false` if an error occured.
Supports reserve:: No
====

[[dest_wcfile]]
====
[subs=normal]
----
<<to_cfile_hpp#wto,wto>>(__cfile__) (__args\...__)
----
[horizontal]
Header file:: `<<to_cfile_hpp#,<strf/to_cfile.hpp> >>`
Return type:: `<<to_cfile_hpp#wide_cfile_writer,wide_cfile_writer<__CharT__>::result>>`
====

[[destination_types]]
=== `destination` classes

The table below lists the concrete types that derivate from the `{destination}<__CharT__>` abstract class.

[%header,cols="47,53"]
|===
| Type | Description

| `<<destination_hpp#basic_cstr_destination, basic_cstr_destination>><__CharT__>`
| Writes C strings. Always writes the termination character `'\0'`.

| `<<destination_hpp#array_destination, array_destination>><__CharT__>`
| Writes to also `char*`, but does not append the termination character `'\0'`

| `<<destination_hpp#discarder,discarder>><__CharT__>`
| Discards the content. The analogous of `/dev/null`.

| `<<to_string_hpp#basic_string_appender,basic_string_appender>><__CharT__, _Traits_~_opt_~, _A_~_opt_~>`
| Appends to `std::basic_string` objects.

| `<<to_string_hpp#basic_string_maker,basic_string_maker>><__CharT__, _Traits_~_opt_~, _A_~_opt_~>`
| Creates `std::basic_string` objects.

| `<<to_string_hpp#basic_sized_string_maker, basic_sized_string_maker>><__CharT__, _Traits_~_opt_~, _A_~_opt_~>`
| Creates `std::basic_string` objects with pre-reserved capacity

| `<<to_streambuf_hpp#basic_streambuf_writer,basic_streambuf_writer>><__CharT__, _Traits_~_opt_~>`
| Writes to `std::basic_streambuf` object

| `<<to_cfile_hpp#narrow_cfile_writer,narrow_cfile_writer>><__CharT__~_opt_~>`
| Writes to `FILE*` using narrow-oriented functions.

| `<<to_cfile_hpp#wide_cfile_writer,wide_cfile_writer>>`
| Writes to `FILE*` using wide-oriented functions.
|===

where:

* `__CharT__` is a charater type.
* `__Traits__` is a https://en.cppreference.com/w/cpp/named_req/CharTraits[_CharTraits_] type.
* `__A__` is an https://en.cppreference.com/w/cpp/named_req/Allocator[_Allocator_] type

////

====
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT> class basic_cstr_destination;

using u8cstr_destination  = basic_cstr_destination<char8_t>;
using cstr_destination    = basic_cstr_destination<char>;
using u16cstr_destination = basic_cstr_destination<char16_t>;
using u32cstr_destination = basic_cstr_destination<char32_t>;
using wcstr_destination   = basic_cstr_destination<wchar_t>;

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT> class discarder;

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

template < typename CharT
         , typename Traits = std::char_traits<CharT>
         , typename Allocator = std::allocator<CharT> >
class basic_string_appender;

using string_appender    = basic_string_appender<char>;
using u8string_appender  = basic_string_appender<char8_t>;
using u16string_appender = basic_string_appender<char16_t>;
using u32string_appender = basic_string_appender<char32_t>;
using wstring_appender   = basic_string_appender<wchar_t>;

} // namespace strf
----
====
====
[source,cpp,subs=normal]
----
namespace strf {

template < typename CharT
         , typename Traits = std::char_traits<CharT>
         , typename Allocator = std::allocator<CharT> >
class basic_string_maker;

using string_maker    = basic_string_maker<char>;
using u8string_maker  = basic_string_maker<char8_t>;
using u16string_maker = basic_string_maker<char16_t>;
using u32string_maker = basic_string_maker<char32_t>;
using wstring_maker   = basic_string_maker<wchar_t>;

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

template < typename CharT
         , typename Traits = std::char_traits<CharT>
         , typename Allocator = std::allocator<CharT> >
class basic_sized_string_maker

using sized_string_maker    = basic_sized_string_maker<char>;
using sized_u8string_maker  = basic_sized_string_maker<char8_t>;
using sized_u16string_maker = basic_sized_string_maker<char16_t>;
using sized_u32string_maker = basic_sized_string_maker<char32_t>;
using sized_wstring_maker   = basic_sized_string_maker<wchar_t>;

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, typename Traits = std::char_traits<CharT> >
class basic_streambuf_writer

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
class narrow_cfile_writer;

} // namespace strf
----
====

====
[source,cpp,subs=normal]
----
namespace strf {

class wide_cfile_writer;

} // namespace strf
----
====

////

[[tr_string]]
== Tr-string

[source,cpp]
----
auto s = strf::to_string.tr("{} in hexadecimal is {}", x, strf::hex(x));
----

The __tr-string__ is like what in other formatting
libraries would be called as the __format string__,
except that it does not specify any formatting.
Its purpose is to enable your program to provide multilingual support
by using translation tools like https://en.wikipedia.org/wiki/Gettext[gettext].

Since it is common for the person who writes the string to be translated
not being the same who translates it, the tr-string syntax allows
the insertion of comments.

.Syntax
[%header,cols=3*]
|===
|A `'{'` followed by  |until                           |means
|`'-'`                |the next `'}'` or end of string |a comment
|another `'{'`        |the second `'{'`                |an escaped `'{'`
|a digit              |the next `'}'` or end of string |a positional argument reference
|any other character  |the next `'}'` or end of string |a non positional argument reference
|===

Comments::
+
[source,cpp]
----
auto str = strf::to_string.tr
    ( "You can learn more about python{-the programming language, not the animal species} at {}"
    , "www.python.org" );
assert(str == "You can learn more about python at www.python.org");
----

Escapes::
Note there is no way and no need to escape the `'}'` character, since it has special meaning only when corresponding to a previous `'{'
+
[source,cpp]
----
auto str = strf::to_string.tr("} {{x} {{{} {{{}}", "aaa", "bbb");
assert(str == "} {x} {aaa {bbb}");
----

Positional arguments::
Position zero refers to the first input argument. The characters the after the digits are ignored. So they can also be used as comments.
+
[source,cpp]
----
auto str = strf::to_string.tr("{1 a person name} likes {0 a food name}.", "sandwich", "Paul");
assert(str == "Paul likes sandwich.");
----

Non positional arguments::
The characters the after the `'{'` are ignored as well
+
[source,cpp]
----
auto str = strf::to_string.tr("{a person} likes {a food type}.", "Paul", "sandwich");
assert(str == "Paul likes sandwich.");
----

[[tr_string_error]]
=== Tr-string error handling

When the argument associated with a `"{"` does not exists, the library does two things:

- It prints a https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character[replacement character `"\uFFFD"` (&#65533;) ] ( or `"?"` when the charset can't represent it ) where the missing argument would be printed.
- It calls the `handle` function on the facet object correspoding to the `<<strf_hpp#tr_error_notifier_c,tr_error_notifier_c>>` category, which, by default, does nothing.

[[facets]]
== Facet Categories

[%header,cols="2,1,4"]
|===
|Category |Constrainable | Description

|`<<numpunct, numpunct_c>><10>`      |Yes |Numeric punctuation for decimal base
|`<<numpunct, numpunct_c>><16>`      |Yes |Numeric punctuation for hexadecimal base
|`<<numpunct, numpunct_c>><8>`       |Yes |Numeric punctuation for octal base
|`<<numpunct, numpunct_c>><2>`       |Yes |Numeric punctuation for binary base

|`<<lettercase,lettercase_c>>`        |Yes |Letter case for printing numeric and booleans values

|`<<charset,charset_c>><CharT>`   |No  |The character encoding correponding to character type `CharT`
|`<<invalid_seq_notifier,invalid_seq_notifier_c>>`  |Yes | Callback to notify nonconformities to the character encoding.
|`<<surrogate_policy,surrogate_policy_c>>` |Yes |Wheter surrogates are treated as errors
|`<<tr_string_error,tr_error_notifier_c>>`   |No  |  Callback to notify errors on the tr-string
|`<<width_calculator,width_calculator_c>>` |Yes |Defines how the width is calculated
|`<<howto_override_printable_types#,print_override_c>>`     |Yes   | Overrides printable types
|===

[[numpunct]]
== Numeric punctuation

To apply numeric punctuation in integers and floating-point
arguments you need to invoke the `punct` or `operator!`
format function. You also need to pass a `numpunct` facet
object to specify the "thousands" separator,
the decimal point and the grouping pattern.
The integer sequence passed to the constructor of `numpunct` defines the grouping.
The last value is repeated, unless it is equal to `-1`.

[source,cpp]
----
auto s1 = strf::to_string.with(strf::numpunct<10>(1, 2, 3))(strf::punct(1000000000000ll));
assert(s1 == "1,000,000,000,00,0");

auto s2 = strf::to_string.with(strf::numpunct<10>(1, 2, 3, -1))(!strf::dec(1000000000000ll));
assert(s2 == "1000000,000,00,0");
----
The constructor of `numpunct` has some preconditions:

* No more than six arguments can be passed.
* No argument can be greater than 30.
* No argument can be less than `1`, unless it is the last argument and it's equal to `-1`.

When default constructed, the `numpunct` has no grouping, __i.e.__
the thousands separator is never printed.

The default thousands separator and decimal point are `U','` and `U'.'`,
repectively. To change them, use the `thousands_sep` and `decimal_point`
member functions:
[source,cpp]
----
auto my_punct = numpunct<10>{3} .thousands_sep(U'\'') .decimal_point(U':');
auto str = strf::to_string.with(my_punct) (strf::punct(1000000.5));
assert(str == "1'000'000:5");

//or as lvalue:
auto my_punct2 = numpunct<10>(3);
my_punct2.thousands_sep(U';');
my_punct2.decimal_point(U'^');

auto str = strf::to_string.with(my_punct2) (strf::punct(1000000.5));
assert(str == "1;000;000^5");
----

=== Numeric punctuation from locale

The header file `<strf/locale.hpp>` declares the `locale_numpunct` function,
which returns a `numpunct<10>` object that reflects the current locale:

[source,cpp,subs=normal]
----
#include <strf/locale.hpp>
#include <strf/to_string.hpp>

void sample() {
    if (setlocale(LC_NUMERIC, "de_DE")) {
        const auto punct_de = strf::locale_numpunct();
        auto str = strf::to_string.with(punct_de) (*!strf::fixed(10000.5))
        assert(str == "10.000,5");
    }
}
----


[[lettercase]]
== Letter case

The `<<strf_hpp#lettercase,lettercase>>` facet affects the letter case
when printing numeric values.
The default value is `strf::lowercase`.

[source,cpp]
----
namespace strf {

enum class lettercase { lower = /*...*/, mixed = /*...*/, upper = /*...*/ };

constexpr lettercase lowercase = lettercase::lower;
constexpr lettercase mixedcase = lettercase::mixed;
constexpr lettercase uppercase = lettercase::upper;

}
----

.Printed numeric values examples
[%header,cols="1,2"]
|===
|Value | Result examples

|`strf::lowercase`
|`0xab` `1e+50` `inf` `nan` `true` `false`

|`strf::mixedcase`
|`0xAB` `1e+50` `Inf` `NaN` `True` `False`

|`strf::uppercase`
|`0XAB` `1E+50` `INF` `NAN` `TRUE` `FALSE`
|===

.Usage example
[source,cpp]
----
auto str_upper = strf::to_string.with(strf::uppercase)
    ( *strf::hex(0xabc), ' '
    , 1.0e+50, ' '
    , std::numeric_limits<FloatT>::infinity() );

assert(str_upper == "0XAB 1E+50 INF");

auto str_mixed = strf::to_string.with(strf::mixedcase)
    ( *strf::hex(0xabc), ' '
    , 1.e+50, ' '
    , std::numeric_limits<FloatT>::infinity() );

assert(str_mixed == "0xAB 1e+50 Inf");
----

[[charset]]
== Character encodings

The following variables templates can be used as facet objects
that specify what is the character encoding associated to
the character type passed as the template parameter.

[[static_charsets]]
[source,cpp]
----
namespace strf {

template <typename CharT> constexpr ascii_t<CharT>       ascii {};

template <typename CharT> constexpr iso_8859_1_t<CharT>  iso_8859_1 {};
template <typename CharT> constexpr iso_8859_2_t<CharT>  iso_8859_2 {};
// ... up to iso_8859_16

template <typename CharT> constexpr windows_1250_t<CharT>  windows_1250 {};
template <typename CharT> constexpr windows_1251_t<CharT>  windows_1251 {};
// ... up to windows_1258

template <typename CharT> constexpr utf8_t<CharT>   utf8 {};
template <typename CharT> constexpr utf16_t<CharT>  utf16 {};
template <typename CharT> constexpr utf32_t<CharT>  utf32 {};

template <typename CharT> constexpr utf_t<CharT> utf {}

} // namespace strf
----

.Example: write in Windows-1252
[source,cpp]
----
auto s = strf::to_string
    .with(strf::windows_1252<char>)
    .with(strf::numpunct<10>{4, 3, 2}.thousands_sep(0x2022))
    ("one hundred billions = ", 100000000000ll);

// The character U+2022 is encoded as '\225' in Windows-1252
assert(s == "one hundred billions = 1\2250000\225000\2250000");
----

[[charset_conversion]]
=== Charset conversion

Since the library knows the encoding correspondig to each
character type, and knows how to convert from one to another,
it is possible to mix input string of difference characters
types, though you need to use the function `conv`:

[source,cpp]
----
auto str   = strf::to_string( "aaa-"
                            , strf::conv(u"bbb-")
                            , strf::conv(U"ccc-")
                            , strf::conv(L"ddd") );

auto str16 = strf::to_u16string( strf::conv("aaa-")
                               , u"bbb-"
                               , strf::conv(U"ccc-")
                               , strf::conv(L"ddd") );

assert(str   ==  "aaa-bbb-ccc-ddd");
assert(str16 == u"aaa-bbb-ccc-ddd");
----

The `conv` function can also specify an alternative encoding
for a specific input string argument:

[source,cpp]
----
auto str_utf8 = strf::to_u8string
    ( strf::conv("--\xA4--", strf::iso_8859_1<char>)
    , strf::conv("--\xA4--", strf::iso_8859_15<char>));

assert(str_utf8 == u8"--\u00A4----\u20AC--");
----

The `sani` function has the same effect as `conv`,
except when the input encoding is same as the output.
In this case `sani` causes the input to be sanitized, whereas `conv` does not:

[source, cpp]
----
auto str = strf::to_string
    .with(strf::iso_8859_3<char>)    // the output charset
    ( strf::conv("--\xff--")                           // not sanitized
    , strf::conv("--\xff--", strf::iso_8859_3<char>)   // not sanitized ( same charset )
    , strf::conv("--\xff--", strf::utf8<char>)         // sanitized ( different charset )
    , strf::sani("--\xff--")                           // sanitized
    , strf::sani("--\xff--", strf::iso_8859_3<char>) ) // sanitized

assert(str == "--\xff----\xff----?----?----?--");
----

The library replaces the invalid sequences by the
https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character[replacement character &#xFFFD;],
if the destination charset supports it ( and by `'?'` otherwise ).

An "invalid sequence" is any input that is non-conformant to the source charset,
or that is impossible translate to the destination charset.
But there is an optional exception for surrogates characters.

NOTE: When the input is UTF-8, the library follows the practice recommended by the
Unicode Standard regarding to calculate how many replacement characters to print
for each non-conformant input sequence. ( see for "Best Practices for Using U+FFFD" in
https://www.unicode.org/versions/Unicode10.0.0/ch03.pdf[Chapter 3] ).

NOTE: The library does not sanitizes non-conformities when converting a single character,
like punctuation characters or the the fill character ( they are in UTF-32 ). In this case
the replacement character is only used when the destination charset is not able
to print the codepoint.
For example, if the you use `(char32_t)0xFFFFFFF` as the <<numpunct,decimal point>>,
then it will printed as "\uFFFD" if the destination is UTF-8 or UTF-16, but
if the destination is UTF-32, then the library just writes `(char32_t)0xFFFFFFF`
verbatim.

[[surrogate_policy]]
=== Surrogates tolerance

There is one particular kind of nonconformity that you may sometimes want to
permit, which is the invalid presence of
https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates[surrogate]
characters.
That is particular common on Windows, where you may have an old file names, created
at the time of Windows 95 ( where wide strings were UCS-2 ) and that contains
some unpaired surrogates. If you then treat it as UTF-16 and convert it to UTF-8
and back to UTF-16, you get a different name.

So the library provides the `surrogate_policy` enumeration, which is a facet that
enables you to turn off the surrogate sanitization.

[source,cpp]
----
namespace strf {
enum class surrogate_policy : bool { strict = false, lax = true };
}
----
When the value is `surrogate_policy::strict`, which is the default,
if an UTF-16 input contains a high surrogate not followed by a low surrogate,
or a low surrogate not following a high surrogate, that is considered
invalid and is thus sanitized.
When the value is `surrogate_policy::lax`, those situations are allowed.

[source,cpp]
----
std::u16string original {u'-', 0xD800 ,u'-', u'-', u'-'};

// convert to UTF-8
auto str_strict = strf::to_u8string(strf::conv(original));
auto str_lax =
    strf::to_u8string .with(strf::surrogate_policy::lax) (strf::conv(original));

assert(str_strict == u8"-\uFFFD---");                  // surrogate sanitized
assert(str_lax == (const char8_t*)"-\xED\xA0\x80---"); // surrogate allowed

// convert back to UTF-16
auto utf16_strict = strf::to_u16string(strf::conv(str_lax));
auto utf16_lax =
    strf::to_u16string .with(strf::surrogate_policy::lax) (strf::conv(str_lax));

assert(utf16_strict == u"-\uFFFD\uFFFD\uFFFD---");     // surrogate sanitized
assert(utf16_lax == original);                         // surrogate preserved
----

[[invalid_seq_notifier]]
=== Encoding error notifier function

The facet `<<strf_hpp#invalid_seq_notifier,invalid_seq_notifier>>` contains
a function pointer that is called every time an ivalid sequence is sanitized,
unless it is null, which is the default.

The code below throws an exception if `u16str` contains any invalid sequence:
[source,cpp]
----
std::u16string u16str = /* ... */;
notifier_func =  [](){
    throw std::sytem_error(std::make_error_code(std::errc::illegal_byte_sequence));
};
strf::invalid_seq_notifier notifier{ notifier_func };

auto str = strf::to_string.width(notifier)(strf::conv(u16str));
----


[[width_calculator]]
== Width Calculation

The `<<strf_hpp#width_calculator_c,width_calculator_c>>` facet value
enables you to choose how the width of a string is calculated when using
<<alignment_format_functions,alignment formatting>>. You have five options:

* The `<<strf_hpp#fast_width,fast_width>>` facet object assumes that the width
  of a string is equal to its size. This is the least accurate method,
  but it's the fastest.
+
.Example
[source,cpp]
----
auto str = "15.00 \xE2\x82\xAC \x80"; // "15.00 € \x80"
auto result = strf::to_string.with(strf::fast_width)
             ( strf::right(str, 12, '*') );
assert(result == "*15.00 \xE2\x82\xAC \x80"); // width calculated as 11
----
* The `<<strf_hpp#width_as_fast_u32len,width_as_fast_u32len>>` facet value
  evaluates the width of a string as the number of Unicode code points.
  However, differently from `width_as_u32len`, to gain performance,
  it assumes that the measured string is conformant to its charset.
  Nonconformities do not cause undefined behaviour, but lead to incorrect
  values. For example, the width of an UTF-8 string may simply be calculated as
  the number of bytes that are not in the range [`0x80`, `0xBF`], __i.e.__,
  btye that are not continuation bytes. This way, any extra continuation byte -- that
  would replaced by a `"\uFFFD"` during sanitization -- is not counted.
+
.Example
[source,cpp]
----
auto str = "15.00 \xE2\x82\xAC \x80"; // "15.00 € \x80"
auto result = strf::to_string .with(strf::width_as_fast_u32len)
             ( strf::right(str, 12, '*'));
assert(result == "****15.00 \xE2\x82\xAC \x80"); // width calculated as 8
----
* The `<<strf_hpp#width_as_u32len,width_as_u32len>>` facet value also
  evaluates the width of a string as the number of Unicode code points.
  But each nonconformity to the charset is counted as an extra
  code points ( as if it were replaced by
  https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character[replacement character &#xFFFD;] ).
+
.Example
[source,cpp]
----
auto str = "15.00 \xE2\x82\xAC \x80"; // "15.00 € \x80"
auto result = strf::to_string .with(strf::width_as_u32len)
             ( strf::right(str, 12, '*'));

assert(result == "***15.00 \xE2\x82\xAC \x80"); // width calculated as 9
----
+
* `<<strf_hpp#std_width_calc,std_width_calc>>` is the default.
It calculates the width just
as http://eel.is/c++draft/format.string.std#11[specified] to `std::format`,
which means it is aware of https://unicode.org/reports/tr29/[grapheme clustering]
and also that the width of some codepoints is equal to `2`.
It doesn't require however the string
to be encoded in UTF ( internally, it is converted to UTF-32 ).
+
* The fifth option is to implement your own width calculator. This
  implies to create a class that satisfies the
  <<strf_hpp#WidthCalculator,WidthCalculator>> type requirements.


//   There are two reasons why you may want to do that, instead
//   of the of the previous options:
// ** Accuracy: The previous methods are not able to take into
//   account the presence of ligatures and digraphs.
// ** Peformance: The object returned by
//   `<<strf_hpp#make_width_calculator,make_width_calculator>>`
//   converts the string to UTF-32 before calling the provided
//   function object for each UTF-32 character.
//   When you implement your own calculator, you can optimize
//   it to directly measure strings that are encoded
//   in a specific charset.
////
  To-do example
////
//-
'''
[NOTE]
====
The width calculation algorithm is applied
on the input, not the output string. Keep that in mind when
converting from one charset to another using
`<<charset_conversion,conv>>` or `<<charset_conversion,sani`>>.
For example, when converting from UTF-8 to UTF-16 and using
the `fast_width` facet, the
width of the string is its size in UTF-8, not in UTF-16.
[source,cpp]
----
auto str = "15.00 \xE2\x82\xAC \x80"; // "15.00 € \x80"

auto res1 = strf::to_u16string.with(strf::fast_width)
            (strf::conv(str) > 12);
auto res2 = strf::to_u16string.with(strf::width_as_fast_u32len)
            (strf::conv(str) > 12);
auto res3 = strf::to_u16string.with(strf::width_as_u32len)
            (strf::conv(str) > 12);

assert(res1 == u" 15.00 \u20AC \uFFFD");  // width calculated as strlen(str)
assert(res2 == u"    15.00 \u20AC \uFFFD"); // width calculated as 8
assert(res3 == u"   15.00 \u20AC \uFFFD"); // width calculated as 9
----
====

== Ranges

=== Without formatting

|===
|`range(__range_obj__, _func_~_opt_~)`
|`range(_array_, _func_~_opt_~)`
|`range(_begin_, _end_, _func_~_opt_~)`
|`separated_range(__range_obj__, _separator_, _func_~_opt_~)`
|`separated_range(_array_, _separator_, _func_~_opt_~)`
|`separated_range(_begin_, _end_, _separator_, _func_~_opt_~)`
|===
where

* `__range_obj__` is an object whose type is a https://en.cppreference.com/w/cpp/named_req/Container[_Container_] type
* `_begin_` and `_end_` are iterators
* `_separator_` is a raw string of `_CharT_`, where `_CharT_` is the destination character type.
* `_func_` is  unary a function object such that the type of expression `_func_(_x_)` is printable where `_x_` is an element of the range.


.Examples
[source,cpp,subs=normal]
----
int arr[3] = { 11, 22, 33 };

auto str = strf::to_string(strf::range(arr));
assert(str == "112233");

str = strf::to_string(strf::separated_range(arr, ", "));
assert(str == "11, 22, 33");

auto op = [](auto x){ return strf::<<join,join>>('(', +strf::fmt(x * 10), ')'); };

str = strf::to_string(strf::separated_range(arr, ", ", op));
assert(str == "(+110), (+220), (+330)");
----

=== With formatting

|===
|`fmt_range(__range_obj__)`
|`fmt_range(_array_)`
|`fmt_range(_begin_, _end_)`
|`fmt_separated_range(__range_obj__, _separator_)`
|`fmt_separated_range(_array_, _separator_)`
|`fmt_separated_range(_begin_, _end_, _separator_)`
|===

Any format function applicable to the element type of the
range can also be applied to the
expression `strf::fmt_range(/{asterisk}\...{asterisk}/)` or
`strf::fmt_separated_range(/{asterisk}\...{asterisk}/)`.
It causes the formatting to be applied to each element.

.Example 1
[source,cpp]
----
std::vector<int> vec = { 11, 22, 33 };
auto str1 = strf::to_string("[", +strf::fmt_separated_range(vec, " ;") > 6, "]");
assert(str1 == "[   +11 ;   +22 ;   +33]");
----

.Example 2
[source,cpp]
----
int array[] = { 11, 22, 33 };
auto str2 = strf::to_string
    ( "["
    , *strf::fmt_separated_range(array, " / ").fill('.').hex() > 6,
    " ]");

assert(str2 == "[..0xfa / ..0xfb / ..0xfc]");
----

[[join]]
== Joins

=== Simple joins
|===
|`join(__args__\...)`
|===
_Joins_ enables you to group a set of input arguments as one:
[source,cpp]
----
auto str = strf::to_string.tr("Blah blah blah {}.", strf::join("abc", '/', 123))
assert(str == "Blah blah blah abc/123")
----

They can be handy to create aliases:

[source,cpp,subs=normal]
----
struct date{ int day, month, year; };

auto as_yymmdd = [](date d) {
    return strf::join( strf::dec(d.year % 100).p(2), '/'
                     , strf::dec(d.month).p(2), '/'
                     , strf::dec(d.day).p(2) );
};
date d {1, 1, 1999};
auto str = strf::to_string("The day was ", as_yymmdd(d), '.');
assert(str == "The day was is 99/01/01.");
----

=== Aligned joins [[aligned_join]]
You can apply any of the <<alignment_format_functions,alignment format functions>> on the
expression `join(__args__\...)`
[source,cpp]
----
auto str = strf::to_string(strf::join("abc", "def", 123) > 15);
assert(str == "      abcdef123);
----
Or use any of the expressions below:
|===
|`join_left(_width_, _ch_~_opt_~) (__args__\...)`
|`join_right(_width_, _ch_~_opt_~) (__args__\...)`
|`join_center(_width_, _ch_~_opt_~) (__args__\...)`
|===
where:

* `__args__\...` are the values to be printed
* `_width_` is a value of type `{width_t}`
* `_alignment_` is a value of type `<<strf_hpp#text_alignment, text_alignment>>`
* `_ch_` is a value of type `char32_t`

[source,cpp]
----
auto str = strf::to_string(strf::join_center(15, U'.')("abc", "def", 123));
assert(...abcdef123...);
----

////
[WARNING]
====
Watch out for dangling references when using joins.
When passing an array to `join`, it is stored by reference
in the returned object. So the code below has UB:
[source]
----
auto get_hello(const char* name)
{
    char buff[20]; // temporary array
    strcpy(buff, "Hello");
    return strf::join(buff, name, '!');
}

int main()
{
    // accessing a dangling array reference
    strf::to(stdout)(get_hello("Maria"));
}
----
Of course, `get_hello()` could be fixed by simply returning instead
`strf::join("Hello", name, '!')`, since string literals have
static storage duration.

Also, although arguments are stored by value in joins
( except for arrays ), some of the arguments may contain references.
For exemple, if `str` is a `std::string`, then
`strf::<<format_function_aliases,right>>(str, 10)` doesn't store a copy of
`str`, but a reference to its array of characters.
====
////

