////
Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////

:default_tr_error_notifier: <<default_tr_error_notifier,default_tr_error_notifier>>

[[tr_string]]
== Tr-String

=== Syntax

[%header,cols=3*]
|===
|A `'{'` followed by  |until                           |means
|`'-'`                |the next `'}'` or end of string |a comment
|a digit              |the next `'}'` or end of string |a positional argument reference
|another `'{'`        |the second `'{'`                |an escaped `'{'`
|any other character  |the next `'}'` or end of string |a non positional argument reference
|===

==== Examples:

.Comments
[source,cpp]
----
auto str = strf::to_string.tr
    ( "You can learn more about python{-the programming language, not the reptile} at {}"
    , "www.python.org" );
assert(str == "You can learn more about python at www.python.org");
----

.Positional arguments
[source,cpp]
----
auto str = strf::to_string.tr("{1 a person} likes {0 a food type}.", "sandwich", "Paul");
assert(str == "Paul likes sandwich.");
----

.Non positional arguments
[source,cpp]
----
auto str = strf::to_string.tr("{a person} likes {a food type}.", "Paul", "sandwich");
assert(str == "Paul likes sandwich.");
----

.Escapes
[source,cpp]
----
auto str = strf::to_string.tr("} {{x} {{{} {{{}}", "aaa", "bbb");
assert(str == "} {x} {aaa {bbb}");
----

==== Syntax error handling

When the argument associated with a `"{"` does not exists, the library does two things:

- It prints a https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character[replacement character `"\uFFFD"` (&#65533;) ] ( or `"?"` when the encoding can't represent it ) where the missing argument would be printed.
- It calls the `handle` function on the facet object correspoding to the `tr_error_notifier_c` category.

=== Facet category `tr_error_notifier_c` [[tr_error_notifier_c]]

For a type to be a facet of the `tr_error_notifier_c`, it must satisfy the
requirements of __<<TrErrorHandling,TrErrorHandling>>__

[source,cpp,subs=normal]
----
namespace strf {

struct tr_error_notifier_c {
    static constexpr {default_tr_error_notifier} get_default() noexcept
    {
        return {default_tr_error_notifier}{};
    }
};

} // namespace strf
----

==== Struct `default_tr_error_notifier` [[default_tr_error_notifier]]

`default_tr_error_notifier` is the default facet of the `tr_error_notifier_c` category.
It's a dummy error handler.

[source,cpp]
----
namespace strf {

struct default_tr_error_notifier {
    using category = tr_error_notifier_c;

    template <typename CharEncoding>
    void handle
        ( const typename CharEncoding::char_type* str
        , std::size_t str_len
        , std::size_t err_pos
        , CharEncoding enc ) noexcept
    {
    }
};

} // namespace strf
----

==== Type requirement _TrErrorHandling_ [[TrErrorHandling]]

Given:

- `X`, a _TrErrorHandling_ type
- `x`, a value of type `X`
- `Enc`, a _<<CharEncoding,CharEncoding>>_ type.
- `enc`, a value of type `Enc`
- `str`, a value of type `const Enc::char_type*` pointing to string encoded according to `enc`
- `str_len`, a `std::size_t` value equal to the length of the string `str`
- `err_pos`, a `std::size_t` value less than or equal to `str_len`

The following must host:

- `X` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[__CopyConstructible__].
- `X::category` is a type alias to `tr_error_notifier_c`
- The following expression is supported:

====
[source,cpp]
----
x.handle(str, str_len, err_pos, enc)
----
[horizontal]
Semantics:: `str` is a tr-string that contains an error. `err_pos` is the
position of the `'{'` character in `str` that starts the invalid argument reference.

====
