////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:arg_printer_type: <<arg_printer_type,arg_printer_type>>
:arg_printer:      <<arg_printer,arg_printer>>
:destination: <<destination_hpp#destination,destination>>
:tag: <<tag,tag>>
:preprinting: <<preprinting,preprinting>>
:make_arg_printer_input: <<make_arg_printer_input,make_arg_printer_input>>


:basic_cstr_writer: <<destination_hpp#basic_cstr_writer,basic_cstr_writer>>
:basic_char_array_writer: <<destination_hpp#basic_char_array_writer,basic_char_array_writer>>
:printer_no_reserve: <<printer_no_reserve,printer_no_reserve>>
:DestinationCreator: <<DestinationCreator,DestinationCreator>>
:SizedDestinationCreator: <<SizedDestinationCreator,SizedDestinationCreator>>

[[destinators]]
== Printers

The `printer_no_reserve`, `printer_with_size_calc` and
`printer_with_given_size` class templates implement the
functions availabe in the basic usage syntax of the library:

image::syntax.svg[]

////
All of them contain a {facets_pack} member object in addition to
__{DestinationCreator}__ or __{SizeDestinationCreator}__ member object and
in the above expression:
////

* `no_reserve()` always returns a `printer_no_reserve` object
* `reserve_calc()` always returns a `printer_with_size_calc` object.
* `reserve(__size__)` always returns a `printer_with_given_size` object.
* The __printer__ is an expression that is or creates an object whose type
  is an instance of one those three class templates.

====
[[to_char_ptr_range]]
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  begin,  char8_t{asterisk}  end);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     begin,  char{asterisk}     end);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} begin,  char16_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} begin,  char32_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  begin,  wchar_t{asterisk}  end);

} // namespace strf
----
Return type:: `{printer_no_reserve}<DestCreator>`, where `DestCreator`
         is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object  `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{basic_cstr_writer}<__char_type__>{begin, end}
----
====

[[to_char_ptr_count]]
====
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  dest, std::size_t count);

} // namespace strf
----

[horizontal]
Return type and value:: Same as of `to(dest, dest + count)`;
====
====
[[to_char_array]]
[source,cpp,subs=normal]
----
namespace strf {

template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char8_t  (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char     (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char16_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char32_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(wchar_t  (&dest)[N]);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to(dest, dest + N)`;
====


[[to_range]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT>
__/{asterisk} see below {asterisk}/__ to_range(CharT* begin, CharT* end);

} // namespace strf
----
Return type:: `{printer_no_reserve}<DestCreator>`, where `DestCreator`
         is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object  `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{basic_char_array_writer}<__char_type__>{begin, end}
----
====
[[to_range_array]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT, std::size_t N>
__/{asterisk} see below {asterisk}/__ to_range(CharT (&dest)[N]);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to_range(dest, dest + N)`;
====
[[to_range_count]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT>
__/{asterisk} see below {asterisk}/__ to_range(CharT* dest, std::size_t count);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to_range(dest, dest + count)`;
====


[[printer_no_reserve]]
=== Class template `printer_no_reserve`
====
[source,cpp,subs=normal]
----
template <typename DestinationCreator, typename FPack = {facets_pack}<>>
class printer_no_reserve
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `DestinationCreator` satisfies <<DestinationCreator,_DestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename DestinationCreator, typename FPack>
class printer_no_reserve
{
public:
    using char_type = typename DestinationCreator::char_type;

    // <<printer_no_reserve_ctor,constructors>>
    template <typename\... Args>
    constexpr printer_no_reserve(Args&&\...);
    constexpr printer_no_reserve(const printer_no_reserve&);
    constexpr printer_no_reserve(printer_no_reserve&&);

    // <<printer_no_reserve_with,facets>>
    template <typename\... FPE>
    printer_no_reserve<DestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    printer_no_reserve<DestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<printer_no_reserve_reserve,size reserve>>
    constexpr printer_with_size_calc<DestinationCreator, FPack>
    reserve_calc() const &;

    constexpr printer_with_size_calc<DestinationCreator, FPack>
    reserve_calc() &&;

    constexpr printer_with_given_size<DestinationCreator, FPack>
    reserve(std::size_t) const &;

    constexpr printer_with_given_size<DestinationCreator, FPack>
    reserve(std::size_t) &&;

    constexpr printer_no_reserve&  no_reserve() &;
    constexpr printer_no_reserve&& no_reserve() &&;
    constexpr const printer_no_reserve&  no_reserve() const &;
    constexpr const printer_no_reserve&& no_reserve() const &&;

    // <<printer_no_reserve_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>&
              , const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type>
              , const Args&\...) const;

private:
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack &#95;fpack;                     // exposition only
};

} // namespace strf
----

==== Public member functions

[[printer_no_reserve_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr printer_no_reserve(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr printer_no_reserve(const printer_no_reserve&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr printer_no_reserve(printer_no_reserve&&) = default;
----
Move constructor.
====
[[printer_no_reserve_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_no_reserve< DestinationCreator
                  , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                 , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates a `printer_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_no_reserve< DestinationCreator
                  , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                 , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `printer_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[printer_no_reserve_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_size_calc` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_size_calc` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_given_size` whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) &&;
----
Compile-time requirements::
`DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_given_size` object whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_no_reserve&  no_reserve() &;
constexpr printer_no_reserve&& no_reserve() &&;
constexpr const printer_no_reserve&  no_reserve() const &;
constexpr const printer_no_reserve&& no_reserve() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====

[[printer_no_reserve_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
// Return type::
// - `decltype(std::declval<decltype(&#95;dest&#95;creator.create())&>().finish())` if such type is valid, otherwise `void`
Effect::
. Creates the `{destination}` object doing
+
[source,cpp,subs=normal]
----
typename DestinationCreator::destination_type dest{&#95;dest&#95;creator.create()};
----
. For each `arg` in `args\...`, does
+
[source,cpp,subs=normal]
----
using pre_t = {preprinting}<precalc_size::no, precalc_width::no>;
pre_t pre;
using printer_t = {arg_printer_type}<char_type, pre_t, FPack, Arg>;
printer_t p{ {make_arg_printer_input}<char_type>(pre, &#95;fpack, arg) };
static_cast<const {arg_printer}<char_type>&>(p).print_to(dest);
----
where `Arg` is the type in `Args\...` corresponding to `arg`
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
====
[[printer_no_reserve_tr]]
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect:: __to-do__


////
. Creates/get the `{destination}` object doing
+
[source,cpp,subs=normal]
----
typename DestinationCreator::destination_type dest{&#95;dest&#95;creator.create()};
----
. For each `arg` in `args\...`, creates an `arg_printer` object by doing:
+
[source,cpp,subs=normal]
----
----
, where `Arg` is the type in `Args\...` corresponding to `arg`
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
////

====
[[printer_with_size_calc]]
=== Class template `printer_with_size_calc`
====
[source,cpp,subs=normal]
----
template <typename SizedDestinationCreator, typename FPack = {facets_pack}<>>
class printer_with_size_calc;
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedDestinationCreator` satisfies <<SizedDestinationCreator,_SizedDestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedDestinationCreator, typename FPack>
class printer_with_size_calc
{
public:
    using char_type = typename SizedDestinationCreator::char_type;

    // <<printer_with_size_calc_ctor,constructors>>
    template <typename\... Args>
    constexpr printer_with_size_calc(Args&&\...);

    constexpr printer_with_size_calc(const printer_with_size_calc&) = default;
    constexpr printer_with_size_calc(printer_with_size_calc&&) = default;

    // <<printer_with_size_calc_with,facets>>
    template <typename\... FPE>
    printer_with_size_calc<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    printer_with_size_calc<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<printer_with_size_calc_reserve,size reserve>>
    constexpr printer_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() const &;

    constexpr printer_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() &&;

    constexpr printer_with_given_size<SizedDestinationCreator, FPack>
    reserve(std::size_t) const &;

    constexpr printer_with_given_size<SizedDestinationCreator, FPack>
    reserve(std::size_t) &&;

    constexpr printer_with_size_calc&  reserve_calc() &;
    constexpr printer_with_size_calc&& reserve_calc() &&;
    constexpr const printer_with_size_calc&  reserve_calc() const &;
    constexpr const printer_with_size_calc&& reserve_calc() const &&;

    // <<printer_with_size_calc_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack _fpack;                     // exposition only
};

} // namespace strf
----

[[printer_with_size_calc_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr printer_with_size_calc(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>::value` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr printer_with_size_calc(const printer_with_size_calc&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr printer_with_size_calc(printer_with_size_calc&&) = default;
----
Move constructor.
====
[[printer_with_size_calc_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_with_size_calc< DestinationCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `printer_with_size_calc` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_with_size_calc< DestinationCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `printer_with_size_calc` object whose `&#95;dest&#95;creator`
is initialized with `std::move(this\->&#95;dest&#95;creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[printer_with_size_calc_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr printer_no_reserve<DestinationCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_given_size` whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size<DestinationCreator, FPack>
reserve(std::size_t) &&;
----
Compile-time requirements::
`DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_given_size` object whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc&  reserve_calc() &;
constexpr printer_with_size_calc&& reserve_calc() &&;
constexpr const printer_with_size_calc&  reserve_calc() const &;
constexpr const printer_with_size_calc&& reserve_calc() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====
[[printer_with_size_calc_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates an object `pre` of type
  `{preprinting}<precalc_size::yes, precalc_width::no>`.
+
[source,cpp,subs=normal]
----
using pre_type = {preprinting}<precalc_size::yes, precalc_width::no>;
pre_type pre;
----
. For each `arg` in `args\...`, creates an `arg_printer` object by doing:
+
[source,cpp,subs=normal]
----
using arg_printer_t = {arg_printer_type}<char_type, pre_type, FPack, Arg>;
arg_printer_t p{ {make_arg_printer_input}<char_type>(pre, &#95;fpack, arg) };
----
. Creates/get the `{destination}` object doing
+
[source,cpp,subs=normal]
----
using dest_type = typename DestinationCreator::sized_destination_type;
dest_type dest{&#95;dest&#95;creator.create(pre.<<size_accumulator_accumulated_size,accumulated_size>>())};
----
. For each `p` object does:
+
[source,cpp,subs=normal]
----
static_cast<const {arg_printer}<char_type>&>(p).print_to(dest);
----
. Returns `dest.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect:: __to-do__

////
. For each `arg` in `args\...`, do
+
[source,cpp,subs=normal]
----
preprinting<precalc_size::yes, precalc_width::no> pre;
auto p = static_cast< const {arg_printer}<CharT>& >
    ( {arg_printer_type}<CharT, FPack, T>{ fpack, pre, x, {tag}<CharT>{} } )
----
. Calculates the size of the content to be printed according to the
  <<tr_string,tr-string syntax>> and using the `pre` objects
  of the previous step.
. Creates/get the `{destination}` object by doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(size)
----
, where `size` is the value calculated in the previous step.
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
////
====

[[printer_with_given_size]]
=== Class template `printer_with_given_size`
====
[source,cpp,subs=normal]
----
template <typename SizedDestinationCreator, typename FPack = {facets_pack}<>>
class printer_with_given_size
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedDestinationCreator` satisfies <<SizedDestinationCreator,_SizedDestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedDestinationCreator, typename FPack>
class printer_with_given_size
{
public:
    using char_type = typename SizedDestinationCreator::char_type;

    // <<printer_with_given_size_ctor,constructors>>
    template <typename\... Args>
    constexpr printer_with_given_size(std::size_t, Args&&\...);
    constexpr printer_with_given_size(const printer_with_given_size&) = default;
    constexpr printer_with_given_size(printer_with_given_size&&) = default;

    // <<printer_with_given_size_with,facets>>
    template <typename\... FPE>
    printer_with_given_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    printer_with_given_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<printer_with_given_size_reserve,size reserve>>
    constexpr printer_with_size_calc<SizedDestinationCreator, FPack>
    reserve_calc() const &;

    constexpr printer_with_size_calc<SizedDestinationCreator, FPack>
    reserve_calc() &&;

    constexpr printer_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() const &;

    constexpr printer_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() &&;

    constexpr printer_with_given_size&  reserve(std::size_t) &;
    constexpr printer_with_given_size&& reserve(std::size_t) &&;
    constexpr printer_with_given_size   reserve(std::size_t) const &;
    constexpr printer_with_given_size   reserve(std::size_t) const &&;

    // <<printer_with_given_size_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    std::size_t _size                 // exposition only
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack _fpack;                     // exposition only
};

} // namespace strf
----
[[printer_with_given_size_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr printer_with_given_size(std::size_t size, Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
- Initializes `_size` with `size`
====
====
[source,cpp]
----
constexpr printer_with_given_size(const printer_with_given_size&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr printer_with_given_size(printer_with_given_size&&) = default;
----
Move constructor.
====
[[printer_with_given_size_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_with_given_size< DestinationCreator
                       , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                      , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `printer_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`
, and whose `_fpack` is initialized with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`

====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
printer_with_given_size< DestinationCreator
                       , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                      , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `printer_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)` from this object
, and whose `_fpack` is initialized with
`pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[printer_with_given_size_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr printer_no_reserve<DestinationCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_no_reserve` object
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> no_reserve() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_size_calc` object
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_size_calc<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `printer_with_size_calc` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size&  reserve(std::size_t size) &;
constexpr printer_with_given_size&& reserve(std::size_t size) &&;
----
[horizontal]
Effect:: assign `size` to `_size`.
Return:: This object.
====
====
[source,cpp,subs=normal]
----
constexpr printer_with_given_size reserve(std::size_t size) const &;
constexpr printer_with_given_size reserve(std::size_t size) const &&;
----
[horizontal]
Effect:: Creates an `destination_with_give_size` object
whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `facets_pack` object with this `_fpack`.
====
[[printer_with_given_size_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates/get the `{destination}` object doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(_size)
----
. For each `arg` in `args\...` does:
+
[source,cpp,subs=normal]
----
using pre_t = {preprinting}<precalc_size::no, precalc_width::no>;
pre_t pre;
using arg_printer_t = {arg_printer_type}<char_type, pre_t, FPack, Arg>;
arg_printer_t p{ {make_arg_printer_input}<char_type>(pre, &#95;fpack, arg) };
static_cast<const {arg_printer}<char_type>&>(p).print_to(dest);
----
, where `Arg` is the type in `Args\...` corresponding to `arg`
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename\... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
__to-do__
////
. Creates/get the `{destination}` object doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(_size)
----
. For each `arg` in `args\...`, creates an `{arg_printer}` object by doing:
+
[source,cpp,subs=normal]
----
auto p = static_cast< const {arg_printer}<CharT>& >
    ( {arg_printer_type}<CharT, FPack, T>{fpack, pre, x, chtag} )
----
, where `pre` is an instance of `preprinting<precalc_size::no, precalc_width::no>`,
abs `chtag` is an expression of type `{tag}<CharT>`.
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid ( which is optional ).
////
====

[[DestinationCreator]]
=== Type requirement _DestinationCreator_
Given

- `char_type`, a character type
- `X`, an  _DestinationCreator_ type for `char_type`
- `x`, an expression of type `X` or `const X`

The following must hold:

- `X` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[CopyConstructible]
- `X` has a member type alias `X::char_type` defined as `char_type`
- `X` has the `X::destination_type` that is a type alias to a concrete type that is derives
   from `{destination}<X::char_type>`

And the following expression must be well-formed:

[[DestinationCreator_create]]
====
[source,cpp]
----
typename X::destination_type{x.create()}
----
====

[[SizedDestinationCreator]]
=== Type requirement _SizedDestinationCreator_
Given

- `char_type`, a character type
- `size`, a value of the `std::size_t`
- `X`, an  _SizedDestinationCreator_ type for `char_type`
- `x`, an expression of type `X` or `const X`

The following must hold:

- `X` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[CopyConstructible]
- `X` has a member type alias `T::char_type` defined as `char_type`
- `X` has the `X::sized_destination_type` that is a type alias to a concrete type that derives
   from `destination<X::char_type>`

And the following expression must be well-formed:

[[SizedDestinationCreator_create]]
====
[source,cpp]
----
typename X::sized_destination_type{x.create(size)}
----
====

