////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

== List of printable types [[printable_types_list]]

=== Strings
Types::
`const CharT*`, `std::basic_string_view<CharT, Traits>`
and `std::basic_string<CharT, Traits, Alloc>`
+
where:
+
- `CharT` is the character type. If it is not the same as the output character type, then it is necessary to use the `conv` or `sani` format function.
- `Traits` can be any type that satisfies https://en.cppreference.com/w/cpp/named_req/CharTraits[CharTraits]
- `Alloc` can be any type that satisfies https://en.cppreference.com/w/cpp/named_req/Allocator[Allocator]

Overridable:: No

Representative type:: `string_input_tag<CharT>`,  where `string_input_tag` is defined as below:
+
[source,cpp]
----
namespace strf {

struct string_input_tag_base {};

template <typename CharT>
struct string_input_tag: string_input_tag_base{}

} // namespace strf
----

Influenced by facet categories::
- `<<width_calculator_c,width_calculator_c>>`
- `<<charset_c,charset_c>><__CharType__>`
- `<<surrogate_policy,surrogate_policy_c>>`
- `<<transcoding_error_notifier_c,transcoding_error_notifier_c>>`


Format functions::
( in addition to <<alignment_formatter, alignment functions>> )

`p(<<strf_hpp#width_t,width_t>> limit)`:::
   Does not print the whole string if its width is greater than `limit`,
   but the greatest possible amount of its leading Unicode code points
   such that the width is not greater than `limit`.
+
////
   but prints the maxixum leading sub-string such that its width
   is not greater than `limit`.
   Prints the maximum amount of Unicode code points such that
   the width is not greater than `limit`.
   __To-to__
////
+
`template <typename Charset> sanitize_from_charset(Charset cs)`:::
   Convert the input string from `cs` to the output charset.
   If the charsets are the same then sanitizes the input string.
`sanitize_charset()`::: Translates input string from the charset associated to `CharT` to
            the output charset. If these charsets are the same
            then sanitizes the input string.
`template <typename Charset> convert_from_charset(Charset cs)`:::
   Convert the input string from `cs` to the
   output charset, if these charsets are not the same.
   Otherwise, copies input string as it is.
`convert_charset()` ::: Translates input string from the charset associated to `CharT` to
          the output charset, if these charsets are not the same.
          Otherwise, copies the input string as it is.
`template <typename Charset>  sani(Charset cs)`::: Equivanlent to `sanitize_charset(cs)`
`template <typename Charset>  conv(Charset cs)`::: Equivanlent to `convert_charset(cs)`
`sani()`::: Equivalent to `sanitize_charset()`
`conv()`::: Equivalent to `convert_charset()`
+
.Example
[source,cpp]
----
auto str = strf::to_string(strf::center(u" Hello! ", 16, '*').conv());
assert(str == "**** Hello! ****");
----



=== Single characters
Type:: The same as the output character type or `char32_t`. In the later case,
       the UTF-32 character is encoded to the destination charset.
Representative type:: The same as the input type

Overridable:: No

Formatters::
* `<<alignment_formatter,alignment_formatter>>`
* `<<quantity_formatter,quantity_formatter>>`

//-
Influenced by facet categories::
* `<<width_calculator_c,width_calculator_c>>`
* `<<charset_c,charset_c>><__CharType__>`: in two situations:
**  when using <<alignment_formatter,alignment formatting>>
**  when the character type is `char32_t` and the destination character type
    is not `char32_t`.

=== `bool` [[printable_bool]]
Type:: `bool`

Representative type:: `bool`
Overridable:: Yes
Formatters::
* `<<alignment_formatter,alignment_formatter>>`

Influenced by facet categories::
- `<<lettercase,lettercase_c>>`
- `<<charset_c,charset_c>><__CharType__>`: Used to encode the <<alignment_formatter,fill character>>.

=== `const void*`
Types:: `const void*`
Representative type:: `const void*`
Overridable:: Yes

Formatters::
* `<<alignment_formatter,alignment_formatter>>`

Influenced by facet categories::
- `<<lettercase,lettercase_c>>`
- `<<charset_c,charset_c>><__CharType__>`: Used to encode the <<alignment_formatter,fill character>>.

=== Integers

Types::
`short`,
`int`,
`long int`,
`long long int`,
`unsigned short`,
`unsigned int`,
`unsigned long int` and
`unsigned long long int`

Representative type:: The same as the input type ( `short`,
`int`,
`long int`,
`long long int`,
`unsigned short`,
`unsigned int`,
`unsigned long int` or
`unsigned long long int` )

Overridable:: Yes

Formatters::
* `<<alignment_formatter,alignment_formatter>>`
* `<<int_formatter,int_formatter>>`

//-
Influenced by facet categories::
- `<<lettercase,lettercase_c>>`
- `<<numpunct, numpunct_c>><__Base__>`
- `<<charset_c,charset_c>><__CharType__>`: Used to encode the <<alignment_formatter,fill character>> and the <<numpunct,punctuation characters>>.


=== Floating Points
Types:: `float`, `double`
Representative type:: The same as the input type ( `float` or `double` )
Overridable:: Yes

Formatters::
* `<<alignment_formatter,alignment_formatter>>`
* `<<float_formatter,float_formatter>>`

//-
Influenced by facet categories::
- `<<lettercase,lettercase_c>>`
- `<<numpunct,numpunct_c>><10>`
- `<<numpunct,numpunct_c>><16>`
- `<<charset_c,charset_c>><__CharType__>`: Used to encode the <<alignment_formatter,fill character>> and the <<numpunct,punctuation characters>>.

=== Ranges

==== Without formatting

[source,cpp]
----
namespace strf {

template <typename Range>
/*...*/ range(const Range& r);

template <typename T, std::size_t N>
/*...*/ range(T (&array)[N]);

template <typename Iterator>
/*...*/ range(const Iterator& begin, const Iterator& end);

// With operation

template <typename Range, typename UnaryOperation>
/*...*/ range(const Range& r, UnaryOperation unary_op);

template <typename T, std::size_t N, typename UnaryOperation>
/*...*/ range(T (&array)[N], UnaryOperation unary_op);

template <typename Iterator, typename UnaryOperation>
/*...*/ range( const Iterator& begin
             , const Iterator& end
             , UnaryOperation unary_op );

// With separator:

template <typename Range, typename CharT>
/*...*/ separated_range(const Range& r, const CharT* separator);

template <typename T, std::size_t N, typename CharT>
/*...*/ separated_range(T (&array)[N], const CharT* separator);

template <typename Iterator, typename CharT>
/*...*/ separated_range( const Iterator& begin
                       , const Iterator& end
                       , const CharT* separator );

// With separator and operation

template <typename Range, typename CharT, typename UnaryOperation>
/*...*/ separated_range( const Range& r
                       , const CharT* separator
                       , UnaryOperation unary_op );

template <typename T, std::size_t N, typename CharT, typename UnaryOperation>
/*...*/ separated_range( T (&array)[N]
                       , const CharT* separator
                       , UnaryOperation unary_op );

template <typename Iterator, typename CharT, typename UnaryOperation>
/*...*/ separated_range( const Iterator& begin
                       , const Iterator& end
                       , const CharT* separator
                       , UnaryOperation unary_op );
} // namespace strf
----

.Examples
[source,cpp,subs=normal]
----
int arr[3] = { 11, 22, 33 };

auto str = strf::to_string(strf::range(arr));
assert(str == "112233");

str = strf::to_string(strf::separated_range(arr, ", "));
assert(str == "11, 22, 33");

auto op = [](auto x){ return strf::<<join,join>>('(', +strf::fmt(x * 10), ')'); };

str = strf::to_string(strf::separated_range(arr, ", ", op));
assert(str == "(+110), (+220), (+330)");
----

==== With formatting

[source,cpp]
----
namespace strf {

template <typename Range>
/*...*/ fmt_range(const Range& r);

template <typename T, std::size_t N>
/*...*/ fmt_range(T (&array)[N], const Range& r);

template <typename Iterator>
/*...*/ fmt_range(const Iterator& begin, const Iterator& end);

// With separator

template <typename Range, typename CharT>
/*...*/ fmt_separated_range(const Range& r, const CharT* separator);

template <typename T, std::size_t N, typename CharT>
/*...*/ fmt_separated_range(T (&array)[N], const CharT* separator);

template <typename Iterator, typename CharT>
/*...*/ fmt_separated_range( const Iterator& begin
                           , const Iterator& end
                           , const CharT* separator );
} // namespace strf
----
Any format function applicable to the element type of the
range can also be applied to the
expression `strf::fmt_range(/{asterisk}\...{asterisk}/)` or
`strf::fmt_separated_range(/{asterisk}\...{asterisk}/)`.
This way the format functions is applied to all elements:

.Example 1
[source,cpp]
----
std::vector<int> vec = { 11, 22, 33 };
auto str1 = strf::to_string("[", +strf::fmt_separated_range(vec, " ;") > 4, "]");
assert(str1 == "[ +11 ; +22 ; +33]");
----

.Example 2
[source,cpp]
----
std::vector<int> vec = { 11, 22, 33 };
auto str2 = strf::to_string
    ( "["
    , *strf::fmt_separated_range(vec, " / ").fill('.').hex() > 6,
    " ]");

assert(str2 == "[..0xfa / ..0xfb / ..0xfc]");
----

[[join]]
=== Joins

==== Without alignment

[source,cpp]
----
namespace strf {

template <typename ... Args>
/*...*/ join(const Args& ... args);

}
----

==== With alignment

You can apply the <<alignment_formatter,alignment format functions>>
one the return type of `join(args\...)`

[source,cpp]
----
auto str = strf::to_string
    ("---", strf::join("abc", "def", 123) > 15, "---");

assert(str == "---      abcdef123---");
----

The functions below provide an alternartive syntax to create aligned
join. Their return type has the `operator()(const Args& \... args)` member function
that receives the elements of the join.

[source,cpp]
----
namespace strf {

enum class text_alignment {left, right, center};

/* ... */ join_align( std::int16_t width
                    , text_alignment align
                    , char32_t fillchar = U' ' );
/* ... */ join_center(int width, char32_t fillchar = U' ');
/* ... */ join_left(int width, char32_t fillchar = U' ');
/* ... */ join_right(int width, char32_t fillchar = U' ');
}
----

.Example
[source,cpp]
----
auto str = strf::to_string
    ("---", strf::join_right(15) ("abc", "def", 123), "---");
assert(str == "---      abcdef123---");

str = strf::to_string
    ("---", strf::join_center(15) ("abc", "def", 123), "---");
assert(str == "---   abcdef123   ---");

str = strf::to_string
    ( "---"
    , strf::join_left(15, U'.') ("abc", strf::right("def", 5), 123)
    , "---" );
assert(str == "---abc  def123....---");
----


=== Facets [[global_function_with]]
It is possible to override facets to only a subset of the input arguments.

[source,cpp]
----
namespace strf {

template < typename FPack >
class inner_pack
{
public:
    template <typename... Args>
    /*...*/  operator()(const Args&... args) const;
    //...
};

template <typename ... Facets>
inner_pack</*...*/> with(const Facets&... facets);
----
.Example 1
[source,cpp]
----
auto str = strf::to_string.with(strf::numpunct<10>(1))
    ( !strf::dec(10000)
    , "  "
    , !strf::hex(0x10000)
    , strf::with( strf::numpunct<10>(3)
                , strf::numpunct<16>(4).thousands_sep('\'') )
        ( "  { "
        , !strf::dec(10000)
        , "  "
        , !strf::hex(0x10000)
        , " }" ) );

assert(str == "1,0,0,0,0  10000  { 10,000  1'0000 }");
----

.Example 2
[source,cpp]
----
auto fp = strf::pack
    ( strf::numpunct<10>(3)
    , strf::numpunct<16>(4).thousands_sep('\'') );

auto str = strf::to_string.with(strf::numpunct<10>(1))
    ( !strf::dec(10000)
    , "  "
    , !strf::hex(0x10000)
    , strf::with(fp)
        ( "  { "
        , !strf::dec(10000)
        , "  "
        , !strf::hex(0x10000)
        , strf::with
            (strf::numpunct<10>(2).thousands_sep('.'))
            ("  { ", !strf::dec(10000), " }")
        , " }" ) );

assert(str == "1,0,0,0,0  10000  { 10,000  1'0000  { 1.00.00 } }");
----
