////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:printer_type: <<printer_type,printer_type>>
:printer: <<printer,printer>>
:print_dest: <<destination_hpp#print_dest,print_dest>>
:tag: <<tag,tag>>
:print_preview: <<print_preview,print_preview>>
:make_printer_input: <<make_printer_input,make_printer_input>>


:basic_cstr_writer: <<destination_hpp#basic_cstr_writer,basic_cstr_writer>>
:basic_char_array_writer: <<destination_hpp#basic_char_array_writer,basic_char_array_writer>>
:destination_no_reserve: <<destinators,destination_no_reserve>>
:DestinationCreator: <<DestinationCreator,DestinationCreator>>
:SizedDestinationCreator: <<SizedDestinationCreator,SizedDestinationCreator>>

[[destinators]]
== Destinations

The `destination_no_reserve`, `destination_calc_size` and
`destination_with_given_size` class templates implement the
functions availabe in the basic usage syntax of the library:

image::syntax.svg[]

////
All of them contain a {facets_pack} member object in addition to
__{DestinationCreator}__ or __{SizeDestinationCreator}__ member object and
in the above expression:
////

* `no_reserve()` always returns a `destination_no_reserve` object
* `reserve_calc()` always returns a `destination_calc_size` object.
* `reserve(__size__)` always returns a `destination_with_given_size` object.
* The __dest-expr__ is an expression that is or creates an object whose type
  is an instance of one those three class templates.

=== Destination makers

====
[[to_char_ptr_range]]
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  begin,  char8_t{asterisk}  end);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     begin,  char{asterisk}     end);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} begin,  char16_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} begin,  char32_t{asterisk} end);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  begin,  wchar_t{asterisk}  end);

} // namespace strf
----
Return type:: `{destination_no_reserve}<DestCreator>`, where `DestCreator`
         is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object  `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{basic_cstr_writer}<__char_type__>{begin, end}
----
====

[[to_char_ptr_count]]
====
[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ to(char8_t{asterisk}  dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char{asterisk}     dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char16_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(char32_t{asterisk} dest, std::size_t count);
__/{asterisk} see below {asterisk}/__ to(wchar_t{asterisk}  dest, std::size_t count);

} // namespace strf
----

[horizontal]
Return type and value:: Same as of `to(dest, dest + count)`;
====
====
[[to_char_array]]
[source,cpp,subs=normal]
----
namespace strf {

template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char8_t  (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char     (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char16_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(char32_t (&dest)[N]);
template<std::size_t N> __/{asterisk} see below {asterisk}/__ to(wchar_t  (&dest)[N]);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to(dest, dest + N)`;
====


[[to_range]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT>
__/{asterisk} see below {asterisk}/__ to_range(CharT* begin, CharT* end);

} // namespace strf
----
Return type:: `{destination_no_reserve}<DestCreator>`, where `DestCreator`
         is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object  `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{basic_char_array_writer}<__char_type__>{begin, end}
----
====
[[to_range_array]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT, std::size_t N>
__/{asterisk} see below {asterisk}/__ to_range(CharT (&dest)[N]);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to_range(dest, dest + N)`;
====
[[to_range_count]]
====
[source,cpp,subs=normal]
----
namespace strf {
template <typename CharT>
__/{asterisk} see below {asterisk}/__ to_range(CharT* dest, std::size_t count);

} // namespace strf
----
[horizontal]
Return type and value:: Same as of `to_range(dest, dest + count)`;
====







[[destination_no_reserve]]
=== Class template `destination_no_reserve`
====
[source,cpp,subs=normal]
----
template <typename DestinationCreator, typename FPack = {facets_pack}<>>
class destination_no_reserve
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `DestinationCreator` satisfies <<DestinationCreator,_DestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename DestinationCreator, typename FPack>
class destination_no_reserve
{
public:
    using char_type = typename DestinationCreator::char_type;

    // <<destination_no_reserve_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_no_reserve(Args&&\...);
    constexpr destination_no_reserve(const destination_no_reserve&);
    constexpr destination_no_reserve(destination_no_reserve&&);

    // <<destination_no_reserve_with,facets>>
    template <typename\... FPE>
    destination_no_reserve<DestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_no_reserve<DestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_no_reserve_reserve,size reserve>>
    constexpr destination_calc_size<DestinationCreator, FPack>
    reserve_calc() const &;

    constexpr destination_calc_size<DestinationCreator, FPack>
    reserve_calc() &&;

    constexpr destination_with_given_size<DestinationCreator, FPack>
    reserve(std::size_t) const &;

    constexpr destination_with_given_size<DestinationCreator, FPack>
    reserve(std::size_t) &&;

    constexpr destination_no_reserve&  no_reserve() &;
    constexpr destination_no_reserve&& no_reserve() &&;
    constexpr const destination_no_reserve&  no_reserve() const &;
    constexpr const destination_no_reserve&& no_reserve() const &&;

    // <<destination_no_reserve_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>&
              , const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type>
              , const Args&\...) const;

private:
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack &#95;fpack;                     // exposition only
};

} // namespace strf
----

==== Public member functions

[[destination_no_reserve_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_no_reserve(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr destination_no_reserve(const destination_no_reserve&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_no_reserve(destination_no_reserve&&) = default;
----
Move constructor.
====
[[destination_no_reserve_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_no_reserve< DestinationCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates a `destination_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_no_reserve< DestinationCreator
                      , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                     , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_no_reserve_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) &&;
----
Compile-time requirements::
`DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` object whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve&  no_reserve() &;
constexpr destination_no_reserve&& no_reserve() &&;
constexpr const destination_no_reserve&  no_reserve() const &;
constexpr const destination_no_reserve&& no_reserve() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====

[[destination_no_reserve_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
// Return type::
// - `decltype(std::declval<decltype(&#95;dest&#95;creator.create())&>().finish())` if such type is valid, otherwise `void`
Effect::
. Creates the `{print_dest}` object doing
+
[source,cpp,subs=normal]
----
typename DestinationCreator::destination_type dest{&#95;dest&#95;creator.create()};
----
. For each `arg` in `args\...`, does
+
[source,cpp,subs=normal]
----
using preview_type = {print_preview}<preview_size::no, preview_width::no>;
preview_type preview;
using printer_type = {printer_type}<char_type, preview_type, FPack, Arg>;
printer_type p{ {make_printer_input}<char_type>(preview, &#95;fpack, arg) };
static_cast<const {printer}<char_type>&>(p).print_to(dest);
----
where `Arg` is the type in `Args\...` corresponding to `arg`
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
====
[[destination_no_reserve_tr]]
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect:: __to-do__


////
. Creates/get the `{print_dest}` object doing
+
[source,cpp,subs=normal]
----
typename DestinationCreator::destination_type dest{&#95;dest&#95;creator.create()};
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
----
, where `Arg` is the type in `Args\...` corresponding to `arg`
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
////

====
[[destination_calc_size]]
=== Class template `destination_calc_size`
====
[source,cpp,subs=normal]
----
template <typename SizedDestinationCreator, typename FPack = {facets_pack}<>>
class destination_calc_size;
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedDestinationCreator` satisfies <<SizedDestinationCreator,_SizedDestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedDestinationCreator, typename FPack>
class destination_calc_size
{
public:
    using char_type = typename SizedDestinationCreator::char_type;

    // <<destination_calc_size_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_calc_size(Args&&\...);

    constexpr destination_calc_size(const destination_calc_size&) = default;
    constexpr destination_calc_size(destination_calc_size&&) = default;

    // <<destination_calc_size_with,facets>>
    template <typename\... FPE>
    destination_calc_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_calc_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_calc_size_reserve,size reserve>>
    constexpr destination_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() const &;

    constexpr destination_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() &&;

    constexpr destination_with_given_size<SizedDestinationCreator, FPack>
    reserve(std::size_t) const &;

    constexpr destination_with_given_size<SizedDestinationCreator, FPack>
    reserve(std::size_t) &&;

    constexpr destination_calc_size&  reserve_calc() &;
    constexpr destination_calc_size&& reserve_calc() &&;
    constexpr const destination_calc_size&  reserve_calc() const &;
    constexpr const destination_calc_size&& reserve_calc() const &&;

    // <<destination_calc_size_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack _fpack;                     // exposition only
};

} // namespace strf
----

[[destination_calc_size_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_calc_size(Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>::value` is `true`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
====
====
[source,cpp]
----
constexpr destination_calc_size(const destination_calc_size&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_calc_size(destination_calc_size&&) = default;
----
Move constructor.
====
[[destination_calc_size_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_calc_size< DestinationCreator
                     , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                             , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_calc_size` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is initialized
with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`
====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_calc_size< DestinationCreator
                     , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                             , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_calc_size` object whose `&#95;dest&#95;creator`
is initialized with `std::move(this\->&#95;dest&#95;creator)`, and whose `_fpack` is
initialized with `pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_calc_size_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve<DestinationCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<DestinationCreator, FPack>
reserve(std::size_t size) const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`, and whose `_fpack` is
initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size<DestinationCreator, FPack>
reserve(std::size_t) &&;
----
Compile-time requirements::
`DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_with_given_size` object whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)  from this object,
and whose `_fpack` is initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size&  reserve_calc() &;
constexpr destination_calc_size&& reserve_calc() &&;
constexpr const destination_calc_size&  reserve_calc() const &;
constexpr const destination_calc_size&& reserve_calc() const &&;
----
[horizontal]
Effect:: None.
Return:: This object.
====
[[destination_calc_size_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates an object `preview` of type
  `{print_preview}<preview_size::yes, preview_width::no>`.
+
[source,cpp,subs=normal]
----
using preview_type = {print_preview}<preview_size::yes, preview_width::no>;
preview_type preview;
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
using printer_type = {printer_type}<char_type, preview_type, FPack, Arg>;
printer_type p{ {make_printer_input}<char_type>(preview, &#95;fpack, arg) };
----
. Creates/get the `{print_dest}` object doing
+
[source,cpp,subs=normal]
----
using dest_type = typename DestinationCreator::sized_destination_type;
dest_type dest{&#95;dest&#95;creator.create(preview.<<size_preview_accumulated_size,accumulated_size>>())};
----
. For each `p` object does:
+
[source,cpp,subs=normal]
----
static_cast<const {printer}<char_type>&>(p).print_to(dest);
----
. Returns `dest.finish()` if such expression is valid, which is optional. Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect:: __to-do__

////
. For each `arg` in `args\...`, do
+
[source,cpp,subs=normal]
----
print_preview<preview_size::yes, preview_width::no> preview;
auto p = static_cast< const {printer}<CharT>& >
    ( {printer_type}<CharT, FPack, T>{ fpack, preview, x, {tag}<CharT>{} } )
----
. Calculates the size of the content to be printed according to the
  <<tr_string,tr-string syntax>> and using the `preview` objects
  of the previous step.
. Creates/get the `{print_dest}` object by doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(size)
----
, where `size` is the value calculated in the previous step.
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
////
====

[[destination_with_given_size]]
=== Class template `destination_with_given_size`
====
[source,cpp,subs=normal]
----
template <typename SizedDestinationCreator, typename FPack = {facets_pack}<>>
class destination_with_given_size
----
Compile-time requirements::
- `FPack` is an instance of <<facets_pack,`facets_pack`>>.
- `SizedDestinationCreator` satisfies <<SizedDestinationCreator,_SizedDestinationCreator_>>.
====
==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename SizedDestinationCreator, typename FPack>
class destination_with_given_size
{
public:
    using char_type = typename SizedDestinationCreator::char_type;

    // <<destination_with_given_size_ctor,constructors>>
    template <typename\... Args>
    constexpr destination_with_given_size(std::size_t, Args&&\...);
    constexpr destination_with_given_size(const destination_with_given_size&) = default;
    constexpr destination_with_given_size(destination_with_given_size&&) = default;

    // <<destination_with_given_size_with,facets>>
    template <typename\... FPE>
    destination_with_given_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) const &;

    template <typename\... FPE>
    destination_with_given_size<SizedDestinationCreator, /{asterisk}\...{asterisk}/> with(FPE&&\...) &&;

    // <<destination_with_given_size_reserve,size reserve>>
    constexpr destination_calc_size<SizedDestinationCreator, FPack>
    reserve_calc() const &;

    constexpr destination_calc_size<SizedDestinationCreator, FPack>
    reserve_calc() &&;

    constexpr destination_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() const &;

    constexpr destination_no_reserve<SizedDestinationCreator, FPack>
    no_reserve() &&;

    constexpr destination_with_given_size&  reserve(std::size_t) &;
    constexpr destination_with_given_size&& reserve(std::size_t) &&;
    constexpr destination_with_given_size   reserve(std::size_t) const &;
    constexpr destination_with_given_size   reserve(std::size_t) const &&;

    // <<destination_with_given_size_printing,printing>>
    template <typename\... Args>
    /{asterisk}\...{asterisk}/ operator()(const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const char_type*, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(const std::basic_string<char_type>&, const Args&\...) const;

    template <typename\... Args>
    /{asterisk}\...{asterisk}/ tr(std::basic_string_view<char_type>, const Args&\...) const;

private:
    std::size_t _size                 // exposition only
    DestinationCreator &#95;dest&#95;creator; // exposition only
    FPack _fpack;                     // exposition only
};

} // namespace strf
----
[[destination_with_given_size_ctor]]
===== Constructors
====
[source,cpp]
----
template <typename... Args>
constexpr destination_with_given_size(std::size_t size, Args&&... args);
----
Compile-time requirements::
- `FPack` is https://en.cppreference.com/w/cpp/named_req/DefaultConstructible[_DefaultConstructible_]
- `std::is_constructible<DestinationCreator, Args\...>`, otherwise this constructor does not participate on overload resolution.
Effect::
- Initializes `&#95;dest&#95;creator` with `std::forward<Args>(args)\...`.
- Initializes `_size` with `size`
====
====
[source,cpp]
----
constexpr destination_with_given_size(const destination_with_given_size&) = default;
----
Copy constructor.

Compile-time requirements::
- `FPack` and `DestinationCreator` are
   https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
====
====
[source,cpp]
----
constexpr destination_with_given_size(destination_with_given_size&&) = default;
----
Move constructor.
====
[[destination_with_given_size_with]]
===== Facets
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) const &;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_with_given_size< DestinationCreator
                           , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                                   , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`
, and whose `_fpack` is initialized with `pack(this\->_fpack, std::forward<FPE>(fpe)\...)`

====
====
[source,cpp,subs=normal]
----
template <typename\... FPE>
/{asterisk} see below {asterisk}/ with(FPE&&\...) &&;
----
Compile-time requirements::
- All types in `FPE\...` satisfy <<FacetsPackElement, _FacetsPackElement_>>.
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
Return Type::
+
[source,cpp,subs=normal]
----
destination_with_given_size< DestinationCreator
                           , decltype(<<pack,pack>>( std::declval<const FPack&>()
                                                   , std::forward<FPE>(fpe)\...) ) >
----
Effect:: Creates an `destination_with_given_size` object
whose `_size` is is initialized with this `_size`
, whose `&#95;dest&#95;creator` is initialized with `std::move(&#95;dest&#95;creator)` from this object
, and whose `_fpack` is initialized with
`pack(std::move(this\->_fpack), std::forward<FPE>(fpe)\...)`
====
[[destination_with_given_size_reserve]]
===== Size reserve
====
[source,cpp,subs=normal]
----
constexpr destination_no_reserve<DestinationCreator, FPack> no_reserve() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> no_reserve() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_no_reserve` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> reserve_calc() const &;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `_fpack` is initialized with this `_fpack`.
====
====
[source,cpp,subs=normal]
----
constexpr destination_calc_size<DestinationCreator, FPack> reserve_calc() &&;
----
Compile-time requirements::
- `DestinationCreator` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[_MoveConstructible_]
   and <<SizedDestinationCreator,_SizedDestinationCreator_>>.
- `FPack` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[_CopyConstructible_].
Effect:: Creates an `destination_calc_size` object whose `&#95;dest&#95;creator`
is initialized with `std::move(&#95;dest&#95;creator)` from this object, and whose `_fpack` object is
initialized with `std::move(_fpack)` from this object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size&  reserve(std::size_t size) &;
constexpr destination_with_given_size&& reserve(std::size_t size) &&;
----
[horizontal]
Effect:: assign `size` to `_size`.
Return:: This object.
====
====
[source,cpp,subs=normal]
----
constexpr destination_with_given_size reserve(std::size_t size) const &;
constexpr destination_with_given_size reserve(std::size_t size) const &&;
----
[horizontal]
Effect:: Creates an `destination_with_give_size` object
whose `_size` is initialized with `size`,
whose `&#95;dest&#95;creator` is initialized with this `&#95;dest&#95;creator`,
and whose `facets_pack` object with this `_fpack`.
====
[[destination_with_given_size_printing]]
===== Printing
====
[source,cpp,subs=normal]
----
template <typename\... Args>
/{asterisk}\...{asterisk}/ operator()(const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
. Creates/get the `{print_dest}` object doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(_size)
----
. For each `arg` in `args\...` does:
+
[source,cpp,subs=normal]
----
using preview_type = {print_preview}<preview_size::no, preview_width::no>;
preview_type preview;
using printer_type = {printer_type}<char_type, preview_type, FPack, Arg>;
printer_type p{ {make_printer_input}<char_type>(preview, &#95;fpack, arg) };
static_cast<const {printer}<char_type>&>(p).print_to(dest);
----
, where `Arg` is the type in `Args\...` corresponding to `arg`
. Returns `dest.finish()` if such expression is valid, which is optional.
  Otherwise the return type is `void`.
====
====
[source,cpp,subs=normal]
----
template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const char_type* tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( const std::basic_string_view<char_type>& tr_string
          , const Args&\... args) const;

template <typename ... Args>
/{asterisk}\...{asterisk}/ tr( std::basic_string_view<char_type> tr_string
          , const Args&\... args) const;
----
Compile-time requirements::
- All types in `Args\...` are <<Printable,_Printable_>>.
Effect::
__to-do__
////
. Creates/get the `{print_dest}` object doing
+
[source,cpp,subs=normal]
----
decltype(auto) dest = &#95;dest&#95;creator.create(_size)
----
. For each `arg` in `args\...`, creates a printer object by doing:
+
[source,cpp,subs=normal]
----
auto p = static_cast< const {printer}<CharT>& >
    ( {printer_type}<CharT, FPack, T>{fpack, preview, x, chtag} )
----
, where `preview` is an instance of `preview<false, false>`,
abs `chtag` is an expression of type `{tag}<CharT>`.
. Prints into `dest` the content according the <<tr_string,tr-string syntax>>
  and using the `p` objects.
. Returns `dest.finish()` if such expression is valid ( which is optional ).
////
====

[[DestinationCreator]]
=== Type requirement _DestinationCreator_
Given

- `char_type`, a character type
- `X`, an  _DestinationCreator_ type for `char_type`
- `x`, an expression of type `X` or `const X`

The following must hold:

- `X` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[CopyConstructible]
- `X` has a member type alias `X::char_type` defined as `char_type`
- `X` has the `X::destination_type` that is a type alias to a concrete type that is derives
   from `{print_dest}<X::char_type>`

And the following expression must be well-formed:

[[DestinationCreator_create]]
====
[source,cpp]
----
typename X::destination_type{x.create()}
----
====

[[SizedDestinationCreator]]
=== Type requirement _SizedDestinationCreator_
Given

- `char_type`, a character type
- `size`, a value of the `std::size_t`
- `X`, an  _SizedDestinationCreator_ type for `char_type`
- `x`, an expression of type `X` or `const X`

The following must hold:

- `X` is https://en.cppreference.com/w/cpp/named_req/CopyConstructible[CopyConstructible]
- `X` has a member type alias `T::char_type` defined as `char_type`
- `X` has the `X::sized_destination_type` that is a type alias to a concrete type that derives
   from `print_dest<X::char_type>`

And the following expression must be well-formed:

[[SizedDestinationCreator_create]]
====
[source,cpp]
----
typename X::sized_destination_type{x.create(size)}
----
====

