////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:facets_pack: <<facets_pack,facets_pack>>
:use_facet: <<use_facet,use_facet>>
:facet_category: <<facet_category,facet_category>>
:facet_traits: <<facet_traits,facet_traits>>
:FacetCategory: <<FacetCategory, FacetCategory>>
:FacetsPackElement: <<FacetsPackElement, FacetsPackElement>>
:remove_cvref_t: link:https://en.cppreference.com/w/cpp/types/remove_cvref[remove_cvref_t]
:UnaryTypeTrait: link:https://en.cppreference.com/w/cpp/named_req/UnaryTypeTrait[UnaryTypeTrait]

== facets_pack

[[facets_pack]]
=== Class template `facets_pack`

====
[source,cpp]
----
template <typename ... FPE>
class facets_pack;
----
Compile-time requirements:: All types in `FPE\...` satisfy
 <<FacetsPackElement, _FacetsPackElement_>>.
====

==== Member functions
===== Constructors
====
[source,cpp]
----
constexpr facets_pack(const facets_pack& other) = default;
----
Effects:: Initializes each element in this object with the corresponding element in `other`
Compile-time requirements:: `(std::is_copy_constructible_v<FPE> && \...)` is `true`,
      otherwise this constructor does not participate in overload resolution.
====
====
[source,cpp]
----
constexpr facets_pack(facets_pack&& other) = default;
----
Effects:: Initializes each element from the
          rvalue reference of the corresponding element in `other`
Compile-time requirements:: `(std::is_move_constructible_v<FPE> && \...)` is `true`, otherwise this
          constructor does not participate in overload resolution.
====
====
[source,cpp]
----
constexpr facets_pack() = default;
----
Effects:: Default-initializes each element
Compile-time requirements:: `(std::is_default_constructible_v<FPE> && \...)` is `true`, otherwise this
          constructor does not participate in overload resolution.
====
====
[source,cpp]
----
template <typename... U>
constexpr explicit facets_pack(U&&... u)
----
Effects:: Initializes each element with the corresponding value in `std::forward<U>(u)\...`.
Compile-time requirements:: This constructor does not participate in overload resolution, unless the following conditions are met
- `sizeof\...(U) != 0` is `true`
- `sizeof\...(U) == sizeof\...(FPE)` is `true`
- `( std::is_constructible_v<FPE, U> && \... )` is `true`
- if `sizeof\...(U) == 1` is `true`, then `std::{remove_cvref_t}<U...>` is not `facets_pack<FPE....>`.
====
===== Assignment operators (deleted)
====
[source,cpp]
----
   facets_pack& operator=(const facets_pack&) = delete
   facets_pack& operator=(facets_pack&&) = delete;
----
Assignments are deleted because it is unclear what would be the correct
behavior when there is a reference type in `FPE\...`.
====

[[pack]]
=== Function template `pack`
====
[source,cpp]
----
template <typename ... T>
constexpr /* see below */ pack(const T& ... args)
----
Return type:: `{facets_pack}<std::remove_cvref_t<T>>\...>`
Return value:: A `{facets_pack}` object initialized with `std::forward<T>(args)\...`
====

=== Function template `use_facet` [[use_facet]]
====
[source,cpp]
----
template <typename FCat, typename Tag, typename ... T>
constexpr decltype(auto) use_facet(const facets_pack<T...>& fp);
----
Effects:: If <<has_facet, `has_facet<FCat, Tag>(fp)`>> returns `true` then
          returns <<do_get_facet,`do_get_facet<FCat, Tag>(fp)`, otherwise
          return `FCat::get_default()`.
Compile-time requirements::  `FCat` is a _{FacetCategory}_ type.
====

[[has_facet]]
=== Hypothetical function template `has_facet`
NOTE: This function template does not exist in this library.
       It is only documented to help to explain the
       <<use_facet, `use_facet`>> function template.
====
[source,cpp]
----
template <typename FCat, typename Tag, typename FPE>
constexpr bool has_facet(const FPE& fpe)
----
Effects::
- If `FPE` is an instance of <<facets_pack, `facets_pack`>>, then returns wheter there
  is any elemente `elm` in `fpe` such that `has_facet<FCat, Tag>(elm)`
  is `true`.
- If `FPE` is an instance of <<constrained_fpe, `constrained_fpe<FPE, Filter>`>>,
  then returns `Filter<Tag>::value && has_facet<FCat, Tag>(fpe.get())`.
- If `FPE` is a  <<Facet,_Facet_>> type, returns `std::is_same_v<FCat, {facet_category}<FPE>>`

Compile-time requirements::
- `FCat` is a _{FacetCategory}_ type.
- `FPE` satisfies <<FacetsPackElement, _FacetsPackElement_>>.
====


[[do_get_facet]]
=== Hypothetical function template `do_get_facet`
NOTE: This function template is not part of the library.
      It is only documented to help to explain the
      <<use_facet,`use_facet`>> function template
====
[source,cpp]
----
template <typename FCat, typename Tag, typename FPE>
constexpr decltype(auto) do_get_facet(const FPE& fpe);
----
Compile-time requirements::
- `FCat` satisfies _{FacetCategory}_.
- `FPE` satisfies <<FacetsPackElement,_FacetsPackElement_>>.
- `has_facet<FCat, Tag>(fpe)` is `true`.
====

[[constrained_fpe]]
=== Class template `constrained_fpe`

====
[source,cpp]
----
template <template <class> class Filter, typename FPE>
class constrained_fpe;
----
The class template `constrained_fpe` is designed to be used in
<<facets_pack,`facets_pack`>>. `constrained_fpe<Filter, FPE>`
holds a value of `FPE` that will only be returned by
<<use_facet, ``use_facet<Category, Tag>``>> if
`Filter<Tag>::value` is `true`.

Compile-time requirements::
- `Filter` is a __{UnaryTypeTrait}__. For any type `T`, the expression
  `Filter<T>::value` must be well-formed and convertible to `bool`.
- `FPE` satisfies <<ConstrainableFacetsPackElement,_ConstrainableFacetsPackElement_>>.
====

==== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <template <class> class Filter, typename FPE>
class constrained_fpe
{
public:
    // <<constrained_fpe_constructor,constructors>>
    constexpr constrained_fpe(const constrained_fpe&) = default;
    constexpr constrained_fpe(constrained_fpe&& other) = default;
    constexpr constrained_fpe() = default;

    template <typename U>
    constexpr constrained_fpe(U&&);

    // <<constrained_fpe_element_access,element access>>
    constexpr const FPE& get() const;

private:
    FPE element; // exposition only;
};

} // namespace strf
----

==== Member functions
[[constrained_fpe_constructor]]
===== Constructors

====
[source,cpp]
----
constexpr constrained_fpe(const constrained_fpe& other);
----
Effect:: Initializes the element of the `constrained_fpe` from
     the const reference of the element of `other`.
Compile-time requirements:: `std::is_copy_constructible<FPE>::value` is `true`,
      otherwise this constructor does not participate in overload resolution.
====
====
[source,cpp]
----
constexpr constrained_fpe(constrained_fpe&& other);
----
Effect:: Initializes the element of the `constrained_fpe` from
     the rvalue reference of the element of `other`.
Compile-time requirements:: `std::is_move_constructible<FPE>::value` is `true`,
      otherwise this constructor does not participate in overload resolution.

====
====
[source,cpp]
----
constexpr constrained_fpe();
----
Effect:: Default-initializes `element`.
Compile-time requirements:: `std::is_default_constructible<FPE>::value` is `true`,
      otherwise this constructor does not participate in overload resolution.
====

====
[source,cpp]
----
template <typename U>
constexpr explicit constrained_fpe(U&& arg);
----
Effect:: Initializes element with `std::forward<U>(arg)`.
Compile-time requirements:: `std::is_constructible<FPE, U>::value` is `true`,
      otherwise this constructor does not participate in overload resolution.
====

[[constrained_fpe_element_access]]
===== Element access

====
[source,cpp]
----
constexpr const FPE& get() const;
----
Effect:: Return the stored element;
====
=== Function template `constrain` [[constrain]]
====
[source]
----
template <template <class> class Filter, typename T>
constexpr constrained_fpe<Filter, U> constrain(const T& arg);
----
`constrain` is just a syntatic sugar to create a <<constrained_fpe, `constrained_fpe`>> object.

Return type:: `constrained_fpe<Filter, U>`, where `U` is
                `std::remove_cv_t<std::remove_reference_t<T>>`.
Return value:: `constrained_fpe<Filter, U>{ std::forward<T>(arg) }`
Compile-time requirements::
`T` is such that `U` satisfies <<FacetsPackElement, _FacetsPackElement_>>.
====

[[FacetsPackElement]]
=== Type requirement _FacetsPackElement_
A given type `F` satisfies _FacetsPackElement_ if, and only if, one of the following conditions is true:

- `F` is a <<Facet,_Facet_>> type.
- `F` is an instance of <<facets_pack,`facets_pack`>>.
- `F` is an instance of <<constrained_fpe,`constrained_fpe`>>.

////
- `F` is `const `F2&`, where `F2` satisfies one of the previous requirements.
- `F` is `const `F2&`, where `F2` satisfies <<Facet, _Facet_>>,
  and `facet_stored_by_value<F2>` is `false`.
////

[[ConstrainableFacetsPackElement]]
=== Type requirement _ConstrainableFacetsPackElement_
A given a type `F` is a _ConstrainableFacetsPackElement_ if, and only if,
one of the following conditions is true:

- `F` is a  <<Facet,_Facet_>> type and  `{facet_category}<F>::constrainable` is `true`.
- `F` is `facets_pack<F2\...>` and all types in `F2\...` are _ConstrainableFacetsPackElement_.
- `F` is an instance of <<constrained_fpe,`constrained_fpe`>>.

////
- If `F` is `const F2&`, then `F2` satifies the _ConstrainableFacetsPackElement_
  requirements.
////

[[Facet]]
=== Type requirement _Facet_
A given a type `F` satisfies `Facet` if all of the following conditions are met:

////
- If `F` is abstract or not _CopyConstructible_, then
  <<facet_stored_by_value `facet_stored_by_value<F>`>>
  must be `false`.
////
- `F` is https://en.cppreference.com/w/cpp/named_req/MoveConstructible[__MoveConstructible__]
- `{facet_category}<F>` satisfies the _{FacetCategory}_ requirements.

[[FacetCategory]]
=== Type requirement _FacetCagory_
A given a type `FCat` satisfies `FacetCategory` if:

- `FCat` has a static member function named `get_default` that takes
  no argument and whose return type is either `F` or `const F&`,
  where `F` is a type that satisfies the requirements associated to
  `FCat`.
- `FCat` has a member named `constrainable` that is a static constexpr
  value convertible to `bool`. ( If this value is `false` then
  the facets associated `FCat` can not be <<constrained_fpe,constrained>> ).

[[facet_traits]]
=== Class template `facet_traits`

This class template provides the <<Facet,Facet>> informations.
If you create a new facet, you can either define such informations as
members of the facet, or specialize `facet_traits`.

[source]
----
template <typename F>
class facet_traits
{
public:
    using category = /* Facet::category or void */;
};
----
==== Public members

====
[source]
----
typename /* */ category;
----
Same as `Facet::category` if such member exist and is a type,
otherwise it is an alias to `void`.
====
==== Specialization
====
[source]
----
template <typename F>
class facet_traits<const F>
{
public:
    using category = typename facet_traits<F>::category;
};
----
====

[[facet_category]]
=== Type alias `facet_category`
`facet_category` is just a syntatic sugar:
====
[source]
----
template <typename Facet>
using facet_category = facet_traits<Facet>::typename category;
----
====
