////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:rank: <<rank,rank>>
:tag: <<tag,tag>>
:destination_no_reserve: <<destination,destination_no_reserve>>
:OutbuffCreator: <<OutbuffCreator,OutbuffCreator>

:basic_outbuff: <<outbuff_hpp#basic_outbuff,basic_outbuff>>
:facet_traits: <<facet_traits,facet_traits>>

== Miscellaneous

[[lettercase]]
=== The `lettercase` facet

[source,cpp,subs=normal]
----
namespace strf {

enum class lettercase { lower = /{asterisk}...{asterisk}/, mixed = /{asterisk}...{asterisk}/, upper = /{asterisk}...{asterisk}/ };

constexpr lettercase lowercase = lettercase::lower;
constexpr lettercase mixedcase = lettercase::mixed;
constexpr lettercase uppercase = lettercase::upper;

struct lettercase_c {
    static constexpr bool constrainable = true;
    constexpr static lettercase get_default() noexcept
    {
        return lettercase::lower;
    }
};

template <>
struct {facet_traits}<lettercase> {
    using category = lettercase_c;
};

} // namespace strf
----
=== Type traits
The table below list class templates that satisfy
https://en.cppreference.com/w/cpp/named_req/UnaryTypeTrait[UnaryTypeTrait].
They are created to be used in the `constrain` function template to filter
printable types.

[cols="1,4"]
|===
|`is_int_number`
| matches `short`, `int`, `long`, `long long` and the corresponding unsigned types

|`is_char`
| matches `char`, `char8_t`, `wchar_t`, `char16_t`, and `char32_t`

|`is_string`
| matches strings.
|===

__to-do__

=== Class template `tag` [[tag]]

[source,cpp,subs=normal]
----
namespace strf {

template <typename\... >
struct tag
{
    explicit tag() = default;
};

template <typename T>
struct tag<T>
{
    explicit constexpr STRF_HD tag() noexcept { }
    using type = T;
};

} // namespace strf
----

////
=== Class template `rank` [[rank]]

[source,cpp,subs=normal]
----
namespace strf {

template <std::size_t N>
struct rank: rank<N - 1>
{
    explicit rank() = default;
};

template <>
struct rank<0>
{
    explicit rank() = default;
};

} // namespace strf
----
////

=== `Outbuff` writing functions

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , std::size_t count );

template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , const CharT{asterisk} data_end );

void write({basic_outbuff}<char>& ob, const char{asterisk} cstr);

void write({basic_outbuff}<wchar_t>& ob, const wchar_t{asterisk} cstr);

} // namespace strf
----


[[basic_outbuff_write_range]]
====
[source,cpp,subs=normal]
----
template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , const CharT{asterisk} data_end );
----
[horizontal]
Effect:: Writes the the range [ `data`, `data_end` ) into `ob`, calling `ob.recycle()`
         as many times as necessary.
====
[[basic_outbuff_write_size]]
====
[source,cpp,subs=normal]
----
template <typename CharT>
void write( {basic_outbuff}<CharT>& ob
          , const CharT{asterisk} data
          , std::size_t data_size );
----
[horizontal]
Effect:: Equivalent to `write(ob, data, data + data_size)`
====
[[basic_outbuff_write_cstr]]
====
[source,cpp]
----
void write( {basic_outbuff}<char>& ob
          , const char* cstr );
----
[horizontal]
Effect:: Equivalent to `write(ob, cstr, std::strlen(cstr))`
====

[[basic_outbuff_write_wcstr]]
====
[source,cpp,subs=normal]
----
void write( {basic_outbuff}<wchar_t>& ob
          , const wchar_t{asterisk} wcstr );
----
[horizontal]
Effect:: Equivalent to `write(ob, wcstr, std::wstrlen(wcstr))`
====

