////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

[[main]]
= `<strf/to_cfile.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <strf/to_cfile.hpp>
:toclevels: 1
:icons: font

:destination: <<destination_hpp#destination,destination>>
:destination_space_after_flush: <<destination_hpp#destination_space_after_flush,destination_space_after_flush>>
:narrow_cfile_writer: <<narrow_cfile_writer,narrow_cfile_writer>>
:wide_cfile_writer: <<wide_cfile_writer,wide_cfile_writer>>

:printer_no_reserve: <<strf_hpp#printer_no_reserve,printer_no_reserve>>
:DestinationCreator: <<strf_hpp#DestinationCreator,DestinationCreator>>

NOTE: This header file includes `<<strf_hpp#,<strf.hpp>>>`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, std::size_t BuffSize>
class narrow_cfile_writer final: public destination<CharT>
{ /{asterisk}\...{asterisk}/ };

class wide_cfile_writer final: public destination<wchar_t>
{ /{asterisk}\...{asterisk}/ };

template <typename CharT = char>
/{asterisk} \... {asterisk}/  to(std::FILE{asterisk});

/{asterisk} \... {asterisk}/ wto(std::FILE{asterisk});

} // namespace strf
----

[[narrow_cfile_writer]]
== Class template `narrow_cfile_writer`
=== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, std::size_t BuffSize>
class narrow_cfile_writer final: public {destination}<CharT> {
public:
    explicit narrow_cfile_writer(std::FILE{asterisk} dest);

    narrow_cfile_writer(const narrow_cfile_writer&) = delete;
    narrow_cfile_writer(narrow_cfile_writer&&) = delete;
    ~narrow_cfile_writer();

    void recycle_buffer() noexcept;

    struct result  {
        std::size_t count;
        bool success;
    };

    result finish();

private:
    CharT buffer[BuffSize]; // exposition only
};

} // namespace strf
----
=== Public member functions
====
[source,cpp]
----
~narrow_cfile_writer();
----
[horizontal]
Effect:: Calls `recycle_buffer()`
====
====
[source,cpp]
----
void recycle_buffer() override;
----
[horizontal]
Effects::
- If `good() == true`, calls `std::fwrite(p0, buffer_ptr() - p0, sizeof(CharT), dest)`,
    where `dest` is the `FILE{asterisk}` used to initialize this object, and
    `p0` is value `buffer_ptr()` would return before any call to `advance` and `advance_to`
    since the last call to `recycle_buffer()`, or since this object's contruction,
    whatever happened last.
-  If the returned value of `std::fwrite` is less than `(buffer_ptr() - p0)`, calls `set_good(false)`.
-  Calls `set_buffer_ptr` and/or `set_buffer_end`.
Postconditions:: `<<destination_hpp#output_buffer_buffer_space,buffer_space>>() >= BuffSize`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle_buffer()` and `set_good(false)`.
Return value::
- `result::count` is the sum of values returned by all calls `std::fwrite` done by this object.
- `result::success` is the value `good()` would return before this call to `finish()`
====


[[wide_cfile_writer]]
== Class template `wide_cfile_writer`
=== Synopsis
[source,cpp,subs=normal]
----
namespace strf {

class wide_cfile_writer final: public {destination}<wchar_t> {
public:
    explicit wide_cfile_writer(std::FILE{asterisk} dest);

    wide_cfile_writer(const narrow_cfile_writer&) = delete;
    wide_cfile_writer(narrow_cfile_writer&&) = delete;
    ~wide_cfile_writer();

    void recycle_buffer() noexcept;

    struct result {
        std::size_t count;
        bool success;
    };

    result finish();
};

} // namespace strf
----
=== Public member functions
====
[source,cpp]
----
~wide_cfile_writer();
----
[horizontal]
Effect:: Calls `recycle_buffer()`
====
====
[source,cpp]
----
void recycle_buffer() override;
----
[horizontal]
Effects::
- If `good() == true`, for each character `ch` in the range [ `p0`, `buffer_ptr()` ) calls `std::fputwc(ch, dest)`, until WEOF is returned or the whole range is read, where `dest` is the `FILE{asterisk}` used to initialize this object, and `p0` is the value `buffer_ptr()` would return before any call to `advance` and `advance_to` since the last call to `recycle_buffer()`, or since this object's contruction, whatever happened last.
- If `std::fputwc` returns `WEOF`, calls `set_good(false)`.
- Calls `set_buffer_ptr` and/or `set_buffer_end`.
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle_buffer()` and `set_good(false)`.
Return value::
- `result::count` is the number of calls to `std::fputwc` by this object that did not return WEOF .
- `result::success` is the value `good()` would return before this call to `finish()`
====

[[to]]
== Function template `to`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT = char>
__/{asterisk} see below {asterisk}/__ to(std::FILE{asterisk} dest);

} // namespace strf
----
[horizontal]
Return type:: `{printer_no_reserve}<DestCreator>`, where `DestCreator` is an
           implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{narrow_cfile_writer}< CharT, {destination_space_after_flush} >{dest}
----

[[wto]]
== Function `wto`

[source,cpp,subs=normal]
----
namespace strf {

__/{asterisk} see below {asterisk}/__ wto(std::FILE{asterisk} dest);

} // namespace strf
----
[horizontal]
Return type:: `{printer_no_reserve}<DestCreator>`, where `DestCreator`
       is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object `&#95;dest&#95;creator`
       is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{wide_cfile_writer}<CharT, Traits>{dest}
----
