////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

[[main]]
= `<strf/to_streambuf.hpp>` Header file reference
:source-highlighter: prettify
:sectnums:
:toc: left
:toc-title: <strf/to_streambuf.hpp>
:toclevels: 1
:icons: font

:destination: <<destination_hpp#destination,destination>>
:destination_space_after_flush: <<destination_hpp#destination_space_after_flush,destination_space_after_flush>>
:basic_streambuf_writer: <<basic_streambuf_writer,basic_streambuf_writer>>
:printer_no_reserve: <<strf_hpp#printer_no_reserve,printer_no_reserve>>
:DestinationCreator: <<strf_hpp#DestinationCreator,DestinationCreator>>

NOTE: This header file includes `<<strf_hpp#,<strf.hpp>>>`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, typename Traits = std::char_traits<CharT> >
class basic_streambuf_writer final: public destination<CharT>
{ /{asterisk}\...{asterisk}/ };

using streambuf_writer  = basic_streambuf_writer<char>;
using wstreambuf_writer = basic_streambuf_writer<wchar_t>;

template <typename CharT, typename Traits>
/{asterisk} \... {asterisk}/ to(std::basic_streambuf<CharT, Traits>& dest);

template <typename CharT, typename Traits>
/{asterisk} \... {asterisk}/ to(std::basic_streambuf<CharT, Traits>* dest);

} // namespace strf
----

[[basic_streambuf_writer]]
== Class template `basic_streambuf_writer`
=== Synopsis
[source,cpp]
----
namespace strf {

template <typename CharT, typename Traits = std::char_traits<CharT> >
class basic_streambuf_writer final: public destination<CharT> {
public:
    explicit basic_streambuf_writer(std::basic_streambuf<CharT, Traits>& dest);
    explicit basic_streambuf_writer(std::basic_streambuf<CharT, Traits>* dest);
    basic_streambuf_writer(const basic_streambuf_writer&) = delete;
    basic_streambuf_writer(basic_streambuf_writer&&) = delete;
    ~basic_streambuf_writer();

    void recycle_buffer() override;
    struct result {
        std::streamsize count;
        bool success;
    };
    result finish();
};

// Global type aliases

using streambuf_writer
    = basic_streambuf_writer<char, std::char_traits<char> >;

using wstreambuf_writer
    = basic_streambuf_writer<wchar_t, std::char_traits<wchar_t> >;

} // namespace strf
----
=== Public member functions

====
[source,cpp]
----
~basic_streambuf_writer();
----
[horizontal]
Effect:: Calls `recycle_buffer()`
====

====
[source,cpp]
----
void recycle_buffer() override;
----
[horizontal]
Effects::
- If `good()` is `true` then calls `dest.sputn(p0, buffer_ptr() - p0)`, where `dest` is the reference this object was initialized with, and `p0` is the return value of `buffer_ptr()` before any call to `advance` and `advance_to` since the last call to `recycle_buffer()`, or since this object's contruction, whatever happened last.
- If the returned value of `dest.sputn` is less then `buffer_ptr() - p0`, calls `set_good(false)`.
- Calls `set_buffer_ptr` and/or `set_buffer_end`.
Postconditions:: `buffer_space() >= {destination_space_after_flush}`
====
====
[source,cpp]
----
result finish();
----
[horizontal]
Effects::
- Calls `recycle_buffer()` and `set_good(false)`.
Return value::
- `result::count` is the sum of the values returned by `dest.sputn`.
- `result::success` is the value `good()` would return before this call to `finish()`.
====

[[to]]
== Function templates `to`

[source,cpp,subs=normal]
----
namespace strf {

template <typename CharT, typename Traits>
__/{asterisk} see below {asterisk}/__ to(std::basic_streambuf<CharT, Traits>& dest);

template <typename CharT, typename Traits>
__/{asterisk} see below {asterisk}/__ to(std::basic_streambuf<CharT, Traits>* dest);


} // namespace strf
----
[horizontal]
Return type:: `{printer_no_reserve}<DestCreator>`, where `DestCreator`
         is an implementation-defined type that satifies __{DestinationCreator}__.
Return value:: An object whose `DestCreator` object  `&#95;dest&#95;creator`
is such that `&#95;dest&#95;creator.create()` returns
+
[source,cpp,subs=normal]
----
{basic_streambuf_writer}<CharT, Traits>{dest}
----