////
Copyright (C) (See commit logs on github.com/robhz786/strf)
Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt)
////

:numpunct:      <<quick_reference#numpunct,numpunct>>
:destination:    <<destination_hpp#destination,destination>>
:UnaryTypeTrait: link:https://en.cppreference.com/w/cpp/named_req/UnaryTypeTrait[UnaryTypeTrait]

= Tutorial of the Strf library
:source-highlighter: prettify
:sectnums:
:sectnumlevels: 2
:icons: font
:toc: left
:toc-title: Tutorial

== Syntax [[syntax]]

image::syntax.svg[width=660,align=center]

The __target__ expression is a customization point and it determinates
where the content goes to as well as the return type of the above whole expression.
The library provides <<quick_reference#targets,many options>> to be used
as the __target__, and you can
<<howto_add_destination#create_target,create your own>>.
However, for convenience, most code samples in this tutorial use `to_string`:
[source,cpp]
----
#include <strf/to_string.hpp>

void sample() {
    int x = 200;
    std::string str = strf::to_string(x, " in hexadecimal is ", strf::hex(x));
    assert(str == "200 in hexadecimal is c8");
}
----

////
You can see that there is not format string, as in `printf`.
Instead, __format functions_ ( as the `hex` above ) specify formatting.
So in order to use translation tool like
https://en.wikipedia.org/wiki/Gettext[gettext] you need to use an alternative
syntax, which employs what is called here as the "Tr-string":
////

You can see that there is no format string here, as there is in `printf`.
Instead, __format functions__ ( like `hex` above ) specify formatting.
The expression `strf::hex(x)` is equivalent to `strf::fmt(x).hex()`.
The return of `strf::fmt(x)` is an object containing the value of `x` in addition to
format information which can be edited with member ( format ) functions
following the
https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Named_Parameter[named parameter idiom]
, like this: `strf::fmt(255).hex().p(4).fill(U'.') > 10`

To use a translation tools like
https://en.wikipedia.org/wiki/Gettext[gettext],
you need to use the `tr` function,
which employs what is called here as the __tr-string__:

////
Strf does not have a format string, as `printf` has. But that doesn't mean you
can't use i18n tools like https://en.wikipedia.org/wiki/Gettext[gettext].
You just need to use an alternative syntax, which employs what is called here as
the <<quick_reference#tr_string,tr-string>>:
////

[source,cpp,subs=normal]
----
auto s = strf::to_string.tr("{} in hexadecimal is {}", x, strf::hex(x));
----

The `reserve`, `no_reseve` and `reserve_calc` functions are only available for some
__targets__, `to_string` being one of them.
Using `reserve(space)` causes the destination to reserve enough space
to store `space` characters. `reserve_calc()` has the same effect,
except that it calculates the number of characters for you.

[[facets]]
== Facets

The `with` function receives __facet objects__, which complement
format functions, since they also influence how things are stringified.
We are *not* talking here about the facets used in `std::ostream`.
In Strf, facets have a different design ( more based on static rather
than dynamic polymorphism ),
and are not necessarily related to localization.

An example of a facet is the `lettercase` enumeration:

[source,cpp]
----
namespace strf {
  enum class lettercase { /* ... */ };
  constexpr lettercase lowercase = /* ... */;
  constexpr lettercase mixedcase = /* ... */;
  constexpr lettercase uppercase = /* ... */;
}
----

It affects numeric and boolean values:
[source,cpp]
----
auto str_uppercase = strf::to_string.with(strf::uppercase)
    ( true, ' ', *strf::hex(0xab), ' ', 1.0e+50 );

auto str_mixedcase = strf::to_string.with(strf::mixedcase)
    ( true, ' ', *strf::hex(0xab), ' ', 1.0e+50 );

assert(str_uppercase == "TRUE 0XAB 1E+50");
assert(str_mixedcase == "True 0xAB 1e+50");
----

[[facet_categories]]
=== Facet categories

In this library, the term _facet_ always refers to types. So the type
`strf::lettercase` is a facet, while `strf::uppercase` is a __facet value__
( or you could call it a __facet object__, which make more sense when the facet is a class or struct ).
In addition, a facet is always associated to one ( and only one ) __facet category__,
and several facets can belong to the same category.

// For each facet category there is class or struct
// with a public static member function `get_default()` that
// returns the default facet value of such facet category.
// By convention, the name of such class or struct is the name of the
// category, and it has the "`_c`" suffix.
// For example, the category of `strf::lettercase` is `strf::lettercase_c`,
// and `strf::lettercase_c::get_default()` returns  `strf::lowercase`.
// The <<strf_hpp#facet_traits,`facet_traits`>>
// struct template provides way to programmatically obtain the category
// a given facet.


For each facet category there is class or struct that defines it.
By convention, its name has the "`_c`" suffix.
Also, it has a public static member function named `get_default()` that
returns the default facet value of the category.
For example, the category of `strf::lettercase` is
`<<strf_hpp#lettercase,strf::lettercase_c`>>,
and `strf::lettercase_c::get_default()` returns  `strf::lowercase`.

The <<strf_hpp#facet_traits,`facet_traits`>>
struct template provides way to programmatically obtain the category
a given facet.

Informaly ( perhaps in future it will be formal thanks to C++20 Concepts ),
for each facet category there is a list of requirements a type
must satisfy to be a facet of the category. In the case of `strf::lettercase_c`,
the requirement is, well, simply to be the `strf::lettercase` type.
( but others facet categories can be more elaborated ).


//  However other categories require the facet to
// contain member functions with expe signatures, effects,
// preconditions, posconditions and so on.

////
If you ever need to create your own facet category ( in
case you need to a new printable type ),

One precondition for all facets, regardless of the category,
is to be move-constructible.

The design of the facets currently provided by the library
////

The design of facets varies a lot according to their categories.
But all facets currently available in the library are small
( in terms of `sizeof` ) and have fast copy constructors.
In addition, most of them can be instantiated as `constexpr` values.

Since Strf is designed for extensibility, if you ever decide to
<<howto_add_printable_types#,add a new printable type>>,
you can also create new facet categories for it,
as well as making it (or not) affected by the some of the existing ones.

You can see a list of the current facets categories <<quick_reference#facets,here>>.

[[constrained_facets]]
=== Constrained facets

You can constrain a facet object to a specific group of input types:
[source,cpp]
----
auto str = strf::to_string
    .with(strf::constrain<std::is_floating_point>(strf::uppercase))
    ( true, ' '*strf::hex(0xab), ' ', 1.0e+50 );

assert(str == "true 0xab 1E+50");
----
, or to a group of arguments:
[source,cpp]
----
auto str = strf::to_string
    ( true, ' ', 1.0e+50, " / "
    , strf::with(strf::uppercase) (true, ' ', 1.0e+50, " / ")
    , true, ' ', 1.0e+50 );

assert(str == "true 1e+50 / TRUE 1E+50 / true 1e+50 );
----
When there are multiple facets objects of the same <<facet_categories,_category_>>,
the order matters. The later one wins:
[source,cpp]
----

auto fa = strf::mixedcase;
auto fb = strf::constrain<std::is_floating_point>(strf::uppercase);

using namespace strf;
auto str_ab = to_string .with(fa, fb) (true, ' ', *hex(0xab), ' ', 1e+9);
auto str_ba = to_string .with(fb, fa) (true, ' ', *hex(0xab), ' ', 1e+9);

// In str_ab, fb overrides fa, but only for floating points
// In str_ba, ba overrides fb for all types, so fb has no effect.

assert(str_ab == "True 0xAB 1E+9");
assert(str_ba == "True 0xAB 1e+9");
----

You can see that the template argument passed to `constrain` is a
__{UnaryTypeTrait}__, __i.e.__, a type template with a static
constexpr boolean member variable named `value`. The type the library
passes to this __UnaryTypeTrait__ is called the
__representative type__ of the printable type, which is usually
the same as the printable type itself, but not always.
For example, in the case of strings, it is
`strf::string_input_tag<__char_type__>`.
The representative of each printable type is documented
in the API reference, in the section
<<strf_hpp#printable_types_list,"List of printable types">>,
but it can also be obtained programmatically, with
`<<strf_hpp#representative_of_printable,representative_of_printable>>`
type alias template.

[[facets_pack]]
=== Facets packs

To avoid retyping all the facets objects that you commonly use,
you can store them into a <<strf_hpp#facets_pack,`facets_pack`>>,
which you can create with the <<strf_hpp#pack,`pack`>> function template:

[source,cpp,subs=normal]
----
constexpr auto my_facets = strf::pack
    ( strf::mixedcase
    , strf::constrain<strf::is_bool>(strf::uppercase)
    , strf::{numpunct}<10>{3}.thousands_sep(U'.').decimal_point(U',')
    , strf::{numpunct}<16>{4}.thousands_sep(U'\'')
    , strf::<<strf_hpp#static_charset_constexpr,windows_1252>><char> );


auto str1 = strf::to_string.with(my_facets) (/{asterisk} \... {asterisk}/);
// \...
auto str2 = strf::to_string.with(my_facets) (/{asterisk} \... {asterisk}/);
// \...
----

The `facets_pack` class template is more similar to `std::tuple` than to `std::locale`.
It stores all the facets objects by value, and extracting one from it (
with the `<<strf_hpp#use_facet,strf::use_facet>>` function template ) is just as fast as
calling a trivial getter function.

Any value that can be passed to the `with` function, can also be passed to `pack`,
and vice-versa. This means a `facets_pack` can contain another `facets_pack`.
So the expression:
[source,cpp,subs=normal]
----
__target__.with(_f1_, _f2_, _f3_, _f4_, _f5_) (/{asterisk} args\... {asterisk}/);
----
is equivalent to
[source,cpp,subs=normal]
----
__target__.with(strf::pack(_f1_, strf::pack(_f2_, _f3_), _f4_), _f5_) (/{asterisk} args\... {asterisk}/);
----
, which, by the way, is also equivalent to:
[source,cpp,subs=normal]
----
__target__.with(_f1_).with(_f2_).with(_f3_).with(_f4_).with(_f5_) (/{asterisk} args\... {asterisk}/);
----

[[Locales]]
== Locales

Strf is a locale-independent library. When you don't specify any facet
object, everything is printed as in the "C" locale.
However, the header `<strf/locale.hpp>` provides the function `locale_numpunct`
that returns a `{numpunct}<10>` object that reflects the numeric punctuation of
the current locale ( decimal point, thousands separator and digits grouping ).
`locale_numpunct()` is not thread safe -- it shall be called while another
thread is modifing the gloabl locale -- but once the returned value
is stored into a `{numpunct}<10>` object, that object is not affected anymore when
the locale changes.

[source,cpp,subs=normal]
----
#include <strf/locale.hpp>
#include <strf/to_string.hpp>

void sample() {
    if (setlocale(LC_NUMERIC, "de_DE")) {
        const auto punct_de = strf::locale_numpunct();
        auto str = strf::to_string.with(punct_de) (*strf::fixed(10000.5))
        assert(str == "10.000,5");

        // Changing locale does not affect punct_de
        // So using it is thread safe
        setlocale(LC_NUMERIC, "C");
        auto str2 = strf::to_string.with(punct_de) (*strf::fixed(20000.5));
        assert(str2 == "20.000,5");
    }
}
----

// The template parameter of `numpuct` specifies the numeric base,
// which means you can apply punctuation to non-decimal base also,
// though this does not relate to localization anymore.

Strf does not use `std::numpunct` for reasons explained in
<<why_not_std_locale#,another document>>.

== Other destinations

Up to here, we only covered things that influence the
content to be printed, not _where_ it is printed.
The <<quick_reference#,quick_reference>> provides a
<<quick_reference#targets,list of target expressions>>
that can be used instead to `to_string`.



//Alternatively,
However, you can also use the classes that derive
from the `{destination}` abstract class template
(listed <<quick_reference#destination_types, here>>).
Each of the target expressions relies in one of them
internally, and they can be used directly instead of
the target expression. This approach is more verbose,
but it has some advantages.

The table below show some examples. Note a pattern there:
all these classes have a `finish` member function that returns
the same as the compact expressions used on the left column.
It is important to call `finish` even if you don't need
the returned value, because it flushes the content remained in
the internal buffer ( though you can also call `flush()` ).

// Alternatively, you can use a class that derives from the
// `{destination}` abstract class template.
// You can see a list of them
// <<quick_reference#destination_types, here>>.
// Each of the target expressions relies in one of them
// internally.

// Now, for each of these target expressions there is
// concrete class that derives from the
// `{destination}` abstract class template.
//  You can see a list of them
// <<quick_reference#destination_types, here>>, and you
// can see bellow example of how to use them:

[caption=,title='examples']
[%header,cols="50,50"]
|===
| Compact form | Equivalent long form

m| auto str = strf::to_string (__args__\...);
m| strf::string_maker dst(_size_); +
strf::to(dst) (__args__\...); +
auto str = dst.finish();

m| auto str = strf::to_string.reserve(__size__) (__args__\...);
m| strf::pre_sized_string_maker dst(_size_); +
strf::to(dst) (__args__\...); +
auto str = dst.finish();

m| auto result = strf::to(stdout) (__args__\...);
m| strf::narrow_cfile_writer<char> dst(stdout); +
strf::to(dst) (_args_\...); +
auto result = dst.finish();

m| char buf[200]; +
auto result = strf::to(buf) (__args__\...);
m| char buf[200]; +
strf::cstr_destination dst(buf); +
strf::to(dst) (__args__\...); +
auto result = dst.finish();
|===

The first advantage of the longer form is that you don't have
to pass all the arguments in a single statement. Thus,
some of the statements may be inside conditionals or loops,
and some of them may use different facets than others:

[source,cpp,subs=normal]
----
strf::string_maker dst;
std::to(dst) (__arg1__, __arg2__);
if (/{asterisk} some condition {asterisk}/) {
    std::to(dst).with(_f1_, _f2_) (__arg3__, __arg4__);
}
while (/{asterisk} \... {asterisk}/) {
    // \...
    std::to(dst).with(_f3_, _f4_) (__arg5__, __arg5__);
}
std::string result = dst.finish();
----

The second reason is naturally to
https://en.wikipedia.org/wiki/Separation_of_concerns[separate concerns]:
you can have one piece of code concerned only
in what is printed, like a functions
that writes to a `strf::{destination}<char>&` :

[source,cpp,subs=normal]
----
void get_message(strf::destination<char>& dst)
{
    strf::to(dst) ("Hello");
    // write stuffs to dst \...
}
----

, while another part of the code (that instantiates the destination object)
decides where the content goes.
// ( by selecting one the concrete classes that derives from `{destination}`).

I know, there is actually nothing really innovative in that design -- it's it's just plain OO,
and it's how peolple already basically do with `std::basic_ostream`.
So, you may question: if Strf can write to `std::basic_ostream` as well
( which it can ), why not just keep using `std::basic_ostream`
instead of start using `strf::destination` ?

// I would say the main reason has to do in how to create a specialization
// of `strf::destination` ( which is explained in
// <<howto_add_destination#,another document>> ).

I would say the main reason is that `strf::destination` is more suitable
to be specialized. As a result, it has more specializations -- like one that
write to `char*`, which you don't have for `std::ostream`. You can also easily
create your own, as explained in <<howto_add_destination#,another tutorial>>.

In case you use {fmt} or `std::format`, the header
`<<iterator_hpp#,<strf/iterator.hpp> >>` defines an output iterator adapter
so that you can also write to `strf::destination` with `fmt::format_to`
( or `std::format_to` ).


////

Ehe header
`<<iterator_hpp#,<strf/iterator.hpp> >>` defines an output iterator adapter
to


so that you can write to `strf::destination`

so that you can reuse code that based
to make it easier to adapt code based on {fmt} or `std::format`
to integrate `strf::destination`



To make its applicability broader, the


augment the applicability


// I would say the main reason is that `std::basic_ostream` is not suitable
// to be specialized from, which is a major flaw for an abstract class.
// It's not only that it is complicated, but also
// but also


There is nothing really new in that design -- it's it's just plain OO,
and it's like it's already done with `std::basic_ostream`.
And you can use Strf to print to `std::basic_ostream` as well, but there are
some advantages in using `strf::destination` instead:

* It is simple to create your own class that derives from `strf::destination`
  ( as explained <<howto_add_destination#,here>> ).
* `std::basic_ostream` is not suitable to all kinds of destinations ( like `char*` ).
* `strf::destination` doesn't store any information regarding formatting, localization,
   or encoding. Its sole concern is where the content goes to.

Notably, `std::format` fixes many of the design flaws of `std::ostream` when it
comes to formatting, but
it doesn't provide an alternative class to abstract destinations; it can write
to output iterators, but that's different. However, it is possible to combine
`std::format` and `strf::destination` with an output iterator adapter,
like the one that is defined in
`<<iterator_hpp#,<strf/iterator.hpp> >>`


////